### ISSUE TITLE
Add SSL security for external HTTP API Endpoints

### ISSUE THREAD

**Issue by rdgoite** [HumanCellAtlas/ingest-central#108]
Communication to Ingest APIs should only be through HTTPS.

**Comment by daniwelter** [comment]
Duplicated by HCA-556: As a DCP API/UI user I would like to only access endpoints secured with HTTPS

**Comment by Bento007** [comment]
What is the progress on this issue?

**Comment by justincc** [comment]
@sampierson @parthshahva @rexwangcc @samanehsan We're getting to the point where we'll be able to switch all our public endpoints to https. As the ingest invokers (upload, analysis) how would like to proceed? Do you want a gradual approach where we initially redirect http and then on an agreed date switch it off?

**Comment by justincc** [comment]
@simonjupp OLS also exposes endpoints I believe. Is there anything that needs to be done here to support https?

**Comment by parthshahva** [comment]
@justincc Upload is not interacting with ingest api at the moment. All our interaction is via rabbitmq. We should coordinate on switching to the secure api endpoint once you guys stop exposing rabbitmq

**Comment by sampierson** [comment]
This will impact the dcp-diag tools.  You could do the redirect thing but that only works if the libraries we happen to be using will follow redirects.  Requests probably does but we’d need to test it to make sure.  I’d be fine fine with a coordinated cut-over.  Less work on your side, and adding an “s” in my code isn’t demanding :)

Sam Pierson
Principal Engineer



chanzuckerberg.com <http://chanzuckerberg.com/>c: +1  <tel:+13105285719>650-422-4140
spierson@chanzuckerberg.com <mailto:sscovanner@chanzuckerberg.com>

**Comment by justincc** [comment]
@parthshahva Yes, putting rabbitmq behind endpoints is on our list for doing soon.

**Comment by justincc** [comment]
@sampierson @rexwangcc @samanehsan The redirect is a one liner. How about we implement this with the redirect on, notify you then turn it off once you've all migrated?

**Comment by justincc** [comment]
Reference in green box https://github.com/HumanCellAtlas/secondary-analysis/issues/461

**Comment by justincc** [comment]
@sampierson I didn't quite understand the situation. It's actually the case that all the HTTPS endpoints are there already, it's just that HTTP still exists as a separate path as well. So you could simply add those "s"'s now. Once we move to a redirect, I hear that the security plan is to keep it in place permanently, so testing redirects on the libraries would also work.

Do you think this would be possible fairly soon? I think we would like to move to the redirect either in the week before Xmas (Mon 17th) or early in the new year.

**Comment by sampierson** [comment]
@justincc aha I didn't realize you had implemented this already.  I'll fix the `dcp-diag` tools today or tomorrow.

**Comment by justincc** [comment]
Fantastic :)

**Comment by rexwangcc** [comment]
@justincc The [PR](https://github.com/HumanCellAtlas/dcp-diag/pull/2) for updating the `dcp-diag` to support Ingest HTTPS APIs is merged. @sampierson and I discussed and agreed to not release a new version of `dcp-diag` utill Ingest enables the https in all of the envs; right now it seems HTTPS is only available in `dev` and `integration`.

**Comment by justincc** [comment]
@rdgoite, what's the timeframe for getting this through to staging then production?

**Comment by aaclan-ebi** [comment]
HTTPS is now available in production. https://github.com/HumanCellAtlas/ingest-kube-deployment/blob/master/production/changelog.md#29-january-2019. 


Please note that the HTTP -> HTTPS redirection is not yet in place.

**Comment by aaclan-ebi** [comment]
Noting here the current public Ingest endpoints which should be using HTTPS:

https://api.ingest.dev.data.humancellatlas.org
https://api.ingest.integration.data.humancellatlas.org
https://api.ingest.staging.data.humancellatlas.org
https://api.ingest.data.humancellatlas.org

https://ui.ingest.dev.data.humancellatlas.org
https://ui.ingest.integration.data.humancellatlas.org
https://ui.ingest.staging.data.humancellatlas.org
https://ui.ingest.data.humancellatlas.org

https://ingest.dev.data.humancellatlas.org
https://ingest.integration.data.humancellatlas.org
https://ingest.staging.data.humancellatlas.org
https://ingest.data.humancellatlas.org
