### ISSUE TITLE
Setup CI/CD Pipeline for Ingest Components in GitLab

### ISSUE THREAD

**Issue by rdgoite** [HumanCellAtlas/ingest-central#109]

**Comment by justincc** [comment]
Seen in https://docs.google.com/spreadsheets/d/155ACGfrgobXy9DI_GduYyHCpkCyFDIa6FvgH8keBdug/edit?ts=5bbbcd2d#gid=0

**Comment by justincc** [comment]
This would be through the Gitlab infrastructure provided by the DCP

**Comment by justincc** [comment]
Duped
