### ISSUE TITLE
Support API Error Metrics

### ISSUE THREAD

**Issue by rdgoite** [HumanCellAtlas/ingest-central#110]
Update logs to support DCP wide effort to gather system wide metrics.

**Comment by justincc** [comment]
Does this have any kind of plan, DCP wide or otherwise?

**Comment by justincc** [comment]
Is linked in CBeta release spreadsheet https://docs.google.com/spreadsheets/d/155ACGfrgobXy9DI_GduYyHCpkCyFDIa6FvgH8keBdug/edit?ts=5bbbcd2d#gid=0

**Comment by justincc** [comment]
This is superseded by [DCP-wide reliability work](https://docs.google.com/document/d/1NeYEWkOj25xdV4hM96q-v-0DLOZynmLnWPqlMI3Tjtk)
