### ISSUE TITLE
Define Runbook for Ingest Infrastructure

### ISSUE THREAD

**Issue by rdgoite** [HumanCellAtlas/ingest-central#111]
As part of the DCP wide goal to make it easy for anyone to set up HCA, we are tasked to provide a runbook that documents how to get the Ingest infrastructure up and running.

See the parent epic for more information regarding the requirements, runbook templates, etc.

**Comment by justincc** [comment]
Seen in https://docs.google.com/spreadsheets/d/155ACGfrgobXy9DI_GduYyHCpkCyFDIa6FvgH8keBdug/edit?ts=5bbbcd2d#gid=0

**Comment by justincc** [comment]
Runbook at https://github.com/HumanCellAtlas/ingest-central/pull/469/files
