### ISSUE TITLE
[Ontology validation] is failing in dev environment

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#12]
**Give the bug a title**

Please give the bug a title that includes the *feature name* followed by a short description (*title*).

* [Login] Not able to login with my account\
* [Validation] Validation failed for a file that should be valid\
* [UI] Spelling mistake in upload instructions

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to spreadsheet upload in the UI 
2. Upload a spreadsheet
3. Click the upload button and wait about 5 second
4. Check Biomaterials in Metadata tab

**Expected behaviour**
Biomaterial metadata with correct ontology values should be valid.

**Actual behaviour**
Biomaterial becomes invalid with following error:

HTTPConnectionPool(host='localhost', port=8088): Max retries exceeded with url: /terms?id=UO_0000003%2C+UO_0000149 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff5b985e7b8>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by danielvaughan** [comment]
Blocked by need for OLS update. At present we will disable ontology validation to get dev test passing.

**Comment by danielvaughan** [comment]
Ontology service updated and test now passing
