### ISSUE TITLE
Ability to specify object attributes of a metadata entity to a separate worksheet

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#126]
As a data submitter, I want to specify a list of properties of an entity in a separate tab in the spreadsheet

e.g. Contacts list to be added in Project's contributors
 
Dev notes:
The importer should have generic implementation of handling "subtabs" (tabs containing properties of entities)
 

Use cases:
Funder tab
publications
familial relationships
reagents
 
This ticket requires clarification on how the user could specify in the spreadsheet that the tab is a subtab containing an entity's property/attribute. 

could be an assumption in the spreadsheet that all header columns will have the format <concrete_entity>.<module attribute> and <concrete_entity id>
could specify in tabs config yml

Replaces HCA-1004

**Comment by justincc** [comment]
We'll re-ask this some other time.
