### ISSUE TITLE
Support wrangler authorisation using minimal initial API

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#127]
Develop an authentication service based on the document Ingest Authentication Proposal

Acceptance Criteria

All Ingest API endpoints require authentication
Standard users can only access endpoints that return data on their own submissions and projects
Users with the wrangler role can see all submission and projects in the system
All services and other boxes can access endpoints without error

Replaces HCA-905

**Comment by justincc** [comment]
Almost certainly won't do any time soon. Anticipate that ingest security for GA will be very mimimal (possibly whitelist). But we can revisit when we need to talk about this.
