### ISSUE TITLE
Create a run book for ingest operations

### ISSUE THREAD

**Issue by morrisonnorman** [HumanCellAtlas/ingest-central#133]

**Comment by morrisonnorman** [comment]
Migrated from JIRA https://www.ebi.ac.uk/panda/jira/browse/HCA-881

**Comment by rdgoite** [comment]
I think this is a duplicate of https://app.zenhub.com/workspace/o/humancellatlas/ingest-central/issues/111. Which of the tickets shall we close?

**Comment by justincc** [comment]
This one
