### ISSUE TITLE
Review accession generation code 

### ISSUE THREAD

**Issue by rdgoite** [HumanCellAtlas/ingest-central#135]
Review accession generating code that was written by @aaclan-ebi to generate accession numbers in ENA. @rolando-ebi & @aaclan-ebi to pair review code and ask for clarification on requirements with @tburdett.

Determine if the code is still fit for purpose for interaction with the USI-API. 
@tburdett is working on a specification document and accepetance criteria.

https://www.ebi.ac.uk/panda/jira/browse/HCA-1139

**Comment by aaclan-ebi** [comment]
Issues of the current archiver:
1. Data conversion - not converting the data to use the latest metadata schema (still currently in v4)
2. Need to setup new AAP account (new AAP endpoint was released)
