### ISSUE TITLE
Handle upload service timeouts when creating upload area

### ISSUE THREAD

**Issue by rdgoite** [HumanCellAtlas/ingest-central#137]
The DCP integration test before failed because the secondary submission didn't get an staging urn because of upload API timeout upon request.

https://www.ebi.ac.uk/panda/jira/browse/HCA-1121

**Comment by aaclan-ebi** [comment]
This should have been fixed by this change: https://github.com/HumanCellAtlas/ingest-client/commit/63b422b22ce002864ec25d53994deef896945ca9#diff-00ad6406b32ab980e02b08fd2a288121
