### ISSUE TITLE
As an HCA-DCP Ingest Wrangler, I would like sequence file metadata to be validated without requiring files to be uploaded.

### ISSUE THREAD

**Issue by rolando-ebi** [HumanCellAtlas/ingest-central#138]
Currently, sequence file metadata isn't triggered for validation until the sequence file has been uploaded. This means there is a delay in checking whether the metadata is valid, and only bring metadata problems up after larger files have been uploaded, which can take a long time. 
Wranglers would like sequence file metadata to be validated like all other metadata, at the time of spreadsheet upload.

Acceptance criteria:

- Sequence file metadata validates along with all other metadata

**Comment by rolando-ebi** [comment]
https://www.ebi.ac.uk/panda/jira/browse/HCA-1112

**Comment by justincc** [comment]
Duplicate of #94

**Comment by justincc** [comment]
Revisit nearer the time
