### ISSUE TITLE
Use authentication endpoints for ingest core

### ISSUE THREAD

**Issue by rdgoite** [HumanCellAtlas/ingest-central#145]
- [ ] Provide authorisation in ingest-core
- [ ] Lock down ingest-core API endpoints
- [ ] Ensure all clients of Core API can perform API calls without error

https://www.ebi.ac.uk/panda/jira/browse/HCA-954

**Comment by justincc** [comment]
@aaclan-ebi How much of this is now covered by your recent security work?

**Comment by aaclan-ebi** [comment]
@justincc I think this is an old ticket, everything should be covered in https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/108
