### ISSUE TITLE
Submission went back to state "valid" after submission/cleanup

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/ingest-central#15]
In the integration environment, take a look at submission 5b04459a6a9fa400077183d6.

http://ui.ingest.integration.data.humancellatlas.org/submissions/detail/5b04459a6a9fa400077183d6/overview

I generated the submission while running the integration test script.  It was created/uploaded/validated and submitted.  A bundle was created: 

http://api.ingest.integration.data.humancellatlas.org/submissionEnvelopes/5b04459a6a9fa400077183d6/bundleManifests

I think I saw it go into "cleanup" status.  Now it is back in "valid" status, and there is a "Submit" button next to it.   That a submission can have a bundle, and be in state "valid", seems like a problem.

**Comment by danielvaughan** [comment]
This is a known bug: https://www.ebi.ac.uk/panda/jira/browse/HCA-712

I am going to push this into the current sprint.

**Comment by danielvaughan** [comment]
Done in JIRA
