### ISSUE TITLE
Ingest large scale data sets into Ingest sandbox

### ISSUE THREAD

**Issue by rdgoite** [HumanCellAtlas/ingest-central#153]
- [ ] Secure scaling test data set from @hewgreen 
- [ ] Ingest data set (paired dev/wrangler)
- [ ] Review output
- [ ] Submit and prepare mock green box script

**Comment by hewgreen** [comment]
I have a ticket in progress in the metadata repo to get the files in place and the sheet up to scratch. Happy to move this to the ingest repo if it makes more sense. Status, I'm waiting for Parth to make a new ec2 for me. 

https://app.zenhub.com/workspace/o/humancellatlas/metadata-schema/issues/510

**Comment by rdgoite** [comment]
These will be done by wrangler/developer pairs.
