### ISSUE TITLE
YAML-based spreadsheet migration

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/ingest-central#158]
As an ingest wrangler, I would like to be able to migrate an existing spreadsheet from one metadata version to another by using a current and an updated YAML file.

**Comment by simonjupp** [comment]
File for migrations is now in place HumanCellAtlas/ingest-central#338

**Comment by daniwelter** [comment]
This is now available directly for spreadsheets rather than using YAML files. Closing the issue for now. If the particular YAML use case becomes relevant again, refile the ticket.
