### ISSUE TITLE
[UI] Submission dashboard flooded with integration tests

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#16]
**What problem does the suggested enhancement solve? Please describe.**

It is difficult to track in-progress and recent submissions of "real" datasets being tested for the pilot launch when the submission dashboard is flooded with integration test submissions.

**What type of enhancement is this?**

Performance, usability

**How will this enhancement benefit wrangers and/or end-users?**

This enhancement will make life **much** easier for all the wranglers when we start testing upload/submission of pilot datasets. This enhancement will not affect end-users at the moment.

**How complex to implement do you estimate this enhancement will be? (High, Medium, Low)**

Low-Medium. I imagine this feature could be implemented by restricting the view to exclude submissions by the integration test (either querying on a submitter ID or querying on something in the metadata). There should also be a corresponding view to show just integration test submissions for the purposes of bug testing.

**How much benefit do you estimate this enhancement will provide? (High, Medium, Low)**

Medium-High

**How urgent is this and is there a specific date it needs to be done by? (High, Medium, Low)**

If this enhancement can't be done by June 15 (the deadline for pilot submitters to give us their metadata/data), then it can wait until after the pilot launch.

**Describe your preferred solution**

An icon or button that let's me "view all submissions by all human wranglers" and "excludes submissions by the Travis CI test".

**Describe alternatives you've considered**

None

**Additional context**

Thanks team :]

**Comment by danielvaughan** [comment]
Added JIRA: https://www.ebi.ac.uk/panda/jira/browse/HCA-937

**Comment by malloryfreeberg** [comment]
Just to clarify, this issue is for the ingest UI, not the Browser.

**Comment by justincc** [comment]
This is now a spike to investigate solutions

**Comment by aaclan-ebi** [comment]
Please explore supporting the ability to delete of submissions to clean up these submissions.

**Comment by MightyAx** [comment]
Deleting is certainly becoming a hot topic and I'm keen to explore. so far we have a spike branch on [ingest-core](https://github.com/HumanCellAtlas/ingest-core/tree/spike/project-filter) and [ingest-ui](https://github.com/HumanCellAtlas/ingest-ui/tree/spike/project-filter) that filters out the integration tests from the project view, if not the submission view.
