### ISSUE TITLE
[Export] Some bundles not created

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#160]
**Give the bug a title**

[Export] Some bundles not created

**To Reproduce**

1. Go to Submit section in dev UI after complete metadata+data validation
2. Click export
3. Wait for all bundles to export
4. Notice that 3/2244 bundles didn't export

**Expected behaviour**

I expected all bundles to export.

**Actual behaviour**

3 bundles weren't generated/exported.

**Impact**

Not able to complete submission to DS.

**Screenshots or Messages**

Submission ID: `5b7d6b20a634720007a10edc` in dev env. 

@aaclan-ebi notes: "hmm we’re getting these errors for those 3 bundles: ingest.exporter.ingestexportservice.BundleDSSError: An error occurred while putting bundle in DSS: HTTPSConnectionPool(host=‘dss.dev.data.humancellatlas.org’, port=443): Max retries exceeded with url: /v1/bundle
s/79036b93-fdeb-4262-a090-295eb7a98d5d?version=2018-08-22T164446.728456Z&replica=aws (Caused by ResponseError(‘too many 500 error responses’))"

"I tried resending the messages again and looks like it created the bundles successfully"

**Comment by rolando-ebi** [comment]
We've fixed the datastore aspects with retries.

However, observed NewConnectionErrors when trying to write metadata to the staging area.

The fix for this in the validator was to use the node's DNS resolver(dnsPolicy: Default). Should try this here
