### ISSUE TITLE
[Upload] 2/3 data files not assigned cloudURLs

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#163]
**Give the bug a title**

[Upload] 2/3 data files not assigned cloudURLs

**To Reproduce**

1. Go to ui.ingest.dev.data.humancellatlas.org
1. Upload spreadsheet for cerebral organoid dataset
1. Copy upload area, use `hca upload` to select area and upload data files
1. Observed only 1/3 of files assigned cloudURL and trigger validation

**Expected behaviour**

I expected all data (fastq.gz) files I uploaded to be matched to their file in the metadata, assigned a clourURL, and be validated.

**Actual behaviour**

Only 1/3 of files (it looks like all the R2 files) were assigned cloudURLs and were validated. The reamining 2/3 of files (I1 and R1 files) do not have cloudURLs.

**Impact**

I cannot complete testing upload/export of this submission.

**Screenshots or Messages**

![screen shot 2018-08-23 at 13 50 20](https://user-images.githubusercontent.com/10993501/44526309-7d989380-a6db-11e8-92f7-832eb2713e2a.png)

**Comment by aaclan-ebi** [comment]
@parthshahva , could you confirm if this is already fixed in dev?

**Comment by aaclan-ebi** [comment]
@malloryfreeberg , is this still occurring?

**Comment by malloryfreeberg** [comment]
@aaclan-ebi  No, I don't believe so.

**Comment by morrisonnorman** [comment]
Closed
