### ISSUE TITLE
Secure RabbitMQ deployment

### ISSUE THREAD

**Issue by rdgoite** [HumanCellAtlas/ingest-central#166]
At the time of writing, the RabbitMQ deployment in all of our Kubernetes clusters (including production) is configured with all default, out-of-the-box settings, and so there's a high risk anyone who knows where to access the Web interface for it can do whatever they please with it.

We need to sort out who has access to the management plugin, and which permissions to grant which users. This is especially needed for our production deployment.

**Comment by aaclan-ebi** [comment]
Setting service type of RabbitMQ service in Kubernetes as ClusterIP.
https://github.com/HumanCellAtlas/ingest-kube-deployment/commit/484894cbee8948e0ad2c0114b8514cbd4a7543b0

Removing the route53 mapping for :
http://amqp.ingest.dev.data.humancellatlas.org:15672/#/
http://amqp.ingest.integration.data.humancellatlas.org:15672/#/
http://amqp.ingest.staging.data.humancellatlas.org:15672/#/
http://amqp.ingest.data.humancellatlas.org:15672/#/

Changes are applied in integration and staging environments.
Staging: next deployment schedule

**Comment by aaclan-ebi** [comment]
How to access RabbitMQ
1. Get the rabbit service local port
```kubectl get service rabbit-service```
2. Get the rabbit service pod
```kubectl get pods | grep rabbit```
3. Access the RabbitMQ Management UI
```kubectl port-forward rabbit-0 15672:15672```

**Comment by aaclan-ebi** [comment]
https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/
