### ISSUE TITLE
Auto-grab latest integration spreadsheet from the metadata-schema repo for use in internal ingest tests

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#167]
should source spreadsheet from metadata-schema repo. Right now we're using an outdated spreadsheet.

**Comment by rolando-ebi** [comment]
We should look at automation of spreadsheet generation/population, or automated grabbing of the spreadsheet from the metadata-schema repo.

In the meantime, we can just grab the spreadsheet used in the dcp integration tests(always kept up to date) and use it in the ingest internal dev tests

**Comment by aaclan-ebi** [comment]
This issue has already been addressed by the work done on this issue https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/307. Closing ticket.
