### ISSUE TITLE
[Validation] Validation stalling on large files 

### ISSUE THREAD

**Issue by willrockout** [HumanCellAtlas/ingest-central#170]
**To Reproduce**

1. Check submission id 5b7db845a634720007a13ac6 on dev ingest site

**Expected behavior**

Large files validate

**Actual behavior**

Large files stuck validating since 8/20

**Impact**

Files don't complete validation can't submit data

**Screenshots or Messages**

If applicable, add screenshots to help explain your problem or the text of any error messages.

Uploaded files to kick of validation in dev ingest and they have been stuck validating since 8/20. The two files are PBMC_RNA_R1.fastq.gz and PBMC_RNA_R2.fastq.gz and are 16Gb and 46Gb respectively. Not sure if this is a ui problem or a validator problem. Parth recommended testing the files outside the ui to see how the validator is handling the files.

**Comment by aaclan-ebi** [comment]
Those files should have triggered jobs in the upload service. The validation ids for those files  are:
-4994c612-1e87-43e7-bc93-41bf5c1f9504
-e830632c-eaa4-4b49-bc47-3ebb1ae8f29f

I believe there were no responses received from the upload service for those validation jobs. The file metadata was last updated 2018-08-22T19:23:55.322Z, which is over a week from now and no redeployments to the validator was made. It should have processed any response if there were. Hi @parthshahva , would you be able to confirm if those validation ids above finished successfully on your end? @willrockout you could upload the files again to trigger the file validation.

**Comment by parthshahva** [comment]
@aaclan-ebi I actually asked @willrockout to create this ticket. The validator provided by ingest was taking a week+ on this file (jobs started on 8/20). This ticket is for you guys to confirm that the validator works as expected on these files **outside** upload infrastructure.

**Comment by aaclan-ebi** [comment]
Hi @parthshahva, I ran the fastq validator against the following files:
PBMC_RNA_R1.fastq.gz(16Gb):  ~7min
PBMC_RNA_R2.fastq.gz (46Gb): ~20min
Memory utilization is consistent  at ~700M.

Hi @willrockout, could you try re-uploading the files and let's see how it goes.
Please give us back the submission id. Thanks!

**Comment by rolando-ebi** [comment]
@parthshahva 

@aaclan-ebi verified this

**Comment by aaclan-ebi** [comment]
![Screen Shot 2018-09-06 at 10.05.19.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/846f860e-353e-4eaf-953e-6a7abc83c8e8)

**Comment by rolando-ebi** [comment]
Ran the fastq validation image on the tools EC2 instance against the largest file. The docker image was built from the python:alpine-3 image instead of the EBS harness image used in the AWS batch fleet. The profile for the run is below:

`Command being timed: "docker run -v /data/wsullivan-rsatija-staging-0:/test 323b8368ba74 fastq_info -r -s /test/PBMC_RNA_R2.fastq.gz"
	User time (seconds): 0.20
	System time (seconds): 0.25
	Percent of CPU this job got: 0%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 18:49.88
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 19076
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 1440
	Voluntary context switches: 17623
	Involuntary context switches: 1605
	Swaps: 0
	File system inputs: 0
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0`

"Maximum resident set size (kbytes): 19076" implies little memory usage.

It looks like the image is functioning correctly which leads me to believe this is a problem with the file validation fleet. Closing this ticket
