### ISSUE TITLE
[API]: /assays endpoint in ingest API is dead

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/ingest-central#172]
The /assays endpoint in the ingest API is still accessible but doesn't actually do anything.

**Expected behaviour**

I expect to either get the assays for that submission back or for the endpoint to not actually be present.
    
**Actual behaviour**

The endpoint is present but doesn't work.

**Impact**

It's tedious and annoying. Please deprecate the endpoint or restore the functionality.

**Comment by malloryfreeberg** [comment]
@justincc have you guys discussed this ticket recently? For doing bundle structure and graph interrogation, we need a quick way to get the UUID of the last process entity in the bundle, in other words, the process entity that links the last biomaterial to a file. This was previously referred to as the "assay" ID, but we don't actually have a concrete "assay" entity anymore. Now we have the ultimate process entity which is basically the "assay".

It would really help us to have a way to ping the ingest API and get the UUID of the ultimate process; either by reanimating the /assays endpoint to point to it or deprecating the /assays endpoint and creating a new one that points to it.

CC @daniwelter

**Comment by justincc** [comment]
@aaclan-ebi @rolando-ebi @rdgoite Any initial thoughts on this?

**Comment by aaclan-ebi** [comment]
Finding assays/analysis is a very expensive query in core at the moment. 

@malloryfreeberg what you can do for now is to get all the input process of the datafiles. Would that work for you?

**Comment by malloryfreeberg** [comment]
I think this is acceptable for now. Thanks @aaclan-ebi :)
