### ISSUE TITLE
metadata is stuck in validating phase even after files go valid

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/ingest-central#18]
metadata is stuck in validating phase even after files go valid

To Reproduce

Steps to reproduce the behaviour:

start ingest only integration test and monitor in logs and UI

Example:

http://ui.ingest.integration.data.humancellatlas.org/submissions/detail/5b0858e2ac80bd00077123a6/overview

Expected behaviour

Metadata goes valid

Actual behaviour

Metadata remains in validating state

**Comment by danielvaughan** [comment]
This looks like the same issue as #11 but in integration

**Comment by parthshahva** [comment]
Example in dev:
http://ui.ingest.dev.data.humancellatlas.org/submissions/detail/5b0ad9815626f4000752697a/metadata. One of the metadata files stuck in validating (envelope marked as validating)

**Comment by danielvaughan** [comment]
This is because of the ontology validation failing to report failure. This has now been resolved.

**Comment by danielvaughan** [comment]
See: https://github.com/HumanCellAtlas/ingest-validator/commit/6cda0e8bfac63aabee36c8ca3434ece5d506b21b
