### ISSUE TITLE
[Importer] Ontology object arrays aren't processed correctly

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/ingest-central#188]
Some ontology fields are object arrays which can contain multiple values. In the spreadsheet, this is captured as:
field.text    field.ontology
foo||bar     id1||id2

In the JSON, this should like something like:
some_field: [
  { text: foo,
    ontology: id1
  },
  { text: bar,
    ontology: id2
  }
]

The importer currently isn't able to do this and leaves the fields concatinated, which means that they fail validation. See http://api.ingest.testing.data.humancellatlas.org/biomaterials/5b96b2cdd32f240008c2a299 fror an example.

Examples of ontology fields this may apply to include genus_species and diseases.

**Comment by rdgoite** [comment]
The changes to support this are currently deployed to dev. I have tested that this works using a very rudimentary test spreadsheet. 

The resulting metadata from the said test can be found here: http://api.ingest.dev.data.humancellatlas.org/biomaterials/5b9ab4a26006e80007c368a3. 

The submission envelope can be found here: http://ui.ingest.dev.data.humancellatlas.org/submissions/detail/5b9ab4a06006e80007c3689f/overview

**Comment by malloryfreeberg** [comment]
I confirmed this worked on a candidate dataset and the ethnicity ontology terms were parsed correctly into an array.
