### ISSUE TITLE
Save spreadsheet in the upload area during submission

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#190]

**Comment by justincc** [comment]
This relates to users uploading the spreadsheet so that we can then consume it but this has been somewhat resolved. May also be required for audit and to be able to provide the spreadsheet to a wrangler on request.

**Comment by claymfischer** [comment]
I quite like this as people also lose/modify their spreadsheets and want to revert back.

**Comment by lauraclarke** [comment]
I think ultimately the UI providing access to the uploaded spreadsheet so people can redownload it. Right now, the wranglers being able to ask to get the original spreadsheet back seems like a good first step in that process.

**Comment by justincc** [comment]
This will be done as a side effect of our simple updates original-spreadsheet-using approach
