### ISSUE TITLE
Submit sequencing data to ENA via USI

### ISSUE THREAD

**Issue by simonjupp** [HumanCellAtlas/ingest-central#195]
Upload sequencing data to USI, will require conversion of fastq file to BAM for 10x experiments

**Comment by justincc** [comment]
As per @aaclan-ebi, currently blocked by issues with USI API.

**Comment by justincc** [comment]
As of 2018-11-01:1618 should have been fixed.

**Comment by justincc** [comment]
May have a relationship to https://github.com/HumanCellAtlas/data-store/issues/1704#issuecomment-439124388
