### ISSUE TITLE
Secure ingest endpoints 

### ISSUE THREAD

**Issue by simonjupp** [HumanCellAtlas/ingest-central#199]
This ticket covers two issues:

1) Securing *service* endpoints that are only intended to be called by other components, such as analysis and upload. For this we will whitelist Google Service Accounts, possibly by their issuer.

2) Securing *submission* endpoints that wranglers or analysis pipelines end up calling. These are all the endpoints that are not service endpoints. This also covers all HTTP verbs (GET, POST, etc.). In auth0 there is a rule called 'privileged-domains' which flag users from certain domains such as ebi.ac.uk with an group 'hca' flag. The current plan is to inspect this and only allow those users to access the ingest UI and API endpoints.

At this stage there will be no endpoints that are accessible to the public at large.

**Comment by justincc** [comment]
Seen in https://docs.google.com/spreadsheets/d/155ACGfrgobXy9DI_GduYyHCpkCyFDIa6FvgH8keBdug/edit?ts=5bbbcd2d#gid=0

**Comment by justincc** [comment]
Upload needs to use private endpoints. Green box are a public submitter just like ordinary submitters. Baseline from public auth might currently be an EBI or Broad address.

**Comment by justincc** [comment]
I need to rephrase the categories in the description since they are arguably misleading (e.g. green box doesn't call its own service endpoints, they are calling the same endpoints that a wrangler would call through the UI)

**Comment by justincc** [comment]
Regarding service endpoints, #267 might be a dupe

**Comment by aaclan-ebi** [comment]
Merged in master and deployed in integration.

**Comment by aaclan-ebi** [comment]
Changes are deployed to production this week: https://github.com/HumanCellAtlas/ingest-kube-deployment/blob/master/production/changelog.md#29-january-2019
