### ISSUE TITLE
Authors in cell_line tab are not being imported correctly.

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/ingest-central#200]
**Give the bug a title**

Spreadsheet upload in dev: Authors in cell_line tab are not being imported correctly . 

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to the following submission: 5ba26c91b93e800009a8ee9b
2. Click on cell_line in the in the Biomaterials tab to open JSON.
3. Scroll down to publications.
4. See authors imported as a single string.

**Expected behaviour**

content: {
describedBy: "http://schema.dev.data.humancellatlas.org/type/biomaterial/8.6.2/cell_line",
schema_type: "biomaterial",
biomaterial_core: {
biomaterial_id: "cell_line_WAe001-A",
biomaterial_name: "embryo_WAe001-A",
biomaterial_description: "Human Embryonic Stem Cell",
ncbi_taxon_id: [
9606
],
genotype: "DCX-Citrine"
},
cell_line_type: "stem cell",
cell_type: {
text: "embryonic stem cell",
ontology: "CL:0002322"
},
disease: {
text: "normal",
ontology: "PATO:0000461"
},
genus_species: [
{
text: "Homo sapiens",
ontology: "NCBITaxon:9606"
}
],
publications: [
{
authors: [
"Thomson JA", "Itskovitz-Eldor J", "Shapiro SS", "Waknitz MA", "Swiergiel JJ", "Marshall VS", "Jones JM"
],
publication_title: "Embryonic stem cell lines derived from human blastocysts.",
pmid: 9804556,
publication_url: "https://www.ncbi.nlm.nih.gov/pubmed/9804556"
}
]
},
  

**Actual behaviour**

content: {
describedBy: "http://schema.dev.data.humancellatlas.org/type/biomaterial/8.6.2/cell_line",
schema_type: "biomaterial",
biomaterial_core: {
biomaterial_id: "cell_line_WAe001-A",
biomaterial_name: "embryo_WAe001-A",
biomaterial_description: "Human Embryonic Stem Cell",
ncbi_taxon_id: [
9606
],
genotype: "DCX-Citrine"
},
cell_line_type: "stem cell",
cell_type: {
text: "embryonic stem cell",
ontology: "CL:0002322"
},
disease: {
text: "normal",
ontology: "PATO:0000461"
},
genus_species: [
{
text: "Homo sapiens",
ontology: "NCBITaxon:9606"
}
],
publications: [
{
authors: [
"Thomson JA, Itskovitz-Eldor J, Shapiro SS, Waknitz MA, Swiergiel JJ, Marshall VS, Jones JM"
],
publication_title: "Embryonic stem cell lines derived from human blastocysts.",
pmid: 9804556,
publication_url: "https://www.ncbi.nlm.nih.gov/pubmed/9804556"
}
]
},

**Impact**

Individual authors are not indexed.

**Screenshots or Messages**

**Comment by rdgoite** [comment]
@zperova can you attach a copy of the spreadsheet that you're using for this? Thanks.

**Comment by zperova** [comment]
@rdgoite It's here: https://drive.google.com/drive/folders/1kfyEYDfu8_G16y214g8JPWj6BYhKhiCu

**Comment by malloryfreeberg** [comment]
We have temporarily fixed this issue by updating the schema to make the `cell_line.publication` field a single object and not an array of objects.
