### ISSUE TITLE
[Importer] author field (array) in JSON not representing array of authors supplied in spreadsheet

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#201]
**Give the bug a title**

[Importer] author field (array) in JSON not representing array of authors supplied in spreadsheet

**To Reproduce**

1. Upload mf-E-GEOD-106540_spreadsheet_v8.xlsx spreadsheet
1. View generated project.json
1. See that only 1 author was put in the `author` array when there are actually multiple authors in the spreadsheet.

**Expected behaviour**

All of the authors listed in author column in the spreadsheet, items separated by double pipes, should be parsed into an array with 1 item per array element.

**Actual behaviour**

Only 1 author was put in the `author` array when there are actually multiple authors in the spreadsheet.

**Impact**

Publications will be missing all but the first author.

**Screenshots or Messages**

What I get:

```
    "publications": [
      {
        "authors": [
          "Segerstolpe A"
        ],
        "publication_title": "Single-Cell Transcriptome Profiling of Human Pancreatic Islets in Health and Type 2 Diabetes",
        "doi": "10.1016/j.cmet.2016.08.020",
        "pmid": 27667667,
        "publication_url": "https://europepmc.org/abstract/MED/27667667"
      }
    ]
```

Spreadsheet:

Authors | Publication title | DOI | PMID | Publication URL | Project shortname |  
-- | -- | -- | -- | -- | -- | --
project.publications.authors | project.publications.publication_title | project.publications.doi | project.publications.pmid | project.publications.publication_url | project.project_core.project_short_name
Segerstolpe   A\|\|Palasantza A\|\|Eliasson P\|\|Andersson EM\|\|Andreasson AC\|\|Sun X\|\|Picelli   S\|\|Sabirsh A\|\|Clausen M\|\|Bjursell MK\|\|Smith DM\|\|Kasper M\|\|Ammala C\|\|Sandberg   R | Single-Cell Transcriptome Profiling of   Human Pancreatic Islets in Health and Type 2 Diabetes | 10.1016/j.cmet.2016.08.020 | 27667667 | https://europepmc.org/abstract/MED/27667667 | Healthy and type 2 diabetes   pancreas |  

Should be:

```
    "publications": [
      {
        "authors": [
          "Segerstolpe A",
          "Palasantza A",
          "Eliasson P",
          ...
        ],
        "publication_title": "Single-Cell Transcriptome Profiling of Human Pancreatic Islets in Health and Type 2 Diabetes",
        "doi": "10.1016/j.cmet.2016.08.020",
        "pmid": 27667667,
        "publication_url": "https://europepmc.org/abstract/MED/27667667"
      }
    ]
```

**Comment by zperova** [comment]
Issue https://github.com/HumanCellAtlas/ingest-central/issues/200 created yesterday is related to this one
