### ISSUE TITLE
As a data submitter, I want to specify a list of properties (modules) of an entity in a separate tab in the spreadsheet

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#203]
The importer should have generic implementation of handling "subtabs" (tabs containing properties of entities)

e.g. 
- Contacts list to be added in Project's contributors
- Cell line publications

This ticket requires clarification on how the user could specify in the spreadsheet that the tab is a subtab containing an entity's property/attribute. 

This could be:
1. an assumption in the spreadsheet that all header columns will have the format <concrete_entity>.<module attribute> and <concrete_entity id>
2. could specify in tabs config yml

TO DO: we should retract the mechanism used to create an object list in a single row like we do for ontologies.

**Comment by justincc** [comment]
This is a broader implementation for the imaging protocol tab issue #219

**Comment by justincc** [comment]
A generic implementation will stop us needing to hardcode tab names in places such as [this](https://github.com/HumanCellAtlas/ingest-client/blob/master/ingest/importer/spreadsheet/ingest_workbook.py#L13). This is also required imminently when wranglers start using spreadsheets with new tab names (e.g. Publications -> Publication). This change should allow us to do both that and handle imaging metadata requirements (many to many relationship between image entities and protocols).

**Comment by justincc** [comment]
@aaclan-ebi will write out a design

**Comment by justincc** [comment]
When this is implemented tell the wranglers so that they can change the test spreadsheets in the metadata-schema repo.

**Comment by justincc** [comment]
Please post a link to the implementation plan when ready.

**Comment by aaclan-ebi** [comment]
Implementation Plan: https://docs.google.com/document/d/114BQJ3SPWt4QJwiaQVGYl6YLCwa1XQy6Zn5GLG9Vmdk/edit#

**Comment by rdgoite** [comment]
To promote the changes further into the deployment pipeline, we would need the integration test spreadsheets to be updated. Is anyone from the wrangler team currently working on this?

**Comment by malloryfreeberg** [comment]
No one is actively working on this, but one of us can if you let us know when you'd like to do the promotion. We are hoping to promote a batch of schema updates to integration this Thursday.
