### ISSUE TITLE
Remove trailing/leading whitespace from JSON string values

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#205]
**What problem does the suggested enhancement solve? Please describe.**

Trailing/leading whitespace in spreadsheet values leads to metadata validation errors.

**What type of enhancement is this?**

Usability

**How will this enhancement benefit wranglers and/or end-users?**

Will prevent users/wranglers from having to remove trailing/leading whitespace in order for metadata to be valid.

**How complex to implement do you estimate this enhancement will be? (High, Medium, Low)**

Low

**How much benefit do you estimate this enhancement will provide? (High, Medium, Low)**

Medium

**How urgent is this and is there a specific date it needs to be done by? (High, Medium, Low)**

Medium (post phase 1)

**Describe your preferred solution**

Trim trailing/leading whitespace from all values in spreadsheet that become "string" JSON types

**Describe alternatives you've considered**

Alternative is to manually remove whitespace in spreadsheet.

**Additional context**

N/A

**Comment by justincc** [comment]
@alegria I have a feeling we may have done this?

**Comment by aaclan-ebi** [comment]
yes! fixed long time ago! :)
