### ISSUE TITLE
Distinct specimens have the same `biomaterial_id`

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/ingest-central#207]
While investigating the cause for https://github.com/DataBiosphere/azul/issues/331, the Azul team identified two scale test bundles in `integration`, each with a `specimen_from_organism_0.json`. We consider these two documents to represent separate metadata entities because the value of `provenance.document_id` is different in each. The `biomaterial_core.biomaterial_id` field is the same in both documents.

The [schema defines](https://github.com/HumanCellAtlas/metadata-schema/blob/ca25b926fb219d8c7d9f0a882417b643e8c0eed2/json_schema/core/biomaterial/biomaterial_core.json#L24) `biomaterial_core.biomaterial_id` as 

```
        "biomaterial_id":{
            "description": "A unique ID for the biomaterial.",
            "type": "string",
            "user_friendly": "Biomaterial ID"
        },
```

This implies that a single specimen (a physical entity) should be identified by a single, distinct value of `biomaterial_core.biomaterial_id`. If `provenance.document_id` uniquely identifies the metadata entity describing that physical entity AND if there should only exist a single, distinct metadata entity describing that physical entity, it has to follow that there must be no more than one `provenance.document_id` value associated with any particular `biomaterial_core.biomaterial_id` value. The fact that we have two `specimen_from_organism` documents with different values for `provenance.document_id` but the same value for `biomaterial_core.biomaterial_id` would violate that rule.

This bug causes the *Specimens* tab in the HCA data browser to display more than one row with the same value in the *Specimen ID* column. Each row on that tab represents a specimen and the *Specimen ID* column displays the value of the `biomaterial_id` field . We could of course display the `document_id` in that column, but as a UUID it would be meaningless to users.

If `biomaterial_id` is not a globally unique identifier, the schema description and the name of the field needs to be changed (the suffix `_id` suggests uniqueness). Otherwise ingest needs to enforce the uniqueness property of that field. IMHO.

**Comment by rolando-ebi** [comment]
@hannes-ucsc From ingest's point of view, the only field in the metadata we look for is the `describedBy`. Every other field is completely ignored. We're not "aware" of `biomaterial_id`, or any other `*_id` field.

The purpose of that field in the spreadsheet(correct me on this if I'm wrong @malloryfreeberg ) is to act as an identifier of a row in the spreadsheet. When parsing the spreadsheet, Ingest's schema-aware spreadsheet converter (i.e Ingest Broker) enforces a uniqueness constraint. The field could instead be called "biomaterial_name" but I imagine it was called "biomaterial_id" to make it clear to spreadsheet users that the field specifies an identifier in the context of their usage.

Is it possible to use the `document_id` here, but then display `biomaterial_id` instead?

**Comment by malloryfreeberg** [comment]
Rolando is correct. `*_id` fields in the metadata content supplied by users are *not* meant to be universally unique in the entire DCP system. They are used by ingest to make the links between entities by their UUIDs (`document_id`), which are universally unique in the DCP. If this isn't clear, we need to update metadata schema repo docs to highlight this.

**Comment by tburdett** [comment]
I do agree with @hannes-ucsc here that the description is misleading.

> "description": "A unique ID for the biomaterial."

If you are completing a spreadsheet as a submitter, this is conveniently short but ambiguous (it would be reasonable to assume you can reference previous submissions this way). And if e.g. the data portal presented this in a mouse-over it would be definitely wrong. I'm ambivalent about the use of `_id` (although changing this will be a breaking change to almost all metadata schema types) but as an absolute minimum think the descriptions have to be updated.

**Comment by diekhans** [comment]
The description is at least inadequate It would be good if
documentation was specific about the type of the identifier
(uuid, user defined, etc).

It would be good in the field naming around ids were consistent.
However, we it would be helpful to avoid breaking changes until
a access library is in use.

**Comment by hannes-ucsc** [comment]
Duplicates https://github.com/HumanCellAtlas/metadata-schema/issues/733
