### ISSUE TITLE
DOI on per project basis 

### ISSUE THREAD

**Issue by ofanobilbao** [HumanCellAtlas/ingest-central#214]
How do we get DOI on per project basis, to track use of HCA? This would help citations whe publishing using HCA data. 
Look at IDR and PDB for this

**Comment by justincc** [comment]
@morrisonnorman just fyi, this it the ticket tracking this requirement

**Comment by justincc** [comment]
Closing as not yet a dev task.

**Comment by lauraclarke** [comment]
Can I get a pointer to where else this is recorded before this ticket is closed. I don't want to lose this @morrisonnorman @justincc

**Comment by justincc** [comment]
This is now being planned and co-ordinated in detail at the DCP level as ticket [226](https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/dcp/226)
