### ISSUE TITLE
Set up monitoring for Ingest components

### ISSUE THREAD

**Issue by rdgoite** [HumanCellAtlas/ingest-central#216]
Define metrics and enable monitoring for:
- [ ] Core
- [ ] Importer
- [ ] Exporter

**Comment by justincc** [comment]
Seen in https://docs.google.com/spreadsheets/d/155ACGfrgobXy9DI_GduYyHCpkCyFDIa6FvgH8keBdug/edit?ts=5bbbcd2d#gid=0

**Comment by justincc** [comment]
Dupe of #369
