### ISSUE TITLE
Linking analysis protocol to bundle

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/ingest-central#223]
Copying over a conversation from [slack 10/19](https://humancellatlas.slack.com/archives/C4LTU5RT8/p1539969559000100)

From @dshiga 
> Analysis protocol metadata is in the analysis envelopes but not in the bundles - seems like it was getting in there before but not anymore? (analysis *process* metadata is there, but analysis_protocol_0.json is missing)

From @tburdett 
> We just had a look and we think both cases are the same - you’ve come at it from two different directions though. In both these scenarios, the submission envelopes have an analysis protocol and analysis process but the link process -> protocol is missing
so e.g. for the first example, you have http://api.ingest.integration.data.humancellatlas.org/processes/5bcb9777593d3c0007227a55/protocols. The submission envelope here is http://api.ingest.integration.data.humancellatlas.org/processes/5bcb9777593d3c0007227a55/submissionEnvelopes (which links to self =  http://api.ingest.integration.data.humancellatlas.org/submissionEnvelopes/5bcb9777593d3c0007227a53)
If you look _here_ for protocols (http://api.ingest.integration.data.humancellatlas.org/submissionEnvelopes/5bcb9777593d3c0007227a53/protocols) then you do actually see one protocol
That explains the difference you’re seeing.

From @aaclan-ebi 
> It seems that the analysis process in ingest http://api.ingest.staging.data.humancellatlas.org/processes/5bb572079e02610007613f2f doesn’t have analysis linked to it http://api.ingest.staging.data.humancellatlas.org/processes/5bb572079e02610007613f2f/protocols .

From @samanehsan 
> we're doing that linking here: https://github.com/HumanCellAtlas/pipeline-tools/blob/master/pipeline_tools/create_envelope.py#L353

The effects of this not linking properly means that the metadata surrounding what version of our pipeline we are running (along with other important metadata) isn't making it back into the datastore.

**Comment by aaclan-ebi** [comment]
I have verified the ff way to link protocols to processes:
`
curl -X PUT -H "Content-Type: text/uri-list" -d "http://api.ingest.integration.data.humancellatlas.org/protocols/5bb6c5851ed6300007863834" "http://api.ingest.integration.data.humancellatlas.org/processes/5bb6c5851ed6300007863835/protocols"
`
and doing

 `curl -X GET "http://api.ingest.integration.data.humancellatlas.org/processes/5bb6c5851ed6300007863835/protocols"` returns the linked protocol to the process.

It seems that in the code,  https://github.com/HumanCellAtlas/pipeline-tools/blob/231a2e810548a2e728e00bf60dbf1565d3890e26/pipeline_tools/create_envelope.py#L60

the url being passed is the protocols resource link "http://api.ingest.integration.data.humancellatlas.org/protocols" and not the actual protocol url (e.g. "http://api.ingest.integration.data.humancellatlas.org/protocols/5bb6c5851ed6300007863834" )

and the ff request is being made:

`curl -X PUT -H "Content-Type: text/uri-list" -d "http://api.ingest.integration.data.humancellatlas.org/protocols" "http://api.ingest.integration.data.humancellatlas.org/processes/5bb6c5851ed6300007863835/protocols"
`

I also noticed that this incorrect request is returning HTTP 204 which is very misleading. I filed a bug ticket in SPRING Data Rest framework JIRA. https://jira.spring.io/browse/DATAREST-1296

 @kbergin , @samanehsan , could you verify if the protocol url being passed is the url of the newly created protocol ? If not, this should be corrected.

I'll let you guys know once I the SPRING issue is resolved.

**Comment by rexwangcc** [comment]
@aaclan-ebi I checked our logs about this, and found 
 `http://api.ingest.integration.data.humancellatlas.org/submissionEnvelopes/5bce1a3b593d3c000722b7f9/protocols` as the protocol URL, so we have been:
- Adding the analysis protocols at: `http://api.ingest.integration.data.humancellatlas.org/submissionEnvelopes/5bce1a3b593d3c000722b7f9/protocols`
- Linking `http://api.ingest.integration.data.humancellatlas.org/submissionEnvelopes/5bce1a3b593d3c000722b7f9/protocols` to `http://api.ingest.integration.data.humancellatlas.org/processes/5bce1a3c593d3c000722b7fb/protocols`

So based on your explanations I guess I should use `http://api.ingest.integration.data.humancellatlas.org/protocols/XXX` instead of `http://api.ingest.integration.data.humancellatlas.org/submissionEnvelopes/5bce1a3b593d3c000722b7f9/protocols` at **ONLY** the linking step right?

**Comment by aaclan-ebi** [comment]
Hi @rexwangcc, yes during linking you must past the actual url of the newly created protocol which is in create_protocol_response['_links']['self']['href']. 

Thanks!

**Comment by samanehsan** [comment]
Hi @aaclan-ebi, is that link equivalent to using create_protocol_response['_links']['protocol']['href'] or is it more reliable to use the 'self' link?

**Comment by rexwangcc** [comment]
@samanehsan Thanks for asking! I was about to asking the same thing! 
E.g. if this line: https://github.com/HumanCellAtlas/pipeline-tools/pull/96/files#diff-c5363cf30132023e251443047cab1a17R92 should be replaced by `analysis_protocol_entity_url 
 = analysis_protocol_response['_links']['protocol']['href']`?

**Comment by aaclan-ebi** [comment]
Good question...hmm I think whichever is fine, but 'self' feels more intuitive to me, like if I'm using it in the code, I want to get the link to itself (to that created entity).

**Comment by rexwangcc** [comment]
Closing with https://github.com/HumanCellAtlas/pipeline-tools/pull/96 and https://github.com/HumanCellAtlas/dcp/pull/181
