### ISSUE TITLE
Import fails when spreadsheet metadata is reformatted through another app

### ISSUE THREAD

**Issue by rdgoite** [HumanCellAtlas/ingest-central#231]
This issue was discovered when @zperova uploaded a spreadsheet (here attached as [`treutlein_error.xslx`](https://app.zenhub.com/files/132741306/bd2f25cd-85c5-459c-bc90-f74a6a9248d4/download)), previously uploaded/updated by @malloryfreeberg ([`treutlein_success.xslx`](https://app.zenhub.com/files/132741306/18582bd9-1cd9-452c-8987-a439ebd59402/download)), that she viewed in and downloaded from Google Drive. When importing through the Ingest Broker, it was reporting the following error:

```
unsupported operand type(s) for -: 'NoneType' and 'int'
```

Other than being viewed and downloaded to Google Drive, there was no other significant changes to the file before it was uploaded through the broker.

**Comment by rdgoite** [comment]
This issue was most likely due to how Google Spreadsheet updated the metadata of the file. There is a [known caveat](https://openpyxl.readthedocs.io/en/2.5/optimized.html#worksheet-dimensions) around this when loading spreadsheet files through the openpyxl library in read-only mode.

A patch to the importer has been added to handle this.

**Comment by zperova** [comment]
@rdgoite I later checked whether downloading the spreadsheet while open in Google Sheets brings up this error but it didn't. I tested in staging.

**Comment by rdgoite** [comment]
Hmmnn. Interesting. I'm not really sure how to reproduce the issue but at least we have the erroneous copy of the spreadsheet. 😅
