### ISSUE TITLE
Ingestion UI page reveals Auth0 credentials in URL when Signing In

### ISSUE THREAD

**Issue by rhiananthony** [HumanCellAtlas/ingest-central#234]
Navigate to https://ui.ingest.data.humancellatlas.org/login
Select Sign In
Look at the URL - this is showing sensitive information which should not be seen by an end user regarding our Auth0 credentials

**Comment by justincc** [comment]
Closing due to no feedback. Please reopen if necessary

**Comment by rhiananthony** [comment]
Reopening. This is not fixed.

**Comment by rhiananthony** [comment]
![Screen Shot 2018-12-03 at 4.38.10 PM.png](https://images.zenhubusercontent.com/5b59e44481fdfb0efe9dd705/84c688ef-0bd1-48fd-87a1-3b7166fce761)

Please look at the URL - this is the login information of the SA user. I don't think this should be visible to a user.

**Comment by justincc** [comment]
This URL is provided by auth0 so I don't believe we have any control over it. Also, I don't see any particularly sensitive information in that URL. Perhaps you could elaborate?

**Comment by aaclan-ebi** [comment]
@rhiananthony, I'm looking into replacing the use of the current auth0 endpoint (i.e. Daniel Vaughan's auth0 endpoint) with the DCP auth0 endpoint and it seems to be exposing same information in the url as well. I believe these parameters are not sensitive information and needed to implement the auth0 flow.

**Comment by justincc** [comment]
Now moving to using Fusillade rather than auth0 directly so any issues can be addressed there.
