### ISSUE TITLE
Integrate main archiver code with the file archiver service

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#238]
This will also mean local testing in a single Docker image.

**Comment by aaclan-ebi** [comment]
The file archiver needs s3 url to upload files, but DSS doesn't provide s3 url of bundle files.
Created a enhancement ticket to DSS https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-store/1704

**Comment by aaclan-ebi** [comment]
Saving file notifications in a file for now. This is done.
