### ISSUE TITLE
Ability to indicate that s3 upload area already exists for submission

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/ingest-central#241]
**What problem does the suggested enhancement solve? Please describe.**

As a wrangler I would like to be able to indicate that upload area with data files already exists for submission in order to be able to point to it and avoid using the hca cli upload tool again.

**What type of enhancement is this?**

Usability and performance

**How will this enhancement benefit wrangers and/or end-users?**
Wranglers and data contributors will only have to upload data once for submission.

**How complex to implement do you estimate this enhancement will be? (High, Medium, Low)**
High

**How much benefit do you estimate this enhancement will provide? (High, Medium, Low)**
High

**How urgent is this and is there a specific date it needs to be done by? (High, Medium, Low)**
Medium

**Describe your preferred solution**

N/A

**Describe alternatives you've considered**

None

**Additional context**

**Comment by zperova** [comment]
This will most likely require coordination between Ingest and Upload service. @parthshahva

**Comment by claymfischer** [comment]
Very happy to see this.

**Comment by rolando-ebi** [comment]
@zperova is this still an issue, or has the ability sync data between s3 buckets resolved the need for this?

**Comment by zperova** [comment]
@rolando-ebi this is no longer relevant.
