### ISSUE TITLE
Minimum additional archiver work for the wranglers to realistically be able to run this process

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#248]
This is the very minimum except for work to get the file archiver running on either the EBI cluster or in a VM.

- [x] Allow the wrangler to submit a project UUID to the Metadata Archiver (MA) rather than bundle UUIDs.
- [x] Create a *single* JSON file containing the file upload details of *all* the files in a project, so that the wrangler only needs to copy this over once.
- [x] Make sure the metadata archiver definitely does not carry on if USI submission fails. We need to avoid archiving mistakes as much as possible.
- [x] Make sure the metadata archiver reports back the number of successful bundle metadata updates in a very clear manner so that wranglers can manually check.
- [x] Script to download files to EBI store from the HCA into the appropriate directory structure. Otherwise wranglers will need to do this manually, in some cases for a large number of files.

See #249 for some minimal quality of life items.

**Comment by claymfischer** [comment]
We'll be leveraging the USI to submit to the archives?

**Comment by justincc** [comment]
Yep, that's how it's being done.
