### ISSUE TITLE
Simple metadata updates for 2019Q2

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#254]
Planning and later implementation for [dcp #222](https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/dcp/222).

Ingest specific parts of the [AUDR RFC](https://docs.google.com/document/d/1XeAw05RAJe20Q1XDF7eLWLGF3gCme4-8l-ZfhtDWOLg/edit?ts=5bf565cc#).

For DCP board purposes this is size M (2 months), estimated one month into Q2

**Comment by hewgreen** [comment]
Specific user requirement from the SCEA:

After submission via USI they would like ENA identifiers to be added to the HCA metadata.

**Comment by lauraclarke** [comment]
This was always the intention, it just requires an update mechanism in place (or for the submission to be automated so accessions are available before the first write to the data store)

**Comment by justincc** [comment]
> Specific user requirement from the SCEA:
> 
> After submission via USI they would like ENA identifiers to be added to the HCA metadata.

Please add this to the use cases doc linked through from the RFC? Thanks.

**Comment by justincc** [comment]
Now waiting for the DCP integration test PR to be approved https://humancellatlas.slack.com/archives/C6SGU0R3J/p1564589623057300
