### ISSUE TITLE
Stop simultaneous requests to upload service for file validation

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/ingest-central#255]
# Sofware Version
Integration/Staging?Prod

# Expected Behavior
Ingest only requests validation on each area + file combination once

# Actual Behavior
https://humancellatlas.airbrake.io/projects/179579/groups/2232609927704590740?tab=overview
Simultaneous requests to validate the same file lead to the validation requests stamping over each other within the batch compute environment.

@rolando-ebi Creating this ticket to reflect the WIP fix to one of the failure paths of integration test

**Comment by justincc** [comment]
@rolando-ebi please comment on whether this is still an issue.

**Comment by rolando-ebi** [comment]
Yes, this is tracked in one of the tickets in our sprint #283

**Comment by justincc** [comment]
Closed in favour of #283
