### ISSUE TITLE
[Core] Multiple save requests -> Conflict

### ISSUE THREAD

**Issue by MDunitz** [HumanCellAtlas/ingest-central#258]
# Software Version
integration/staging?prod

# Expected Behavior
ingest only tries to save once 

# Actual Behavior
multiple requests to save lead to failures and `Conflict Responses`
https://humancellatlas.airbrake.io/projects/179579/groups/2232715498319493616?tab=overview

this has occurred 17k times in the past 6 months

**Comment by rolando-ebi** [comment]
Multiple conflicting save requests are expected due to the optimistic locking approach in mongo db.

The logs should be spammed with less of these messages after deprecating the addInputBundle() API endpoint
