### ISSUE TITLE
Add SSL security for Ingest UI

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#269]
1. Ingest UI must run in HTTPS
2. HTTPS UI Auth0 callback endpoints must be whitelisted DCP Auth0 account (If it's no longer using Daniel Vaughan's endpoint)

**Comment by justincc** [comment]
Is this already done Alegria? I see the [integration UI](https://ui.ingest.integration.data.humancellatlas.org/login) is https.

**Comment by aaclan-ebi** [comment]
AFAIK this must go in sync with https changes in Ingest API too. That's still in integration currently.

**Comment by justincc** [comment]
Still in dev

**Comment by aaclan-ebi** [comment]
This is now deployed in integration.

**Comment by aaclan-ebi** [comment]
This is deployed in production.
