### ISSUE TITLE
Dockerize Ingest UI for it to run in Ingest EKS cluster

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#270]
Tasks:
- [x] 1. Create Dockerfile for Ingest UI (27/03)
- [x] 2. Create kube configs (28/03)

3. Deploy in each environment and change route 53 mappings

- [x] dev (28/03)
- [x] integration (28/03)
- [x] staging (03/04)
- [x] prod (09/04)

- [x] 4. Delete Cloudfront distributions and s3 buckets 
(Try setting up cloudfront to source from https endpoint)

**Comment by justincc** [comment]
If we're going to whitelist the required URLs for auth anyway, is this something that we need to do imminently and is it actually important?

**Comment by aaclan-ebi** [comment]
Noting this ticket here:
https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/358

Instead of fixing the cloudfront distribution set up in prod, we decided to deploy ingest-ui in EKS to be consistent with other Ingest components.

**Comment by aaclan-ebi** [comment]
Deployed in dev

**Comment by aaclan-ebi** [comment]
Deleted all s3 buckets and cloudfront distributions and code references to those.
