### ISSUE TITLE
Identify notifications required for data contributors

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#272]
@malloryfreeberg commented on [Tue Dec 04 2018](https://github.com/HumanCellAtlas/hca-data-wrangling/issues/68)

**Description of the task:**

Create document describing what to notify data contributors about during their data submission journey.

Doc started [here](https://docs.google.com/document/d/1txMb2OwCckmV7hI2WxophBeErKvczRbK-jOw-lkw0mg/edit).

**Acceptance criteria for the task:**

- [x] Make draft of Google doc
- [x] Finalize Google doc
- [x] Circulate doc with ingest team

---

@malloryfreeberg commented on [Tue Dec 04 2018](https://github.com/HumanCellAtlas/hca-data-wrangling/issues/68#issuecomment-444167990)

Pinging @morrisonnorman and @gabsie on this issue as we are all working on it.

**Comment by malloryfreeberg** [comment]
Notification requirements outlined [here](https://docs.google.com/document/d/1txMb2OwCckmV7hI2WxophBeErKvczRbK-jOw-lkw0mg/edit#heading=h.84nggckvzpi4).

@justincc 

Please close this issue if the document satisfies your needs.

**Comment by justincc** [comment]
Could you remind me why dev needs this document? Isn't this all wrangler mediated for now?

**Comment by malloryfreeberg** [comment]
Yes, this is all wrangler-led for now. Just doing my due diligence by posting that the ticket is done and putting it on your radar for future development work.
