### ISSUE TITLE
Allow green box to authenticate against the ingest API

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#274]
* Set up GCP account (unknown requirements or permissions yet) or an auth0 client account for green box.
* Core should be able to verify the GCP or auth0 client.

**Comment by aaclan-ebi** [comment]
Investigating on how to verify s2s access tokens in ingest.

**Comment by aaclan-ebi** [comment]
PR: https://github.com/HumanCellAtlas/ingest-core/pull/48

**Comment by aaclan-ebi** [comment]
Provided the following target dates:
integration: 09/01/2019
staging: 16/01/2019
prod: 23/01/2019

**Comment by aaclan-ebi** [comment]
Changes to verify self-issued tokens using Google service accounts credentials are now deployed in dev.

**Comment by aaclan-ebi** [comment]
Filed a ticket for greenbox to use self-issued tokens instead of the auth0 token from Dan's auth0 endpoint: https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/secondary-analysis/481.

**Comment by aaclan-ebi** [comment]
Change to authenticate requests in messaging endpoints are deployed in dev.

**Comment by aaclan-ebi** [comment]
The changes to accept token from service accounts is already deployed in production.
