### ISSUE TITLE
Investigate DCP-wide monitoring facilities and configure simple monitoring that doesn't require ingest changes

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#288]

**Comment by justincc** [comment]
[DCP-wide Grafana dashboard](https://metrics.dev.data.humancellatlas.org/)

[Ingest monitoring master document](https://docs.google.com/document/d/1PxDtQXYgrdFGuo1MPY0uJK7o6QAxBR9AofTc4gq8Ofc/edit#) - contains links to Matt's monitoring RFC. Please add to this for what we can currently monitor in ingest.

**Comment by justincc** [comment]
As discussed @rdgoite will split out another ticket for more detailed request tracing to help ingest and put this in product backlog for now.

**Comment by rdgoite** [comment]
I made a separate ticket for improving Ingest traceability in #361.

**Comment by justincc** [comment]
Some graphs now at https://metrics.dev.data.humancellatlas.org/d/dLLhy0qik/ingest

Doing some thinking now about what more we would like to measure in Grafana for later team discussion.
