### ISSUE TITLE
[UI] 'NoneType' object has no attribute 'title'

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#29]
**To Reproduce**

Steps to reproduce the behaviour:
1. Go to 'ui.ingest.dev...'
2. Click on 'New submission'
3. Upload new spreadsheet

**Expected behaviour**
    
* I expected to see a success message for spreadsheet being ingested.

**Actual behaviour**

* I observed the error message shown.

**Screenshots or Messages**

![screen shot 2018-06-01 at 14 12 10](https://user-images.githubusercontent.com/10993501/40842514-09b132c2-65a6-11e8-9469-69427ce70a58.png)

**Comment by rdgoite** [comment]
Importer v2 is still a little sensitive to the structure of the spreadsheets file it can process. The particular [test spreadsheet](https://humancellatlas.slack.com/files/U6CB89VLJ/FAZQL4FC4/test.xlsx) for this issue has a few currently unhandled incompatibilities:
1. It contains a "Contacts" worksheet, while the importer expects "Contact"
2. Donor metadata is specified in "Donor" spreadsheet that do not match an entry in the reference schema template.

While a more graceful handling might be desired for these, the current workarounds to these issues respectively are:
1. Rename the "Contacts" worksheet to "Contact".
2. Rename the "Donor" worksheet to "Donor Organism".
