### ISSUE TITLE
Account for support for paired validation via upload support

### ISSUE THREAD

**Issue by parthshahva** [HumanCellAtlas/ingest-central#295]
Date these breaking changes are proposed to be promoted to integration: 2/15/19. 

1 and 2 below should not take long for ingest to implement to fix the breaking change. 3 can occur when ingest is ready to request validation of multiple files (old api endpoint has not been removed)

1) a) Merge https://github.com/HumanCellAtlas/fastq_utils/pull/4 b) tag fastq_utils c) use latest tag of fastq_utils in ingest_validation

2) This is a sample payload post validation: ```{'validation_id': 'df3869fb-b5e7-466e-8523-e21675665b10', 'command': '/validator /data/deadbeef-dead-dead-dead-475701957500/small_file', 'exit_code': 1, 'status': 'completed', 'stdout': 'invalid\n', 'stderr': '', 'duration_s': 0.02052164077758789, 'exception': None, 'upload_area_id': 'deadbeef-dead-dead-dead-475701957500', 'names': ['small_file']}```

Ingest will need to make a change to accept key `names` instead of `name` and iterate through the files in the results payload

3) (Optional) The old endpoint is still up. When ingest is ready to validate paired fastq files, ingest can utilize the /v1/{upload_area_uuid}/validate endpoint by passing 'files' via the payload instead of passing a file via the path.

**Comment by justincc** [comment]
1) merged. @rolando-ebi where are we with 2). Do you think this is something we can do before the 15th or do we need longer, bearing in mind other long meetings, etc. that we need to have before then?

**Comment by rolando-ebi** [comment]
@justincc 

> Do you think this is something we can do before the 15th or do we need longer

We can be using the new endpoint for the 15th, the validation of paired fastqs may take a bit longer

**Comment by justincc** [comment]
> @justincc
> 
> > Do you think this is something we can do before the 15th or do we need longer
> 
> We can be using the new endpoint for the 15th, the validation of paired fastqs may take a bit longer

Cool, let's hit that for Fri 15th then.

**Comment by justincc** [comment]
@parthshahva Regarding 3) where is there more information on the new endpoint?

**Comment by parthshahva** [comment]
@justincc Documentation for all endpoints is available at https://upload.dev.data.humancellatlas.org/

**Comment by justincc** [comment]
Completed
