### ISSUE TITLE
Number conversion from excel

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/ingest-central#296]
**Importer throws 'should be number at' error but should automatically convert**

**To Reproduce**

Upload a spreadsheet from excel to staging with a number formatted by excel as text in a field that requires a number.

**Expected behaviour**

The importer should try to convert number fields to numbers and only throw this error if it fails to automatically convert from a string.

**Actual behaviour**

This error is thrown for the value '5' which should be converted to a number without any problems as this is from the example int he metadata.

**Impact**

Wrangler must manually edit all fields. Cannot produce input for integration tests without manual editing.

**Comment by justincc** [comment]
How much pain does this cause you?

**Comment by hewgreen** [comment]
Huge pain. Excel sheets have to be edited before every upload if the typing reverts (which it does a lot). This was supposed to be fixed previously.

Related to this is the number to string typing problem in nested arrays that is completely blocking us from ingesting imaging datasets.

**Comment by justincc** [comment]
Number to string typing is #302

**Comment by aaclan-ebi** [comment]
Fix is in dev and integration.

staging promotion: 20th Feb
production: 27th Feb
