### ISSUE TITLE
Trim leading and trailing whitespace from spreadsheet values when converting to JSON.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#297]
**Please make ingest aware via Slack before submitting a suggestion**

1. What problem does the suggested enhancement solve? Please describe.

I'm always frustrated when I try to upload a spreadsheet that has extra spaces after some metadata values and the metadata goes invalid because the value doesn't match the enum/ontology exactly.

2. What type of enhancement is this?

Performance, usability

3. How much benefit do you estimate this enhancement will provide? (High, Medium, Low)

Medium (Unable to ingest spreadsheets with whitespace atm, and tracking down whitespace is very time-consuming)

4. Please describe a solution

When individual values are grabbed from the spreadsheet, strip trailing and leading whitespace prior to putting in the JSON

**Comment by claymfischer** [comment]
I would argue this benefit is **high** - it's a common issue that will cost data generators a lot of time to resolve.

**Comment by aaclan-ebi** [comment]
Fix is in dev and integration.

staging promotion: 20th Feb
production: 27th Feb
