### ISSUE TITLE
Design improvements to core scalability and reliability

### ISSUE THREAD

**Issue by rolando-ebi** [HumanCellAtlas/ingest-central#299]
At the moment, the core buffers order-critical state messages for re-ordering. This means that if we lose a core instance we will lose critical events messages that were buffered in memory. To address this, we should make the core completely stateless and handle the message ordering elsewhere.

Acceptance criteria:

- The ingest-core component is completely stateless
- Critical state event messages emitted from the core have their order ensured elsewhere before they hit the state tracker

**Comment by justincc** [comment]
This ticket concerns planning and design. Done criteria is defining what we are going to do.

**Comment by justincc** [comment]
[Design document](https://docs.google.com/document/d/1HVC5_r_2mZ-a8huxaa4wOGdoK9R-yc6JW-B3AVcBbXg/edit?ts=5c741f81#)
