### ISSUE TITLE
File-upload messages are dropped when files uploaded before File resources created in a submission envelope

### ISSUE THREAD

**Issue by rolando-ebi** [HumanCellAtlas/ingest-central#30]
**To Reproduce**

1. Create a submission envelope
2. Upload files that are part of the submission
3. Upload the spreadsheet after all files uploaded
4. No files will ever get assigned a cloudUrl

**Expected behaviour**

Files still get a cloudUrl 
    
**Actual behaviour**

No files will ever get assigned a cloudUrl

**Comment by danielvaughan** [comment]
JIRA Created: https://www.ebi.ac.uk/panda/jira/browse/HCA-974

**Comment by aaclan-ebi** [comment]
Fix was deployed to production last 17th July.

**Comment by aaclan-ebi** [comment]
Unintentionally closed. Reopened.
