### ISSUE TITLE
Report per bundle export errors

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#301]
Currently all export processes are writing to the same document (i.e. submission envelope) to report the errors. This might cause failure in the actual reporting. 

Suggestion: Track export errrors in separate document
option 1: submission error - new collection instead of extra field in submission env
option 2: bundle manifest - bundle level document to track the error

**Comment by rolando-ebi** [comment]
This is done thanks to @MightyAx recent work

**Comment by MightyAx** [comment]
For reference: https://github.com/HumanCellAtlas/ingest-central/issues/447
