### ISSUE TITLE
Upgrade eks-cluster to resolve vulnerability issue with Docker images

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#304]
Refers to recent Slack notifications (links coming soon)

**Comment by rolando-ebi** [comment]
As we want to use the dev cluster to test these kinds of changes, this is blocked until we have a stable dev cluster with correct Terraform state

**Comment by justincc** [comment]
Dev and test updated
Integration env update blocked because integration tests failing
Staging/prod blocked by today's deployment
