### ISSUE TITLE
Test metadata archiving and improve logging 

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#305]
1. Verification of the issue Mallory reported (script hanging and printing some weird details).
2. Print more info regarding status of submission/validation in the USI.
2. Add ability to view submission/archiving result in the archiving script.

**Comment by aaclan-ebi** [comment]
Made the submission part idempotent so that if the script timed out waiting for the validation or result, the user should be able to safely rerun the script and show the result if USI jobs has completed.
