### ISSUE TITLE
Extend existing ingest integration test for performance testing

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#307]
Covering both primary and secondary submission. This builds on existing code.

**Comment by aaclan-ebi** [comment]
Tasks:
[ ] Update current integration test to not use glioblastoma dataset
[ ] Extend current integration test to cover secondary submission
[ ] Design how to do performance testing
[ ] Implement ^

**Comment by aaclan-ebi** [comment]
Suggestions:
[ ] added the checks that entities will be linked [this sprint] 
[ ] Isolate data from primary submission to be used the secondary submission [Future sprint]

**Comment by aaclan-ebi** [comment]
This is now running in Gitlab but the integration tests needs to be transferred to the HumanCellAtlas group. Coordinating that with Brian H/Parth.

GitLab project: https://allspark.dev.data.humancellatlas.org/aaclan-ebi/ingest-integration-tests

Current status: https://github.com/HumanCellAtlas/ingest-central#status-of-integration-tests

**Comment by aaclan-ebi** [comment]
Now moved to HCA group https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/ingest-integration-tests
