### ISSUE TITLE
Landing page for new submission should be metadata tab

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#31]
**What problem does the suggested enhancement solve? Please describe.**

It is confusing when - after clicking "New submission" from the submission dashboard, the UI takes me to the Overview tab instead of the Metadata tab. Which means I have to know to click over to Metadata in order to find the spreadsheet upload tool.

**What type of enhancement is this?**

Usability

**How will this enhancement benefit wrangers and/or end-users?**

Wranglers can be taught to navigate to the Metadata tab, but other users will find it confusing to land on the empty Overview tab after clicking New Submission

**How complex to implement do you estimate this enhancement will be? (High, Medium, Low)**

Low

**How much benefit do you estimate this enhancement will provide? (High, Medium, Low)**

High

**How urgent is this and is there a specific date it needs to be done by? (High, Medium, Low)**

Not urgent for pilot since we won't have outside users using the UI.

**Describe your preferred solution**

Clicking "New submission" should bring users to the page where they can directly upload a spreadsheet.

**Describe alternatives you've considered**

NA

**Additional context**

**Comment by aaclan-ebi** [comment]
This currently fixed in dev and will be promoted to integration by next wk.
