### ISSUE TITLE
[Validation] Spreadsheet upload error with cryptic error message

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#310]
**Give the bug a title**

[Validation] Spreadsheet upload error with cryptic error message

**To Reproduce**

1. Upload spreadsheet.
1. See error

**Expected behaviour**

I expect the spreadsheet to import and then present the validation error, or at least show where I can find the error to try to fix it.

**Actual behaviour**

Spreadsheet didn't import, error thrown, don't know where it is. Submission ID: `5c6e95580c5b8e0007243579`

**Impact**

User will have a difficult time tracking down what is wrong in their spreadsheet.

**Screenshots or Messages**

![screen shot 2019-02-21 at 13 00 15](https://user-images.githubusercontent.com/10993501/53171062-95dd6280-35d9-11e9-91ec-72b05d54145e.png)

[mf-Meyer-spreadsheet-v7.xlsx](https://github.com/HumanCellAtlas/ingest-central/files/2889360/mf-Meyer-spreadsheet-v7.xlsx)

**Comment by MightyAx** [comment]
[Link to UI](https://ui.ingest.staging.data.humancellatlas.org/submissions/detail/5c6e95580c5b8e0007243579/overview)
[Link to API](https://api.ingest.staging.data.humancellatlas.org/browser/index.html#https://api.ingest.staging.data.humancellatlas.org/submissionEnvelopes/5c6e95580c5b8e0007243579)

**Comment by MightyAx** [comment]
More information given in parser error messages, and parser reporting multiple messages (rather than just one).
solved by ingest-client#47
