### ISSUE TITLE
Try removing the ingest core internal metadata update event queues

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#317]
These may no longer be necessary. If so then removing them would simplify our code and allow multiple instances of ingest-core, though state tracking would also still need to be scaled.

Acceptance criteria:
- [ ] Remove queues
- [ ] Pass unit tests
- [ ] Pass ingest-core + state tracker reliability test
- [ ] Assess any performance change with ingest-core + state tracker performance test

**Comment by rolando-ebi** [comment]
After testing this we see that order is preserved. However, it’s slow; each HTTP request must wait for the core to send a message to the state tracker, as opposed to just dropping a message into an internal buffer in memory

Increasing number of core instances, plus making the broker do concurrent requests, should let us see the speeds we’re used to, or better.

**Comment by justincc** [comment]
Yeah, the problem is that we may not be able to scale core without removing the single instance limit AND we need more than one instance for greater reliability anyway. So ultimately we probably need to deploy this with a larger number of core instances and concurrent requests. Let's discuss when you're back and create a ticket for this, though it won't be done immediately.
