### ISSUE TITLE
S3 XML is being cached in cloudfront causing delay in updating the latest schemas in Ingest

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#319]
https://api.ingest.dev.data.humancellatlas.org/schemas/search/latestSchemas?size=1000 should be returning the latest schema versions

https://humancellatlas.slack.com/archives/C9AJZ9LF9/p1551374869006000

**Comment by aaclan-ebi** [comment]
Possible solution is to do cache invalidation and do the POST schemas/update after it. This will make sure that latest schemas endpoint will return the latest schema versions.

Noting here the slack convo on another occurrence of this issue: https://humancellatlas.slack.com/archives/C9AJZ9LF9/p1552591743011400

**Comment by rolando-ebi** [comment]
This is no longer being cached after we updated the cloudfront to never do caching, circa AWS training in April 2019
