### ISSUE TITLE
 [Validation] Linking fields in spreadsheet being converted to JSON content

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#32]
**To Reproduce**

Steps to reproduce the behaviour:
1. Upload `test.xlsx` spreadsheet which contains `protocol_core.protocol_id` fields in biomaterial tabs indicating which protocols were used to generate those biomaterials.
2. Validation fails for those biomaterials with error message `Error: Additional properties are not allowed ('protocol_core' was unexpected) at root of document`

**Expected behaviour**

I expect that linking fields in the spreadsheet are known to the importer and only used to generate `links.json`, not converted to JSON content and injected into the biomaterial JSON.

**Actual behaviour**

It appears that the converter/importer has converted the protocol fields in biomaterial tabs to JSON content in the biomaterial JSON, which fails validation because those fields are not a part of the JSON schema and are flagged as "additional fields" which aren't allowed.

**Screenshots or Messages**

![screen shot 2018-06-04 at 10 09 05](https://user-images.githubusercontent.com/10993501/40908680-5a195a7e-67df-11e8-8649-2db590c7a38c.png)

**Comment by aaclan-ebi** [comment]
The importer uses the header column keys in row 6 of the spreadsheet. It looks like link column key is misspelled `enrchment_protocol.protocol_core.protocol_id` and the first part of the key `enrchment_protocol` is not being recognised by the importer.

TODO:
Warnings should be added in the importer if it found some unrecognised column and tab names.

**Comment by aaclan-ebi** [comment]
Renaming and converting this ticket to enhancement.

**Comment by aaclan-ebi** [comment]
Looks like this is also happening to protocols to process links, converting this back to bug.

**Comment by aaclan-ebi** [comment]
The link column being added in the json is process.process_core.process_location which is not an id column and not a valid link column. A jira ticket has been added to support the adding of additional process information in biomaterials and files tab in spreadsheet.

**Comment by danielvaughan** [comment]
JIRA Created: https://www.ebi.ac.uk/panda/jira/browse/HCA-992

**Comment by malloryfreeberg** [comment]
I've just experienced this again with the `process.insdc_experiment` field in the sequence file tab.

<img width="801" alt="screen shot 2018-06-12 at 17 02 11" src="https://user-images.githubusercontent.com/10993501/41302704-1691840e-6e63-11e8-987f-3cdd74c473e1.png">

**Comment by malloryfreeberg** [comment]
@aaclan-ebi Is there a fix for this in dev that I can test?

**Comment by aaclan-ebi** [comment]
Hi @malloryfreeberg , yes this feature is already in dev. You can add additional information about the process in the biomaterials/files worksheet. Please let us know if you see any issues.

**Comment by malloryfreeberg** [comment]
Ok. I'll check in dev and report back.

**Comment by malloryfreeberg** [comment]
Looks good in dev! 👍

**Comment by aaclan-ebi** [comment]
The changes has been released to production last 17th July. Closing this.
