### ISSUE TITLE
Investigate the performance characteristics of checking submission validity by inspecting all metadata states in the mongodb

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#321]
Rather than with the current state tracking method.

It should be possible to do this with some separate test code rather than within an existing component.

**Comment by justincc** [comment]
Test state queries for a large number of metadata documents (>150k)

**Comment by rolando-ebi** [comment]
See this python notebook for a walkthrough and demonstration of this investigation: 

https://github.com/HumanCellAtlas/ingest-central/blob/master/notebooks/mongo_state_tracking.ipynb

**Comment by justincc** [comment]
Could you put an abstract at the top that summarizes the findings?
