### ISSUE TITLE
[Importer] Importer fails to import when tab is mis-named

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#324]
When trying to upload an older spreadsheet version in which the project module tab names have not been renamed (e.g. from "Contacts" to "Project - Contributors"), I get the follow error. The message is a bit cryptic, but I could figure out what it meant.

I would expect the importer to still import/convert the spreadsheet and *then* throw an error about an unidentified Contact tab (or better yet, smartly be able to tell that this is supposed to be the "Project - Contributors" tab).

![screen shot 2019-03-01 at 16 40 53](https://user-images.githubusercontent.com/10993501/53652520-feaf8500-3c40-11e9-9750-40efb15e8b19.png)

**Comment by malloryfreeberg** [comment]
@tburdett

**Comment by malloryfreeberg** [comment]
Encountered a similar error from another data contributor. Used "Donor" as the tab name instead of "Donor organism".

![screen shot 2019-03-04 at 09 54 50](https://user-images.githubusercontent.com/10993501/53725316-ab694c80-3e63-11e9-901b-6ee71f860589.png)

**Comment by justincc** [comment]
How does it benefit if an error is thrown after import/convert instead of during?

**Comment by malloryfreeberg** [comment]
If the error is throw during import, it is the only error we see and have the opportunity to fix. There could be 10s or 100s of validation errors, and it is way more efficient to import the whole spreadsheet and display all the errors at once than to only show 1 error, we have to fix it and re-upload, then we get shown 1 more error, we have to fix it and re-upload, and repeat this for however many errors there are.

**Comment by justincc** [comment]
So if, say, the validation process took place in the browser this wouldn't be such a problem?

**Comment by malloryfreeberg** [comment]
Ideally the validation errors would all be displayed in the ingest UI (browser), yes. Right now, *if* the import is successful, only the first error per submittable type is displayed in the ingest UI, but wranglers can get to all validation errors by interrogating the ingest API, which is sufficient at the moment. If an error is thrown *during* import, wranglers never see any other errors except that first one, which - as stated in the previous comment - means we have to fix that error right then and re-upload to then see any further errors.

**Comment by tburdett** [comment]
It's intended that submission clients are able to implement their own import/conversion step (e.g. lab specific brokers, green box submission pipelines). These won't all use the same format for submission (for example, it is allowed for clients to define their "own" broker format, and UCSC at one time was considering building a tagstorm-based broker). Splitting validation logic across multiple client implementations leads to inconsistencies that are difficult to debug and track.

This is more complexity than our current implementation needs, but the design provides for both a clean audit trail (for wranglers) of what failed during validation and a clean separation of concerns (for developers) by restricting the scope of the importer and the validator and ensures the importer is loosely coupled to the schema.

**Comment by justincc** [comment]
Without addressing the main issue of this ticket, I would be pretty reluctant to try and automatically recognize that Contacts -> Project.Contributors. This will take dev time and introduce complexity into the codebase for an issue that should disappear over time anyway.

**Comment by lauraclarke** [comment]
I am not sure we need the importer to automatically recognise synonyms and map them but to import and validate everything it can recognise and then throw the errors for the things it cannot mean the wranglers could fix all the errors found in one go and try again rather than have repeated round of error discover required because a submitter has monkeyed with tab names
