### ISSUE TITLE
Operator Documentation (RunBooks)

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/ingest-central#327]
Internal.

Runbook should detail how to deploy the component.
Runbook should detail how to roll-back a deployment.
Runbook should provide guidance on how to diagnose / resolve common problems.

Create your RunBook on allspark.dev.data.humancellatlas.org
Put a link to it in this page: https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/home

Examples:

https://github.com/HumanCellAtlas/ingest-central/blob/master/release-manager-playbook.md

[SOP: Releasing new Versions of DCP Software](https://docs.google.com/document/d/1HbSWuIABaavaHpCwaO0peA_uwTW5wBCdRnYoz7ZVQuQ/edit?ts=5b0d7550#heading=h.yw6cvy5vlmbu)

[Playbook template in doc form](https://docs.google.com/document/d/1EPcN1tEIwMuzRXj8JPARd-Vgnc3sXJvwQOEcVWkVaYc/edit)

**Comment by justincc** [comment]
Runbook at https://github.com/HumanCellAtlas/ingest-central/pull/469/files but this does not cover the requirements. It also needs to be updated since last time was 2018-06

**Comment by justincc** [comment]
Moved to https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/Ingest-Runbook

**Comment by rhiananthony** [comment]
This is a Q3 priority, can we please set a milestone (Q3 milestone 3?) and set an owner?

**Comment by justincc** [comment]
I have set the milestone but we will not attach an owner until it is in a sprint and someone picks it up.

**Comment by stahiri** [comment]
This work has shifted to Q4 as carryover MUST HAVE work. I've updated the release and milestone.

**Comment by rhiananthony** [comment]
I created the base runbook from the readme guide in the ingest deployment repo. This is sufficient for the Q4 objective, so we are closing this ticket at this time.

**Comment by stahiri** [comment]
@justincc it looks like this objective is complete as there are ingest runbooks published to the wiki (https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/Ingest%20Deployment%20Runbook and https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/Ingest%20Runbook) so I believe this ticket can be closed. Can you please **confirm** and **close**?
