### ISSUE TITLE
[Validation] Validation fails on missing required field, but field IS present

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#33]
**To Reproduce**

1. Go to metadata spreadh upload in the UI 
2. Upload `test.xlsx` spreadsheet
3. See error that 'instrument_manufacturer_model' is required property but is missing.

**Expected behaviour**

I expected that this field would validate as it is required and is present in the spreadsheet.

**Actual behaviour**

The sequencing protocol tab/schema went invalid due to `Error: 'instrument_manufacturer_model' is a required property at root of document`, which suggests that the field is missing but the field is in the spreadsheet, both the text and ontology curie.

**Screenshots or Messages**

![screen shot 2018-06-04 at 10 22 32](https://user-images.githubusercontent.com/10993501/40909348-41ce5d6e-67e1-11e8-85be-4b127426d33b.png)

![screen shot 2018-06-04 at 10 23 18](https://user-images.githubusercontent.com/10993501/40909386-54b8fa88-67e1-11e8-9888-acb206ed3646.png)

**Comment by aaclan-ebi** [comment]
The sequencing protocol in the spreadsheet was successfully added and validated. However, it
looks like the an empty row is being processed and added by the importer. The fix should be on handling and ignoring empty rows in spreadsheet file.

**Comment by danielvaughan** [comment]
Work around is to delete in spreadsheet all the rows below the last complete data row.

**Comment by aaclan-ebi** [comment]
Fix for this was released to production last 17th July.
