### ISSUE TITLE
Ensure secrets do not leak into source code

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/ingest-central#331]
Verify that all developers are using Git Secrets.

https://github.com/awslabs/git-secrets
https://cloud.google.com/blog/products/gcp/help-keep-your-google-cloud-service-account-keys-safe
https://docs.google.com/document/d/1_7deaZd2XbjUetVJs8EsQg6JbW_MEX2iFgXpnR_PyYs/edit#heading=h.4f1e34ah25ia

**Comment by stahiri** [comment]
@rdgoite - I believe ingest devs are using git-secrets. Can you confirm and update this ticket as appropriate?

**Comment by stahiri** [comment]
@rdgoite - please advise if this work is complete. I believe it is; if so, please update and close out this ticket!

**Comment by rdgoite** [comment]
Everyone has so far setup git-secrets in their local dev environment. However, I still have to verify if everyone has set them up for each of our repositories.
