### ISSUE TITLE
Add security.txt file to all repos

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/ingest-central#334]
Add a security.txt file to all repo.
This is as a way for people to communicate security issues to us.
`security.txt` contents:
```
If you'd like to report a security issue please contact us
Contact: security-leads@data.humancellatlas.org
```

**Comment by stahiri** [comment]
@justincc can you confirm that ingest has committed security.txt as described above? If this is not complete, can this be added in Q3? (I've removed the association with GA release)

**Comment by stahiri** [comment]
@justincc / @rdgoite / @MightyAx - any update on the status of this one?

**Comment by justincc** [comment]
Unfortunately this is being continuously overriden by priority items. Will likely not get done in Q3.

**Comment by MightyAx** [comment]
There's a [security.md](https://github.com/HumanCellAtlas/.github/blob/master/SECURITY.md) file that every repo in the HumanCellAtlas organisation automatically references, due to it's inclusion in the [HumanCellAtlas/.github](https://github.com/HumanCellAtlas/.github). 

That line is already present there.

**Comment by lauraclarke** [comment]
@MightyAx we don't have the security.txt at the root of each repo though such as 

https://github.com/HumanCellAtlas/skylab/blob/master/security.txt

**Comment by stahiri** [comment]
As discussed in the 9/25/19 DevSecOps meeting, all repos will reference security.md via the issues and security tabs. Repos may elect to additionally include a security.txt file and are responsible for ensuring that: (1) security.txt references the overarching HCA security.md, and (2) paths to security.md are kept up to date in the security.txt file.

Given this, I'm closing this ticket.
