### ISSUE TITLE
3rd party libraries in use are tracked and analyzed for security risk

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/ingest-central#337]
DevSecOps team needs to tell us what tools to use to do this.
Then we will update all the component team tickets with that information.

**Comment by stahiri** [comment]
Per #308, DevSecOps recommendation is for everyone to use the same tool. Both Snyk and SourceClear are good options here. Prior recommendation from the team is to start with Snyk since it's open source (SourceClear requires procurement).

**Comment by rdgoite** [comment]
I have recently integrated our Python code repositories with DCP Snyk setup.

**Comment by stahiri** [comment]
@rdgoite - based on your comment from April, I believe this ticket can be closed. Would you please confirm and update, if correct?

**Comment by rdgoite** [comment]
Yes, I've already set up all relevant Ingest repositories in the DCP-wide Snyk instance. I can see however that some of the other Ingest repositories that we don't really manage/maintain anymore added in there. Not sure if this is something we need to sort out in the scope of this ticket.

**Comment by stahiri** [comment]
Snyk has been implemented across the humancellatlas GitHub org
