### ISSUE TITLE
[USI] Include HCA Project UUID in BioStudies submission.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#344]
HCA project accession (BioStudies) - Currently, the HCA Project UUID is embedded in the "alias" field in the BioStudies submission. Other archives have dedicated HCA UUID fields (e.g. "HCA Biomaterial UUID" in BioSamples). We should be submitting an "HCA Project UUID" key:value to BioStudies to uniquely reference the HCA Project. The BioSamples "alias" field is not required by BioStudies.

**Acceptance criteria:**
- [x] Add "HCA Project UUID" field to USI submission and populate with the HCA project UUID.
- [x] Pass "HCA Project UUID" from USI to BioStudies and confirm it is available in the JSON.
- [ ] ~Don't pass "alias" field to BioStudies (not required).~

**Comment by malloryfreeberg** [comment]
@aaclan-ebi and @ke4 I have confirmed point 2 works!

Can you remind me whether it is required that USI pass the "alias" field to BioStudies?

**Comment by aaclan-ebi** [comment]
@malloryfreeberg yes, it is required in USI. We need the alias for the linking as well. When we create the study we link it to the project alias in that submission. I think in USI, this alias is being passed as BioStudies project alias. @ke4 is it possible to not use USI alias as the BioStudies alias?

**Comment by ke4** [comment]
@aaclan-ebi I checked the biostudies-agent's code and it gets the alias from the USI's Project entity and set it on the BioStudy entity. I am not sure if it is required by other projects or not. If not, then I can easily remove that part of the code.

**Comment by malloryfreeberg** [comment]
From Ugis' email last week:

> 1) You can include any attributes you think are useful - there is no need to have an attribute called 'alias'. I think it would be useful to keep an UUID attribute in BioStudies for traceability, and we can perhaps suppress the display of this for end users.

Since we have the HCA Project UUID, I think that should suffice for having a way to trace the Study. @ke4 can you please remove passing the "alias" to BioStudies? This is the last thing to do for this ticket!

**Comment by ke4** [comment]
@malloryfreeberg There is always a last one, and another one and another one ... :-D

**Comment by malloryfreeberg** [comment]
Decided to keep alias in for now.

**Comment by aaclan-ebi** [comment]
@malloryfreeberg would it be okay to close this and reopen or create a new one in the future? (Just not to clutter our In Progress pipeline in ZenHub)

**Comment by aaclan-ebi** [comment]
I'm moving it to Done for now.
