### ISSUE TITLE
[USI] Remove HCA wranglers and curators from contributors list in BioStudies.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#345]
In the current way that BioStudies displays the contributors submitted as part of the project from HCA, the HCA wranglers and external curators are listed last and thus appear as the senior PIs in the list of contributors on the BioStudies web page:

![Screen Shot 2019-03-12 at 10 09 06](https://user-images.githubusercontent.com/10993501/54192050-04159680-44af-11e9-81ce-b8ae8b5ea558.png)

The current display is misleading. Ideally, BioStudies could interpret the assigned roles of contributors and smartly show the list of contributors in an order that doesn't misrepresent who performed what role. 

As a first step to addressing the misleading display, we can remove contributors (HCA wranglers, external curators) who were not part of the actual project so that they aren't displayed in BioStudies. These contributors will still be represented in the HCA metadata.

**Acceptance criteria:**
- [x] Remove HCA Wranglers and external curators from list of authors submitted to BioStudies. Roles can be found in the `project_role` field in HCA metadata.

**Comment by malloryfreeberg** [comment]
From @aaclan-ebi 

> For BioStudies project contacts, is it safe if I exclude the contributor with project role Human Cell Atlas wrangler, or should I just search for wrangler keyword (which might not be safe as well) Hmm, this is not an enum field, right?

The field is an enum right now, but we are working on making it an ontology. You're right, though, it might be best to search for keywords as I'm not sure what term we will end up adding to the ontology. 

`project_role` ontology being tracked here: https://github.com/HumanCellAtlas/metadata-schema/issues/855

**Comment by aaclan-ebi** [comment]
This is now done. 

Please note that we only exclude the contact if it has a project role with `wrangler` keyword on it.

**Comment by malloryfreeberg** [comment]
@aaclan-ebi can you also exclude "curator"?

Here is the official [enum](https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/module/project/contact.json#L76) in the HCA metadata.

**Comment by aaclan-ebi** [comment]
Project contacts with project role "curator" are now being excluded too.

**Comment by malloryfreeberg** [comment]
@aaclan-ebi confirmed this looks good 👍 

Feel free to mark this as done :)

**Comment by aaclan-ebi** [comment]
Okie! Thanks!
