### ISSUE TITLE
Handle duplicate export messages

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#351]
Possible solution:	
1. Handle bundle export messages in an idempotent manner.
2. Do some deduplication

Things to think about for:
	- Check if we can have direct link between bundle and it's assay/analysis process ?
	- What if we really want to re-export?
	- Check if we could use redelivered flag in RabbitMQ

I tagged it `next` as I think this has a very high priority.

Occurences:
- Some duplicate analysis bundles in scale test  https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/339
 - Some duplicate assay bundles in TM dataset in prod (might be a different casuse but noting it here as it could be related) https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/343

**Comment by aaclan-ebi** [comment]
The team discussed the possible solutions for this issue:

1. Let Ingest core assign the bundle uuid and bundle version and send it as part of the exporter message. If there's a duplicated message and there's 2 export processes processing same bundle uuid + version, one will eventually succeed and the other one will fail.

Pros: Quick solution to prevent duplicate bundles 
Cons: The exporter instance will still try to export the duplicate message and will only fail at the end.

2: Generate the bundle manifest record in Core with bundle uuid + version and send it as part of the message. The exporter will use the bundle manifest to keep track if that bundle is already being processed.

Pros:
- Long term solution
- It will allow us to keep track of the error message and status of the export process in bundle manifest
- It will allow us to easily retry the export process

Cons: 
- Bundle Manifest needs redesign
- Consumers of Bundle Manifest resource needs to be notified with the changes (DCP Diag tool, Ingest UI etc)
- Needs more dev time and effort

**Comment by parthshahva** [comment]
@aaclan-ebi As part of this ticket, we should probably double check all prior production envelopes to determine if any were impacted?

**Comment by aaclan-ebi** [comment]
@parthshahva yeah good point. Since state tracker is tracking the index, a submission would never be set to Complete unless all expected bundles were created. I believe we're sure that we have all the expected bundles. 

We just need to verify with the wranglers if the expected no. of bundles for each dataset submissions is  the same as the no. of bundles created. If there are excess bundles, those must be duplicates and we have to remove those.

Hi @malloryfreeberg, Do you know who we can ask this info? I am not sure who to ask, but we can create a ticket for this if ever in the data wrangler repo? or metadata schema repo?

**Comment by parthshahva** [comment]
@aaclan-ebi Is there any potential for a case where 1 bundle export failed but 1 was duplicated leading to the correct # of bundles but incorrect results?

**Comment by aaclan-ebi** [comment]
@parthshahva Nope, we're tracking the index so that shouldn't happen. But it might happen that there's 2 bundles for the same assay process. No info should be lost but there might be redundancy unfortunately :-( If there is, we can identify and delete those.

**Comment by malloryfreeberg** [comment]
> We just need to verify with the wranglers if the expected no. of bundles for each dataset submissions is the same as the no. of bundles created. If there are excess bundles, those must be duplicates and we have to remove those.
> Do you know who we can ask this info? I am not sure who to ask, but we can create a ticket for this if ever in the data wrangler repo? or metadata schema repo?

@aaclan-ebi Row 6 of the CBeta spreadsheet has the expected number of bundles for the 16 datasets in the prod DS right now. But if you're asking how the expected number of bundles can be checked during the submission process, the answer is by getting the number of unique values in the  `process.process_core.process_id` fields in the Sequence file tab.

**Comment by aaclan-ebi** [comment]
Okie! Thanks @malloryfreeberg ! I double-checked the actual bundles in each submission and compared it with the expected bundles in the CBeta spreadsheet. Everything seems to match except for TM dataset which is still in progress. All prior production bundles should be fine. :-)

**Comment by aaclan-ebi** [comment]
Deployed to integration 22 Mar, https://github.com/HumanCellAtlas/ingest-kube-deployment/commit/5c229b1168661a6312d89e6da2356d28cc7f8558
