### ISSUE TITLE
[Ingest Integration test] Isolate data from primary submission to be used the secondary submission 

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#354]
This is to avoid doing another primary submission when running the analysis submission.

This is Tony's suggestion during the demo of this ticket: https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/307

Current Behaviour: When testing the secondary submission, a dataset spreadsheet is being uploaded. All metadata in that dataset is being added. Not all are required for analysis submisssion. (biomaterials, assay processes and other processes, protocols, project metadata are not needed)

New Behavior: We could just create the minimum set of test data necessary for analysis submission:
- submission envelope
- files
- bundle manifest

**Comment by rolando-ebi** [comment]
@aaclan-ebi I believe this is done
