### ISSUE TITLE
Decide how we're going to document everything going forward

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#359]
a) Google docs, b) wiki, c) markdown files in a github repo?

c) is what we should be doing but we need to discuss
  1) Whether this is suitable for all document types
  2) The migration plan for existing stuff which is practically all in google docs

What I don't want to see is some stuff in docs, some in wiki, some in git unless there is an agreed migration strategy.

**Comment by justincc** [comment]
Inspired by #343

**Comment by justincc** [comment]
Team decision is that SOPs will be documented in the [ingest-central wiki](https://github.com/HumanCellAtlas/ingest-central/wiki). Other documentation (e.g. design) will remain in Google Docs for now.

**Comment by malloryfreeberg** [comment]
@rdgoite @justincc it would probably be helpful to let the data portal content team know about this so they can point the portal to the appropriate content in the wiki to replace the static content that is there now :) Not a high priority, but just keep it in mind.
