### ISSUE TITLE
Reinstate mongo backup cronjobs in all environments

### ISSUE THREAD

**Issue by rolando-ebi** [HumanCellAtlas/ingest-central#362]
I noticed that our integration cluster is not running mongo backup cronjobs. We need to fix this and ensure it's happening across all environments

Acceptance criteria:
- Cronjobs to perform mongo backups are running in all environments

**Comment by justincc** [comment]
How critical would you say this is?

**Comment by rdgoite** [comment]
Backup procedures have all been set to run in all environments. I have updated the backup script in `ingest-kube-deployment` to run through Helm.
