### ISSUE TITLE
[SPIKE] Assess likely update performance to datastore with current bundling facilities

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#367]
We need to assess the likely performance of pushing updates to the datastore with our current bundling facilities. Assumptions:

1) 100K bundles (on a par with Tabula Muris)
2) Don't consider secondary analysis yet (this may change)
3) A single project description change. This is shallow but broad (affects all bundles)

How long do we think it will take with our current solution of doing a project file update then update every bundle version to reference that new file?

This information should be placed in [this section of the ingest updates design document](https://docs.google.com/document/d/1YkIqUgZStWC7mnQWHvefONWbUhAcHPDtV6rXExrWhSw/edit#heading=h.b3b8m3d44f26)

Also if applicable, please think if there are ways of how we could reduce this time without changing the APIs or behaviour of other components, and what we guess the reduction would be. Don't worry about actually measuring at this stage.

**Comment by lauraclarke** [comment]
@justincc quick check on

2. Don't consider secondary analysis yet (this may change)

I was under the assumption that ingest would be propagating input data changes into the analysis bundles at the same time as updating the input bundles, is that no longer the case?

**Comment by justincc** [comment]
Per discussion this morning, we will press on with doing the actual implementation and then reopen discussion with the datastore if the performance impact is too high (which I expect).

**Comment by justincc** [comment]
> @justincc quick check on
> 
>     1. Don't consider secondary analysis yet (this may change)
> 
> 
> I was under the assumption that ingest would be propagating input data changes into the analysis bundles at the same time as updating the input bundles, is that no longer the case?

That's still the case. That was an old comment by which I was trying to reduce the scope of this ticket.
