### ISSUE TITLE
Implement search backend so a wrangler can find the submission to update

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#375]
See [this section of the design doc](https://docs.google.com/document/d/1YkIqUgZStWC7mnQWHvefONWbUhAcHPDtV6rXExrWhSw/edit#heading=h.wy3yieeaglt0)

Acceptance criteria:

- An API in ingest-core that allows users to search MetadataDocuments given an arbitrary key and value and returns matching Submissions containing MetadataDocuments with the field/value pair

**Comment by justincc** [comment]
This is not the UI part

**Comment by justincc** [comment]
Please liaise with Mallory first to find out what we want. As with a lot of things, we want to try and keep this as simple as possible so we can finish updates and move on to other stuff.

**Comment by aaclan-ebi** [comment]
Had a quick chat before with Gabs about searching by projects and viewing submissions in a project. Might be good to consult her as well. :) I also kinda started this last week, changes here might be of use: https://github.com/HumanCellAtlas/ingest-core/tree/feature/query-projects

**Comment by justincc** [comment]
Yeah, we need acceptance criteria on this before we start working on it proper.

**Comment by prabh-t** [comment]
This seems quite straightforward to implement at first glance but since Mallory and Gabs not around today, I can't clarify what's needed exactly. I'll play around with the code anyway to familiarise myself.

**Comment by rolando-ebi** [comment]
UI requirements captured here: https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/440

**Comment by justincc** [comment]
When you've done the design please record in the HLD or LLD of https://drive.google.com/drive/folders/1QFSzIeJDPFCsL9jWdTwZmzLoxD4zDB_j as appropriate (or a fresh doc linked to the existing docs if you think that's better).
