### ISSUE TITLE
Address performance regression in lieu of ingest-core reliability changes

### ISSUE THREAD

**Issue by rolando-ebi** [HumanCellAtlas/ingest-central#386]
As part of work to make the ingest-core component reliable we must remove its internal message buffers in order to ensure that no messages are lost in the case of a failure. This means that critical life-cycle messages will be emitted in the same thread that handles HTTP requests to the core, adding to the response time of the core. To maintain old throughput levels, we should scale out the number of core instances as well as perform concurrent requests in clients to the core

Acceptance criteria:
- There are multiple(let's say 3) instances of the core
- The ingest-broker performs concurrent rather than sequential requests to the core. The concurrency rate should be tuneable

**Comment by justincc** [comment]
Follow on from #317

**Comment by justincc** [comment]
I'm increasingly of the opinion that state machines should be in core but that's a debate for another day.

**Comment by rolando-ebi** [comment]
Integration tests are passing with 3 instances of the stateless ingest-core. No performance regressions.

For the purpose of reliability, I tested a large submission while manually knocking out 2/3 of the ingest-core pods. Everything works as expected assuming clients of the ingest API have a reasonable retry policy for 5XX HTTP errors.

With a replicated core, we should ensure that ingest subcomponents (importer, validator, exporter) do retries on 5XX errors.
