### ISSUE TITLE
[Spike] Upgrade Spring Boot to latest supported version

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#393]
Ingest uses Spring Boot 1.5.6. [1.x is EOL on 2019-08-01](https://spring.io/blog/2018/07/30/spring-boot-1-x-eol-aug-1st-2019). We *must* update then, probably immediately in Q3.

This is a complex piece of work since there are many API changes. We need to consider these before we start.

Acceptance criteria:

- A documented process for a gradual upgrade to spring boot 2
- A branch of ingest-core that runs spring boot 2 and passes all dev tests

**Comment by prabh-t** [comment]
good news is that current spring boot v1.5.6 doesn't hardcode version dependence on spring-core and spring-context, and it has been working fine with v5.0.4 of those parent libs. Current GA release of spring boot is v2.1.6 and this obviously work with v5.1.8 of core dep, so not a big leap fro v5.0.4.
I can investigate further, try, test and report.

**Comment by rolando-ebi** [comment]
Suggested strategy:

- Continually merge master into a branch for this work
- Upgrade spring boot version in build.gradle
- while not compiling:
  - attempt to compile
  - perform dependency management as necessary to import required libs
  - perform code changes in lieu of library API changes
- while unit tests not passing:
  - perform code changes until test pass, possibly fix tests
- build image and deploy to dev
- launch the dev integration tests
- while dev integration tests not passing:
  - assess why and fix as necessary or open tickets against other components if necessary
- merge upgrade branch to master
