### ISSUE TITLE
Capture appropriate alerts and audit trails so we can handle detected attacks and understand the consequences of emergent threats and breaches

### ISSUE THREAD

**Issue by stahiri** [HumanCellAtlas/ingest-central#394]
As specified in the [Q2 Roadmap] (https://docs.google.com/spreadsheets/d/1iAL2JR3ndgMmYwojUU0kU8Pm7B7ycRLt_973seREd3M/edit#gid=1107068822&range=C10).

We need appropriate alerts and audit trails so we can learn about and appropriately handle detected attacks and understand the consequences of emergent threats and breaches. This includes being able to know when an attack is taking place and being able to see in the logs what the attack entailed (what attacker accessed, changed, etc.).

__Deliverable__:
Ensure each component captures audit logs for the following types of events (as appropriate):
• Server alerts and error messages
• User log-on and log-off (successful or unsuccessful)
• System administration activities
• Modification of privileges and access
• Modifications to the application
• Application alerts and error messages
• Configuration changes
• Account creation, modification, or deletion

**Comment by justincc** [comment]
Hi Sarah,

To address the points above:

* Server alerts and error messages: Logged by cloudwatch
* Logins/logouts: This is recorded in the hca auth0
* System administration: This is logged by Kubernetes
* Modification of privileges and access: UI and system admin users only have one level of access.
* Modifications to the application: Logged by Kubernetes
* Application alerts and error messages: Error messages are logged in Kibana
* Configurations changes: Logged by Kubernetes
* Account creation, modification or deletion: For the UI, by previous agreement, anybody in certain domains (ebi.ac.uk, broadinstitute.org, ...) can access the ingest UI. There is no concept of account modification or deletion.

Therefore, at this time we don't believe there is anything that ingest needs to do for this ticket.

**Comment by stahiri** [comment]
Thank you @justincc!
