### ISSUE TITLE
Authenticate all Ingest POST metadata entity endpoints

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#395]
Acceptance criteria:
We don't process JSON from any eternal source without authentication.

Design:
We think we will do this by attaching a header to all incoming requests in NGINX and then checking that header in core on incoming requests.

Alternative is to do JWT token authentication in the same manner as ingest-client. This would involve adding the necessary libraries and token management to the staging manager at least, and finding appropriate libraries and doing token management on the validator.

Older text

## User story
* As an API user
* I want POST requests to Ingest API be authenticated
* so that all requests to create entities in Ingest will be limited to authorised services and users 

## Definition of done
All POST endpoints should require a JWT token:

/submissionEnvelopes/files/*
/submissionEnvelopes/biomaterials/*
/submissionEnvelopes/protocols/*
/submissionEnvelopes/processes/*

/files/*
/biomaterials/*
/protocols/*
/processes/*

If token is invalid a 403 Unauthorised http response error will be returned.

**Comment by justincc** [comment]
Required to deal with a security issue that could only otherwise be handled by #393

**Comment by rdgoite** [comment]
The NGINX Ingress controller already attaches special headers to all HTTP requests that get forwarded to internal Kubernetes services. Using these header, I've updated the Core security configuration to filter requests that come through the Ingress controller.

The changes are now in dev, and I've confirmed that the security configuration works by sending the following analogous request using an ad-hoc pod in the dev cluster:

```
root@debian-curl:/# curl http://$INGEST_CORE_SERVICE_SERVICE_HOST:$INGEST_CORE_SERVICE_SERVICE_PORT/user/
{"timestamp":"2019-05-13T12:27:51.165+0000","status":404,"error":"Not Found","message":"Not Found","path":"/user/"}
```

```
root@debian-curl:/# curl https://api.ingest.dev.data.humancellatlas.org/user
{"timestamp":"2019-05-13T12:27:55.911+0000","status":401,"error":"Unauthorized","message":"Unauthorized","path":"/user"}
```
