### ISSUE TITLE
Provide interaction design to support ability to do updates

### ISSUE THREAD

**Issue by gabsie** [HumanCellAtlas/ingest-central#400]
Provide the step by step interactions for doing updates through the UI, following the steps in the user journey.

- Create based on necessary user steps
- Evaluate the low-fi prototype with wranglers.
- Discuss implementation with developers.

Definition of done: when the designs are with the frontend implementation team.

**Comment by justincc** [comment]
We need to complete this asap (definitely not later than this sprint) since it may affect our estimates, which the DCP needs asap.
