### ISSUE TITLE
Switch to new 10x integration test spreadsheet.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#401]
Old 10x integration test spreadsheet in schema repo: https://github.com/HumanCellAtlas/metadata-schema/blob/master/infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx

New Optimus 10x integration test spreadsheet in schema repo: https://github.com/HumanCellAtlas/metadata-schema/blob/master/infrastructure_testing_files/current/dcp_integration_test_metadata_1_optimus_10X_bundle.xlsx

With new Optimus pipeline running in the DCP, only the Optimus 10x spreadsheet is currently used by the DCP-wide integration test. Schema repo team would like to not have to maintain both the old and optimus 10x spreadsheets, and the old 10x is not relevant anymore. 

Please switch to the new spreadsheet so schema repo team can archive the old one.

**Comment by malloryfreeberg** [comment]
@justincc I'm not sure where this fits in with your team's overall priorities, but at the moment all environments are using the new Optimus integration test spreadsheet. I wonder whether it's important that the ingest dev environment switches to this spreadsheet sooner rather than later? To make sure that the ingest dev internal test is in sync with the DCP-wide one.

**Comment by justincc** [comment]
@alegria @rolando-ebi @rdgoite what do you think?

**Comment by aaclan-ebi** [comment]
Thanks for letting us know @malloryfreeberg !

@justincc , we don't have a test using that spreadsheet in our integration tests, so it's fine.

**Comment by malloryfreeberg** [comment]
Thanks @aaclan-ebi !
