### ISSUE TITLE
[UI] "Connection aborted" error when uploading spreadsheet

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#41]
**Give the bug a title**

[UI] "Connection aborted" error when uploading spreadsheet

**To Reproduce**

Steps to reproduce the behaviour:
1. Uploaded `test.xlsx` spreadsheet
1. Waited
1. Saw error

**Expected behaviour**

* I expected the spreadsheet to import.

**Actual behaviour**

* I saw the error message: `('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))` on the red banner at the top of the page.

**Impact**

I won't be able to upload any spreadsheets.

**Screenshots or Messages**

![screen shot 2018-06-06 at 11 32 59](https://user-images.githubusercontent.com/10993501/41033225-a9b154fc-697d-11e8-96ea-477670751960.png)

**Comment by danielvaughan** [comment]
This is likely to be a temporary error when the cluster was having issues

**Comment by malloryfreeberg** [comment]
Closing this issue as I haven't seen it again today.
