### ISSUE TITLE
Update submission is cleaned up as necessary after submission to the datastore has been done

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#412]
Acceptance criteria:
* The Update submission is cleaned up as necessary after submission to the datastore

Probable implementation:
Once all update bundles have been fully processed the upload area has been deleted.

**Comment by aaclan-ebi** [comment]
The attributes in messages being sent to notify the state tracker was kept so the current code works for update submissions. Marking this ticket done.
