### ISSUE TITLE
Add back support for piecemeal submission to allow large spreadsheets to be split

### ISSUE THREAD

**Issue by danielvaughan** [HumanCellAtlas/ingest-central#42]
**What problem does the suggested enhancement solve? Please describe.**

Excel is limited to 2 million cells but we have data that requires more than this. One way to fix this is to support multiple spreadsheets.

**What type of enhancement is this?**

Usability

**How will this enhancement benefit wrangers and/or end-users?**

Wranglers can ingest spreadsheets with more than 2 million cells

**How complex to implement do you estimate this enhancement will be? (High, Medium, Low)**
Medium

**How much benefit do you estimate this enhancement will provide? (High, Medium, Low)**
High

**How urgent is this and is there a specific date it needs to be done by? (High, Medium, Low)**
Medium

**Describe your preferred solution**

Support multiple spreadsheets

**Describe alternatives you've considered**

Look to see if there is a workaround to the 2 million cells limit.

**Additional context**

**Comment by lauraclarke** [comment]
This has a high urgency not medium. There is an active dataset which is blocked from submission due to this limit a solution is needed asap.

The alternatives are not just looking for a workaround. There is also the option to generate multiple spreadsheets but create the JSON outside the ingest infrastructure, compile the JSON into the equivalent of a single submission and submit programmatically

@hewgreen Who reported this? it would be good to get the full details here

**Comment by hewgreen** [comment]
@cjvillar and @willrockout will both have this issue.

**Comment by danielvaughan** [comment]
JIRA added https://www.ebi.ac.uk/panda/jira/browse/HCA-995

**Comment by danielvaughan** [comment]
Limits for excel: https://support.office.com/en-us/article/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3

Total number of rows and columns on a worksheet

1,048,576 rows by 16,384 columns

So approx 17 billion cells in theory

Noncontiguous cells that can be selected: 2,147,483,648 cells

**Comment by danielvaughan** [comment]
Google Sheets has a 2 million cell limit:
https://support.google.com/drive/answer/37603?hl=en

**Comment by danielvaughan** [comment]
My understanding of implementation
* Load first spreadsheet to the submission envelope
* If a second spreadsheet is uploaded ignore the project and append data from all the other tabs

**Comment by gabsie** [comment]
Hi, everyone  - as discussed this morning the implementation of extra spreadsheet, please find the design thoughts I have had on this before: 

At this page, at the bottom, you have "Add more samples" (in your design, you can call it "Add more metadata")
https://chanzuckerberg.invisionapp.com/share/XMDS231YF#/281752400_4-4-6-1_Experiment-Sample-review_B

Once they click on the button, it should expand to open up the interface for uploading another spreadsheet, like on the previous screen:

https://chanzuckerberg.invisionapp.com/share/XMDS231YF#/281752399_4-4-4-1_Experiment-Custom-template-B

Then on the next page with data - the new files expected from the spreadsheet should appear with status: "Expected"

Let me know if questions!

**Comment by aaclan-ebi** [comment]
Thanks @gabsie! We'll revisit those when we do the tasks for UI improvement.

The ability to link to existing metadata in ingest by UUID was deployed to production last 17th July.
