### ISSUE TITLE
Use Fusillade integration instead of Fusillade in Ingest Authentication

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#424]
Trent Smith recommended to use Fusillade integration instead of dev.
slack announcement: https://humancellatlas.slack.com/archives/GF9E3FSNR/p1558391453000300

Tasks needed on our end:
1. Update Ingest UI to replace the authorise url to be https://auth.integration.data.humancellatlas.org/
~2. Update Ingest Core - checking of `audience`in JWT token - redeploy with different env variable~
~3. Remove backwards compatibility code for Dan's Auth0 endpoint~
~4. (optional) coordinate with other teams to use different audience value for each env~
~e.g.~
~current audience values:~
~dev, integration, staging: https://dev.data.humancellatlas.org/~
~prod: https://data.humancellatlas.org/~

~new audience values:~
~dev : https://dev.data.humancellatlas.org/~
~integration: https://integration.data.humancellatlas.org/~
~staging: https://staging.data.humancellatlas.org/~
~prod: https://data.humancellatlas.org/~

**Comment by justincc** [comment]
How much work do you think it would be for points 1-3? If not much we can get that done quickly. Should point 4 be a different ticket when necessary?

**Comment by aaclan-ebi** [comment]
Yes, we could file 4 in a separate ticket. It is recommended by Andrey but wasn't feasible for Ingest that time. We could do it in Ingest now just by changing the environment values however I'm not sure if other boxes has the `audience` value configured in environment variables as well. So this might take a while. 

For 1-3, I think it's just a 3.

**Comment by aaclan-ebi** [comment]
pushed to staging https://github.com/HumanCellAtlas/ingest-kube-deployment/blob/master/staging/changelog.md#22-may-2019

pushed to prod today. https://github.com/HumanCellAtlas/ingest-kube-deployment/blob/production-release-2019-05-28/production/changelog.md#28-may-2019
