### ISSUE TITLE
Include schema and/or field name when showing errors

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#430]
**Please discuss with a member of the ingest development team before submitting a suggestion**

1. What problem does the suggested enhancement solve? Please describe.

It's difficult to test ingesting a spreadsheet when the importer fails and the errors are vague and don't point to either the schema or the field that caused the error. See below as an example:

![Screen Shot 2019-06-05 at 12 57 15](https://user-images.githubusercontent.com/10993501/58958721-74c10c00-879b-11e9-9026-9db9ffacd979.png)

In the above error, the field name `project.contributors.project_role` in the Project - Contributors tab should have been `project.contributors.project_role.text`.

2. What type of enhancement is this?

Performance, usability

3. How much benefit do you estimate this enhancement will provide? (High, Medium, Low)

High

4. Please describe a solution

Display the schema and/or field name where the error was encountered so that wranglers/contributors can easily find what needs to be updated in the spreadsheet.

**Comment by MightyAx** [comment]
As of ingest-client#47 we now display the location of error's that occur when parsing the spreadsheet into JSON.
