### ISSUE TITLE
[Validation] Ontology validation does not run in ingest.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#436]
**To Reproduce**

1. Upload a spreadsheet in the UI (this particular test was in staging). Spreadsheet has the wrong ontology term for the organ field (uses an NCBITaxon ontology when only UBERON terms are allowed)
1. View the metadata validation results 
1. See that the metadata is valid (submission ID: `5cff77dde0cbe5000844100c`)

**Expected behaviour**
    
I expect that the ontology validator catches when terms are used that don't follow the restriction of the ontology schema.

**Actual behaviour**

Ontology validation doesn't happen.

**Impact**

No ontology validation happens. Incorrect ontology terms could be assigned to metadata fields.

**Screenshots or Messages**
Incorrect spreadsheet:
![Screen Shot 2019-06-11 at 10 49 00](https://user-images.githubusercontent.com/10993501/59262137-90626180-8c36-11e9-9645-1abed8efb2e1.png)

Graph restriction for this field:
![Screen Shot 2019-06-11 at 10 49 38](https://user-images.githubusercontent.com/10993501/59262192-a5d78b80-8c36-11e9-8ad3-20acb5d938f5.png)

Metadata is valid:
![Screen Shot 2019-06-11 at 10 50 24](https://user-images.githubusercontent.com/10993501/59262246-c0aa0000-8c36-11e9-987f-f6ea137e9d20.png)
![Screen Shot 2019-06-11 at 10 52 53](https://user-images.githubusercontent.com/10993501/59262452-25655a80-8c37-11e9-98df-b9e896491612.png)

**Comment by daniwelter** [comment]
This definitely worked at some stage. I'd be interested to know why it doesn't work now? Was the js validator turned off in ingest and if so, why?
