### ISSUE TITLE
[UI] 400 BAD REQUEST

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#44]
**Give the bug a title**

[UI] 400 BAD REQUEST

**To Reproduce**

Steps to reproduce the behaviour:
1. Upload spreadsheet with metadata starting on row 5 instead of row 6.
1. See error

**Expected behaviour**
    
* I expected to see an error message saying that my metadata didn't start on row 6 as expected.

**Actual behaviour**

* I got e 404 BAD REQUEST error

**Impact**

* This error message makes it difficult for a user to know that they need to move their metadata to the correct row in the spreadsheet.

**Screenshots or Messages**

![screen shot 2018-06-06 at 17 57 00](https://user-images.githubusercontent.com/10993501/41053473-85deee14-69b3-11e8-97d3-535c7e9b523d.png)

**Comment by malloryfreeberg** [comment]
@cjvillar also sees this issue (#57) and he has double checked that all his metadata starts on row 6.

**Comment by cjvillar** [comment]
Thanks, I don't see the bad request error anymore.
