### ISSUE TITLE
Implement UI elements to search for submissions

### ISSUE THREAD

**Issue by rolando-ebi** [HumanCellAtlas/ingest-central#440]
Acceptance criteria:

- Widget(s) in the submission dashboard that allows users to search for submissions given information about a project or a protocol
- The keys to search on for projects: project_title, project_description, project_short_name
- The keys to search on for protocol: library_construction_method (ontology), (TBD)
- Real time search, don't have to press "Enter" or "Search" to begins displaying results

**Comment by aaclan-ebi** [comment]
cc @gabsie , @malloryfreeberg

**Comment by aaclan-ebi** [comment]
UI changes are merged to master and deployed in dev, need the core backend search to be deployed in dev.

**Comment by aaclan-ebi** [comment]
New search box in this page: https://ui.ingest.dev.data.humancellatlas.org/projects/list
Project details view will display table of submissions linked to it.
