### ISSUE TITLE
Integrate a simple inconsequential update into DCP-wide integration test

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#442]
This is for ingest's behavior only. Correct behavior of components (e.g. data browser) will be left for them to assert. This means we should not need to coordinate with them to any great extent, though we should still them that this is coming.

**Acceptance criteria**
* The DCP-wide tests incorporate an inconsequential metadata update.
* The DCP-wide tests incorporate assertions to check our update behavior is correct.
* The tests are not failing because of ingest issues (it is acceptable that they fail because of other component issues)

The first 2 could be met by a copy/paste out of the ingest-integration-tests.

**Comment by justincc** [comment]
We may need both:
* An inconsequential update, one that doesn't trigger analysis (e.g. a project name change)
* A consequential one, right now a metadata field update that would ordinarily trigger a workflow run. We'll need to find out from analysis what this would be.

**Comment by justincc** [comment]
Okay, let's restrict this to the inconsequential change (donor ID) update for now. Mint box are saying this will not trigger analysis. A consequential update, if indeed there is one, will be a subsequent ticket in a subsequent sprint.

As discussed, we just do our part (tack updates on to the end of the existing test and do our assertions). It's left to downstream components to do their own checks when they are ready. I don't think we need to co-ordinate this upfront.

However, if this isn't ready by the end of Thursday to put in place, let's delay adding it until Monday.

**Comment by rdgoite** [comment]
The metadata update test has been merged to the DCP integration test repository and [has been confirmed to be working](https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/dcp/pipelines/14021).

**Comment by justincc** [comment]
Excellent, excellent.
