### ISSUE TITLE
Submission is stuck in SUBMITTED and no bundles were exported

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#445]

**Comment by aaclan-ebi** [comment]
There's a discussion about this before. And a ticket may have been filed already but I couldn't find so I created a new one. The following options were considered but have not been decided.

Options:
1. Create a new state to indicate that the submission envelope is ready to be submitted.
2. Make all entities inside submission to be in Pending til all entities are added and linked.
3. Check submission manifest actual and expected links. But not all submission may contain submission manifest
 https://github.com/HumanCellAtlas/ingest-core/compare/fix/incomplete-linking?expand=1

**Comment by justincc** [comment]
Dupe is #212
