### ISSUE TITLE
Create a separate entity for submissionErrors

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#447]
There are optimistic locking issues at the moment are many exporter jobs trying to POST submission errors. To prevent this, it would be nice to create a separate entity/collection for the submissionErrors instead of it being a field in the submission envelopes 

Acceptance criteria:
- Provide a POST endpoint to create and link submission errors to submission envelopes
- Provide ability to GET the submissions errors in an envelope
- Components (i.e. exporter, importer, UI) must be able to POST and GET the submission errors

Stretch goal:  Revisit the design submissionErrors field, consider adding timestamp

**Comment by justincc** [comment]
Special case assignment to @MightyAx as a learning exercise so assigned during the sprint and no estimate currently.

**Comment by justincc** [comment]
@aaclan-ebi is the first point of contact when you need help though of course you can talk to anybody.

**Comment by MightyAx** [comment]
- [x] Ingest-Core changes
- [ ] Ingest-Client changes
- [ ] Ingest-UI changes
