### ISSUE TITLE
Restore auth on token PUT/PATCH/POST requests

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#452]
We rolled this back temporarily because analysis are not doing it. We need to roll this forward again asap.

**Comment by justincc** [comment]
Analysis ticket https://github.com/HumanCellAtlas/secondary-analysis/issues/629

**Comment by justincc** [comment]
[Rex's PR for the necessary analysis-side work](https://github.com/HumanCellAtlas/pipeline-tools/pull/154/)

**Comment by justincc** [comment]
[Sounds like mint box are ready](https://humancellatlas.slack.com/archives/C75G0R97E/p1562174941042800?thread_ts=1562073433.034700&cid=C75G0R97E). We just need to wait for them to promote their fix up to integration before doing the same ourselves.

**Comment by aaclan-ebi** [comment]
This was deployed back to dev and integration today. Verify if DCP integration test is passing.
