### ISSUE TITLE
Document `links.json`

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#458]
We need to document the `links.json` since it has users, certainly the matrix service and probably the analysis service.

**Comment by justincc** [comment]
See #453 for a new project uuid field.

**Comment by justincc** [comment]
@maniarathi where would be the best place for this?

**Comment by maniarathi** [comment]
Great question! This one was a little tricky for me to parse through and I have one question first: how does the interaction normally happen? Is it simply that users receive `links.json` via some API call or something else?

As a starting point, I think documenting it in https://github.com/HumanCellAtlas/ingest-central/wiki might be a good start with a link in the README pointing towards it (so that it is visible from the landing page).

**Comment by justincc** [comment]
The `links.json` is in every bundle. It contains the edges of the experimental graph for that bundle.

The problem with describing this in ingest-central is that this isn't an ingest item - it's a data model/API item. Ingest just happens to be the component that generates it. This might circle back to the fact that we have no formal data model (and hence no formal description of it). I was hoping we could come up with some 'neutral' place for this documentation, such as the DCP wiki. Perhaps this is something to discuss in next tech-arch?

**Comment by justincc** [comment]
This sliver of Google doc [the nearest thing we may have to a description](https://docs.google.com/document/d/15bSO0sgo5KRWJIr6VUgZf97uL8397vUZ68AL17EC_cA/edit#heading=h.8wckwxen3raj), which is no description at all.

**Comment by diekhans** [comment]
A description of links.json needs to be part of the data model RFC:
https://docs.google.com/document/d/1CdIJ_pBdiiQUFh8kYARRhMXvhKXGERG3bdv763tpAKI/edit#heading=h.9clqgpl47dsx 

Right now, how to navigate  the experimental graph in the face of multiple versions of entity instances is complex. It requires integrating implicit linking based on what bundle contains the instances.  This needs to be rigorously defined.

**Comment by justincc** [comment]
1) We find a place to stick documentation on things like `links.json` that makes sense (not a Google doc).
2) I will write something about the current `links.json` based on my own understanding.
3) Then people can correct it.

**Comment by justincc** [comment]
https://github.com/HumanCellAtlas/dcp/wiki/links.json
