### ISSUE TITLE
Supplementary files shouldn't be added as analysis process inputs

### ISSUE THREAD

**Issue by rolando-ebi** [HumanCellAtlas/ingest-central#462]
In the Process.addInputBundle() convenience endpoint provided by ingest, we assume that all data files in the primary bundle are sequence-file inputs to the analysis process. Schema awareness would be required to discern supplementary files from sequence files in this assumption.

We should remove this endpoint and make input file linking an explicit operation in our API. I've spoke to greenbox about this and they already have the information required to create these links. This also adds more visibility to API users as to what their API calls do.]

Acceptance criteria:
- remove the addInputBundle() method
- notify greenbox about this breaking change in advance
- Fix ingest integration tests that depend on this deprecated functionality

**Comment by aaclan-ebi** [comment]
@rolando-ebi , I was reading this convo on slack https://humancellatlas.slack.com/archives/C49TW3RV5/p1562854399154900
and it looks like that  the greenbox might treat some entities (like input biomaterial) as input to analysis process. This would break our logic for analysis processes in Ingest ( file -> process -> file ).

**Comment by lauraclarke** [comment]
@aaclan-ebi it would be good to confirm if that is the case, as that means they are using a different setup to the assumptions in ingest and we should confirm why they are doing that and if they need to or if we need to change our assumptions
