### ISSUE TITLE
[spike] Verify if user can upload new submission for an existing project

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#468]
Such a submission can reference existing metadata entities by UUID as long as the submission will only create new bundles and won't add information to any existing bundles (currently that no file metadata is added that links to an existing entity).

In theory this feature is already in ingest but it never got used and isn't being automatically tested. So there's an odds on chance it has been broken.

Tasks:
[ ] Verify this is functioning
[ ] Add automated tests for this if sufficient tests don't exist already
[ ] Coordinate with wranglers to test this

**Comment by mshadbolt** [comment]
FYI I am currently attempting this in this data-wrangling repo ticket :
https://github.com/HumanCellAtlas/hca-data-wrangling/issues/267

**Comment by mshadbolt** [comment]
@justincc here is the info we discussed me sharing with you:
The project page in the staging ui https://ui.ingest.staging.data.humancellatlas.org/projects/detail/5cdbe24064198100078915ae

An example spreadsheet where I populated the uuids by querying the ingest API
[ms-Meyer-lung-scrna-cs-from-new-donors-blank-enrichment.xlsx](https://github.com/HumanCellAtlas/ingest-central/files/3550269/ms-Meyer-lung-scrna-cs-from-new-donors-blank-enrichment.xlsx)

You can also use the 'download spreadsheet' button for each submission in the ui but it might be difficult to tell which uuids the system populated vs what I populated

**Comment by aaclan-ebi** [comment]
Hi @mshadbolt , the submissions described in the ticket https://github.com/HumanCellAtlas/hca-data-wrangling/issues/267  failed because of the issue https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/482. The fix for the exporter should be in staging today and in prod by tomorrow. You could retry testing this functionality again.

**Comment by aaclan-ebi** [comment]
Successful submissions: 
https://ui.ingest.staging.data.humancellatlas.org/projects/detail?uuid=f7dc2bae-c186-46b2-9d30-24f0046f9073

Failed submissions: 
https://ui.ingest.staging.data.humancellatlas.org/projects/detail?uuid=8b01ff5a-2157-4c4a-96bb-2c686a7ef8b0

https://ui.ingest.staging.data.humancellatlas.org/submissions/detail/5d6d297fb73e8700073707b7/overview

Findings: If we try to add a new bundle and reference an existing file submitted from way ago which don’t have the fields schema_major_version, schema_minor_version, we’ll get the file_already_exist error from DSS.

**Comment by mshadbolt** [comment]
@aaclan-ebi I received an email from the contributor yesterday who is very keen to see all the data as a whole submitted and publicly available in the DCP. Do you have an idea of when we would be able to get this working?

**Comment by justincc** [comment]
I'm afraid we can't say until we have a nominated solution. There are also over AUDR problems we're uncovering that might insert an additional delay.

**Comment by lauraclarke** [comment]
@justincc Can you give us a ballpark estimate, is this something which will hopefully be addressed in the next sprint or is it likely to take longer, it would be good to be able to do some expectation management

**Comment by justincc** [comment]
The only thing I can say is that at this stage I feel it will be more than a sprint for adding. Can't give more detail until we've finished investigating.

**Comment by justincc** [comment]
We have now determined that this isn't working. Closing in favour of #536
