### ISSUE TITLE
Investigate issues when retrying validation

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#470]
Retrying validation might be incorrectly setting still invalid files to valid. See https://humancellatlas.slack.com/archives/C6YTC4NJW/p1563487015031600

**Acceptance criteria**
Retrying a validation will never set an invalid file to valid.

**Comment by aaclan-ebi** [comment]
Investigation to verify if there are invalid files in production: https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/upload-service/394
