### ISSUE TITLE
Prevent race condition when staging files for export

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#482]
Right now, every time the exporter wants to create a bundle it immediately creates the files and then the bundle in the datastore. It may be more reliable and efficient to analyze all bundles then create all the files for them then all the bundles.

See also [this slack conversation](https://humancellatlas.slack.com/archives/C6YTC4NJW/p1564157365036300?thread_ts=1564155747.030500&cid=C6YTC4NJW)

**Acceptance criteria**
* The majority of the ingest team are happy with the design of this solution before it's implemented.
* We are reasonably confident that this change has not made reliability worse.
* All the datasets which failed to import can now be processed without triggering this race condition.

At this point we will pursue the approach of keeping a lock on our staging file requests to the upload service. If this takes longer than the estimated time, particularly to account for failure scenarios then we need to rethink the approach.

**Comment by rdgoite** [comment]
Looks like this is more urgent than originally thought. The current exporter implementation has been causing a problem with some of the recent submission attempts (#499, #502). Wrangler team have communicated that some of the datasets they're currently processing are on tight schedules.

**Comment by parthshahva** [comment]
As part of this redesign, put file to upload area should be de-duplicated. Ie if a metadata file is shared across multiple bundles, it should ideally be put to the upload area and DSS only once and then the file UUID should be shared across bundle manifests.

**Comment by justincc** [comment]
[This script](https://humancellatlas.slack.com/archives/C6YTC4NJW/p1565362159108800) was created by @parth to fix the upload tags issue.

**Comment by justincc** [comment]
The implementation approach in this ticket may mean either that a) all export has to flow through a single instance or b) there needs to be a backend persistence layer to coordinate multiple exporters. We will have more discussion on this.

**Comment by justincc** [comment]
[Exporter redesign work](https://docs.google.com/document/d/1m8OM56Xfk9pu6O28nOEkO9N2px0sgdVqRZcSticyY98)

**Comment by Parth** [comment]
~@parth~ @parthshahva

**Comment by rdgoite** [comment]
As a side effect of this change, we will also need to make modifications to update metadata part of the exporter code. They are currently using almost divergent code that needs some merging.

**Comment by rdgoite** [comment]
Test [submission of Kidney dataset](https://ui.ingest.dev.data.humancellatlas.org/submissions/detail/5d67e9fde7d256000830d9cd/overview)(thanks @ESapenaVentura) in dev went through with no problems.
