### ISSUE TITLE
Refresh the token before doing a PUT /bundle in the exporter

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#485]
Fusillade tokens are expiring before export has completed.

Since there is no way for us to provide the token in DSS client  atm,  the quick solution may have to require us to create a new instance of the HCA DSS client every time we send request to the DS. 

Currently there is no way for us to manage and refresh the tokens on our own. The token is being generated only upon the instantiation of the DSS client. Enhancement ticket was filed before in DSS repo. https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-store/2216

**Comment by aaclan-ebi** [comment]
Affected data set: https://humancellatlas.slack.com/archives/C6YTC4NJW/p1564389830050900

**Comment by justincc** [comment]
Creating a DSS client for every datastore request sounds like an extreme solution. In the PR for this ticket I see you cached the token instead?

**Comment by aaclan-ebi** [comment]
yeah, as a workaround, it'll be instantiated every 50min (1hour with refresh period 10min)

**Comment by aaclan-ebi** [comment]
Aug 1 - fix released to staging https://github.com/HumanCellAtlas/ingest-kube-deployment/blob/master/staging/changelog.md#30-july-2019
