### ISSUE TITLE
Re-Export Tabula Muris.

### ISSUE THREAD

**Issue by cjvillar** [HumanCellAtlas/ingest-central#488]
Tabula Muris Re-Export

Bundles failed to be made.

Ingested Tabula Muris (uuid 14df1f92-155c-4da2-97fc-85601dee64da) UI said submitted but bundling failed. I don't know why. I wrangled the data, submitted files, followed protocol.

To see 0 bundles use: `analyze-submission -d prod 14df1f92155c4da297fc85601dee64da`

**Comment by justincc** [comment]
It sounds like the uploader encountered a race condition and we will need to re-export some bundles again https://humancellatlas.slack.com/archives/C6YTC4NJW/p1564694593071800?thread_ts=1564155747.030500&cid=C6YTC4NJW

**Comment by cjvillar** [comment]
Looks like the TM export is stalled out? Not sure but I have 99,821 "bundles" showing in the UI I think I need 998840 (199680 SS@ files /2)

**Comment by rolando-ebi** [comment]
@parthshahva we're seeing similar errors when attempting to re-export the missing bundles. These files might have to be deleted in the upload-db/s3. Will collate a list.

**Comment by rolando-ebi** [comment]
@parthshahva these are the files to be deleted:

```
/v1/area/14df1f92-155c-4da2-97fc-85601dee64da/process_2e2399bd-f058-46ee-a97f-0f4b3e23f989.json
/v1/area/14df1f92-155c-4da2-97fc-85601dee64da/process_5a2d6559-5c2f-4b59-b502-f297595b06ff.json
/v1/area/14df1f92-155c-4da2-97fc-85601dee64da/process_812c94b7-834f-4431-957c-88791aa75dec.json
```

**Comment by parthshahva** [comment]
@rolando-ebi the files should be fixed. could you retry?

**Comment by rolando-ebi** [comment]
Cheers @parthshahva. @cjvillar TM submission complete :+1:

**Comment by cjvillar** [comment]
Nice! Thanks All! Should I consider this ticket closed then?

**Comment by cjvillar** [comment]
@parthshahva I noticed in  https://tracker.data.humancellatlas.org/ GCP has on more bundle than AWS. just FYI

**Comment by parthshahva** [comment]
@cjvillar Ah good catch. I think a ticket needs to be created in data-store for that one missing aws bundle and in azul for all those missing bundles. It might be worth holding off on the azul ticket until the data store issue is resolved (otherwise azul will have to re-index a 3rd time to grab the missing bundle)

**Comment by parthshahva** [comment]
You can use the shareable link https://tracker.data.humancellatlas.org/?projectUUID=e0009214-c0a0-4a7b-96e2-d6a83e966ce0 now in the tickets if you want to quickly link to the issue

**Comment by cjvillar** [comment]
awesome, thanks parth

**Comment by claymfischer** [comment]
Wonderful, thanks all!

**Comment by cjvillar** [comment]
data-store #2328 https://github.com/HumanCellAtlas/data-store/issues/2328

**Comment by cjvillar** [comment]
TM progress now in the hands of Azul: https://github.com/DataBiosphere/azul/issues/1212 (thanks, Parth).

**Comment by cjvillar** [comment]
Looks like we're in Secondary analysis territory. Does anyone know if they can analyze mouse SS2?

**Comment by parthshahva** [comment]
@cjvillar Yea I think @rexwangcc was waiting for this project to complete in order to kick off the workflows

**Comment by rexwangcc** [comment]
Parth, thanks for tagging me here! 

Based on my understanding, on our side, the mouse SS2 pipeline and the infrastructure for running it are developed. I'm not sure if the analysis pipeline itself has passed the scientific validation yet, @kbergin could confirm.

We have created an [example result bundle](https://humancellatlas.slack.com/archives/C6C5S6B5W/p1565191611103700) for matrix and downstream services to test with. But the subscription for ss2 bundles is not turned on, so it won't kick off any workflows automatically at this time: https://github.com/HumanCellAtlas/lira/blob/master/subscription/elasticsearch_queries/prod-test-data/smartseq2-test-data.json

**Comment by kbergin** [comment]
Hi all - the SS2 Mouse validation is nearly complete, we will notify everyone when we release the pipeline officially and turn it on in all environments. We would additionally wait to put it into production to hear that the matrix service has been able to work with the data.

**Comment by rolando-ebi** [comment]
@cjvillar @kbergin since this ticket was about re-exporting TM, can we mark it done?

**Comment by cjvillar** [comment]
Thanks, @rolando-ebi. closing.
