### ISSUE TITLE
Retry failed bundle for imaging dataset

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#491]
There was a problem with expiring token in the exporter. Issue [485](https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/485)

Affected submission:
Submission ID: 5d3036765f9ee90008d3e7cc
submission UUID:     4c0d9412-36d3-4b11-8e68-059e286f5122 Supposed to get 1 bundle with 2757 files.

Reported by @zperova https://humancellatlas.slack.com/archives/C6YTC4NJW/p1564390412054600

**Comment by aaclan-ebi** [comment]
Need to retry the failed bundle.

**Comment by justincc** [comment]
This is a submission in staging?

**Comment by aaclan-ebi** [comment]
@justincc , yes. I'm trying to find the failed message in the logs now. We're not tracking the failed message atm. This is not good if we lose the logs.

**Comment by aaclan-ebi** [comment]
I couldn't find it anymore :( i may have to recreate the message, it's good there's only one bundle. But this is a problem if we have to find failed bundles for other larger datasets.

**Comment by justincc** [comment]
Yes. How could we better record failed operations?

**Comment by aaclan-ebi** [comment]
manually regenerated the ff message to be retried:
```
{
	"bundleUuid": "7a8123db-6ba7-43a6-9b96-e26f99b77601",
	"versionTimestamp": "2019-08-02T165239.001040Z",
	"messageProtocol": null,
	"documentId": "5d3036985f9ee90008d3f29c",
	"documentUuid": "cf0ccf9a-b094-4be9-8942-a495260dd3e0",
	"callbackLink": "/processes/5d25079f88fa640008b4f162",
	"documentType": "Process",
	"envelopeId": "5d3036765f9ee90008d3e7cc",
	"envelopeUuid": "4c0d9412-36d3-4b11-8e68-059e286f5122",
	"index": 1,
	"total": 1
}
```

**Comment by aaclan-ebi** [comment]
@zperova this is currently ongoing.

**Comment by aaclan-ebi** [comment]
@zperova the expiring token issue in Ingest was fixed however it looks like the bundle couldn't be created in DS. We're getting HTTP 500 errors. I filed this [ticket](https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-store/2320) in DS.

**Comment by aaclan-ebi** [comment]
Hi @zperova , Brian H. from DSS manually created the bundle, https://dss.staging.data.humancellatlas.org/v1/bundles/7a8123db-6ba7-43a6-9b96-e26f99b77601?version=2019-08-02T165239.001000Z&replica=aws

There might be issues when creating bundles with too many files. I'm confirming with Brian H. what the current limit is so that we could implement their suggestion.

**Comment by aaclan-ebi** [comment]
I'm moving this to done as the said bundle has already been created. Although, I can foresee encountering near future issues when creating bundles with too many files. I filed a new ticket to be prioritised to track the effort for that.

**Comment by zperova** [comment]
@aaclan-ebi I still can not see the bundle in the Ingest API and the status is 'Processing'.

**Comment by justincc** [comment]
Can you retrieve it from the datastore? Alegria is on holiday but I can imagine because this was created directly by the datastore it's not reflected in our database.

**Comment by zperova** [comment]
@justincc shouldn't that be fixed for the dataset to turn to complete and go to the tracker and Data Browser? The status is currently "Processing".

**Comment by justincc** [comment]
I'm guessing that the dataset copmleted and this was a fix afterwards. Is it possible for you to check the datastore? If you can't or the data is not there we'll certainly take a look, though someone else will need to pick up this ticket since Alegria is on holiday for another week.

**Comment by zperova** [comment]
@justincc 
when I use dcp-diag tool the result that I get is that there are no bundles in the DSS: 

`PHASE 2: Checking bundles are present in DSS:
	Checking for bundle manifests:...done.
	0 bundle are present in AWS
	0 bundle are present in GCP
	Saving state in 5d3036765f9ee90008d3e7cc.json...done.`

I asked about the Complete status because I can not see it in the Data Browser or the Data tracker.

However if I use Swagger API I do see this bundle. 

I will ask @xbrianh about this. However I still think wonder, why the ingest envelope is not complete, if the bundle is there.

**Comment by justincc** [comment]
I expect all the other bundles went through but because this one needed manual remediation, the envelope never set itself to complete. Once the bundle is in the datastore the notification goes out immediately - it doesn't rely on ingest further changing its own status.

I presume other bundles from that dataset are present?

Yes, please ask @xbrianh.

**Comment by zperova** [comment]
@justincc there is only one bundle in this dataset.
I will make a ticket in DSS for @xbrianh

**Comment by xbrianh** [comment]
@aaclan-ebi Can you remind me of the context of bundle `7a8123db-6ba7-43a6-9b96-e26f99b77601`? I don't recall creating any bundles in staging. But there are other things I don't recall :)

@zperova The bundle should appear in `dcp-diag` results. There was an issue in the DSS preventing discoverability. This has been addressed.

**Comment by justincc** [comment]
Hi @xbrianh. @aaclan-ebi is on holiday until Friday but I think this was in the context of ingest failing to create a large bundle in a single request.

**Comment by justincc** [comment]
Ingest ticket for solution implementation (unscheduled pending capacity and confirmation that the mechanism doesn't need reconsideration) is #503

**Comment by aaclan-ebi** [comment]
@zperova, Since the bundle wasn't retried from Ingest and bundle was created manually, the submission wasn't automatically set to completed. I've tried to manually create a bundle manifest and trigger complete event in Ingest. Please note, I've only added only the bundleUuid and version for now. The files mapping in this bundle isn't tracked. It would require more effort (i.e. a custom script to get all the file uuids in the bundle) to specify the files mapping. I don't see the strong need for now since this bundle is in staging. If you are going to test the "simple updates"  feature then that "files mapping" info in the bundle manifest is necessary. Please let me know if it is.

The submission is now set to Complete.
https://ui.ingest.staging.data.humancellatlas.org/submissions/detail/5d3036765f9ee90008d3e7cc/overview

The bundle not appearing in the `dcp-diag` result is a separate issue and is now resolved according to Brian H. @zperova could you confirm this?
