### ISSUE TITLE
Update version of NGINX used as Ingress controller

### ISSUE THREAD

**Issue by rdgoite** [HumanCellAtlas/ingest-central#492]
The security team has determined that [the NGINX version used as Ingress controller has security issues](https://humancellatlas.slack.com/archives/GBCT6QECF/p1564063446022500) particularly in its HTTP/2 implementation. This needs to be updated to version `>1.15.5`.

Alternatively, in case simply updating to a newer version does not work, we can choose to disable HTTP/2 support, or switch to a different server.

**Comment by justincc** [comment]
Dupe of #481
