### ISSUE TITLE
Document how to reference existing metadata entities in a new spreadsheet submission

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#494]
Look to do this in readthedocs.org 

**Acceptance criteria**
There are instructions on how to reference existing metadata entities in a new spreadsheet submission.
These instructions have been manually tested.
Wranglers are happy with the instructions.

**Comment by aaclan-ebi** [comment]
Guide: https://github.com/HumanCellAtlas/ingest-central/wiki/How-To-Upload-A-New-Submission-For-An-Existing-Project

**Comment by justincc** [comment]
Documented but this won't work right now as the underlying mechanisms don't work properly. Closing in favour of #536
