### ISSUE TITLE
Document the simple updates process from the wrangler's POV

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#498]
**Acceptance criteria**
* The simple updates process is documented such that we believe a wrangler could follow it.
* The documentation is in a publicly available place.
* [Optional if a wrangler is ready to try and update]. Give the documentation to them and see if they can follow it sitting by them. If not, improve it where necessary.

Rolando is create a readthedocs for the ingest API doc. Either this could be in there or in the ingest wiki, even if that is temporary.

**Comment by rdgoite** [comment]
Here's the initial [set of instructions](https://github.com/HumanCellAtlas/ingest-central/wiki/Updating-Metadata-through-Spreadsheets). It's currently hosted in our Github wiki, but it should be easy to transfer anywhere want.

**Comment by justincc** [comment]
Great. Are the wranglers aware?

**Comment by justincc** [comment]
I added a note at the top to tell them what they need to do if they want to make an update on an update.
