### ISSUE TITLE
[UI] Boolean error when uploading spreadsheet for submission

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/ingest-central#500]
**Give the bug a title**

Please give the bug a title that includes the *feature name* followed by a short description (*title*).

* [Login] Not able to login with my account
* [Validation] Validation failed for a file that should be valid
* [UI] Spelling mistake in upload instructions

**To Reproduce**

Upload a submission that contains a value that is converted to boolean with an extra space at the end (e.g., `yes ` or `no `) on the `project`-related properties. An example of a boolean project property is `project.contributors.corresponding_contributor`.

After doing this, no metadata will be loaded from the project and it will just throw the error "no" (Or "yes", I haven't tried both variants)

**Expected behaviour**

I expected for the metadata of the project to load, and throw a more specific error somewhere.

**Actual behaviour**

The metadata for the project doesn't load at all.

**Impact**

Once the source of the error is clear, it has an easy solution, but other wranglers (and, in the future, users) need, at least, a clearer error to detect the source.

**Screenshots or Messages**

![IMG_20190808_203719](https://user-images.githubusercontent.com/38617863/62767447-95079280-ba8c-11e9-858b-afd730fc8e57.jpg)

**Comment by rdgoite** [comment]
This error was due to a very rigid check on boolean values supplied in the spreadsheet. The system wasn't programmed to accommodate for trailing spaces/blank characters, and so the input with `no ` (note the space after) caused an unexpected error.

Here's the generated log in the broker for this incident:

```
Traceback (most recent call last):
  File "/app/src/hca-ingest/ingest/importer/importer.py", line 54, in import_file
    spreadsheet_json, template_mgr = self._generate_spreadsheet_json(file_path, project_uuid)
  File "/app/src/hca-ingest/ingest/importer/importer.py", line 45, in _generate_spreadsheet_json
    spreadsheet_json = workbook_importer.do_import(ingest_workbook, project_uuid)
  File "/app/src/hca-ingest/ingest/importer/importer.py", line 204, in do_import
    metadata_entities = self.worksheet_importer.do_import(worksheet)
  File "/app/src/hca-ingest/ingest/importer/importer.py", line 238, in do_import
    metadata = row_template.do_import(row)
  File "/app/src/hca-ingest/ingest/importer/conversion/template_manager.py", line 174, in do_import
    conversion.apply(metadata, cell.value)
  File "/app/src/hca-ingest/ingest/importer/conversion/conversion_strategy.py", line 38, in apply
    content = self.converter.convert(cell_data)
  File "/app/src/hca-ingest/ingest/importer/conversion/data_converter.py", line 70, in convert
    raise InvalidBooleanValue(data)
ingest.importer.conversion.exceptions.InvalidBooleanValue: no
[ingestapi.py:352 -        create_entity() ] 2019-08-08 19:34:38,027 - ingest.api.ingestapi - DEBUG - POST http://172.20.105.197/submissionEnvelopes/5d4c794c3f2def0008be7d18/submissionErrors {"errorCode": "ingest.importer.error", "errorType": "Error", "message": "An error during submission occurred.", "details": "no "}
```

**Comment by MightyAx** [comment]
This error should be resolved by the new parsing error reporting feature.
ingest-client#47
