### ISSUE TITLE
Create an onboarding doc

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#501]
**Acceptance criteria**
We have an ingest-specific on-boarding doc.

This doesn't need to be super-detailed - we can iterate. But it should incorporate Parth's recent instructions for adding a developer to DCP AWS.

We have a general onboarding doc at https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/home

Part of #322

**Comment by justincc** [comment]
[Doc](https://docs.google.com/document/d/1shmM9Wfy6twVeWftRxpLrujtNojC07m-ky5n-M3jKac/edit?ts=5d679cb4#heading=h.uhpz5vrgih5j). We want to convert this to markdown and link in the ingest-central wiki.

**Comment by rolando-ebi** [comment]
[onboarding doc in ingest-central.wiki](https://github.com/HumanCellAtlas/ingest-central/wiki/Onboarding)

**Comment by justincc** [comment]
Part of #332
