### ISSUE TITLE
No bundles generated for Benjamin Stewarts' dataset

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/ingest-central#502]
**HIGH PRIORITY**

For the Kidney cell atlas (Benjamin Stewarts dataset), No bundles ever got to see the sunlight:

- __Submission UUID__: 40972c5f-295a-4e39-9ac8-a1aaca89798f
- __When__: 09/08/2019
- __Ticket in Wrangling repo__: [Here](https://github.com/HumanCellAtlas/hca-data-wrangling/issues/141)

It seems that the issue traces to upload, as in the mouse gastrulation atlas submission. Rodrey and I are working on this, but nothing can be done until it is a reasonable hour for the upload team to be awaken.

**Comment by parthshahva** [comment]
All the files are fixed. Ingest developer needs to re-kick

As a general note, this is likely to keep happening for every single dataset until the exporter redesign is completed.

**Comment by ESapenaVentura** [comment]
Thanks @parthshahva!

**Comment by aaclan-ebi** [comment]
Retrying from this submission: https://ui.ingest.data.humancellatlas.org/submissions/detail/5d5082c01a249400085abd87/overview

47 failed bundles to retry
[https://app.zenhub.com/files/132741306/938a039d-52b4-426e-b66d-36afa5a2da13/download](https://app.zenhub.com/files/132741306/938a039d-52b4-426e-b66d-36afa5a2da13/download)

**Comment by aaclan-ebi** [comment]
Successful submission: https://ui.ingest.data.humancellatlas.org/submissions/detail/5d51692a1a249400085ac36a/overview

47 bundles exported. @ESapenaVentura , i'll mark this ticket as Done. If you see any issues, please let us know.

**Comment by parthshahva** [comment]
Why are there two copies of this project with data in the system?

Take a look at https://tracker.data.humancellatlas.org/?projectUUID=abe1a013-af7a-45ed-8c26-f3793c24a1f4 and https://tracker.data.humancellatlas.org/?projectUUID=82c1d3d0-0db7-452f-a22d-5cf22eec768f.

Additionally the one you mentioned @aaclan-ebi has 46 bundles the other one is still marked as processing and has 96 bundles

**Comment by aaclan-ebi** [comment]
The correct one is the https://tracker.data.humancellatlas.org/?projectUUID=abe1a013-af7a-45ed-8c26-f3793c24a1f4 with 47 bundles. Looks like there was a previous submission with incorrect bundles and @ESapenaVentura will request DSS to tombstone those.

**Comment by ESapenaVentura** [comment]
Ticket to tombstone the incorrect version [here](https://github.com/HumanCellAtlas/data-store/issues/2343) 

Sorry for the inconveniences.
