### ISSUE TITLE
Report all spreadsheet parsing errors in the UI

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#508]
Rather than just reporting one and ignoring the rest as we do at the moment

Only show as many errors as will fit on the screen. We do not want to make the page unusable by showing more errors than this. Usually there are less than 10 errors (@zperova)

This relies on a spike

** Acceptance criteria **
The user can see all the spreadsheet parsing errors.

**Comment by MightyAx** [comment]
Pull Request [ingest-ui#24](https://github.com/HumanCellAtlas/ingest-ui/pull/24)
Ready for Review.

**Comment by lauraclarke** [comment]
@MightyAx  Quick question on this, are you showing up to n unique errors and counts for each error type or are you showing just the first n errors regardless of uniqueness?

**Comment by zperova** [comment]
@lauraclarke we have agreed for a quick fix to display 10 parsing errors regardless of uniqueness to speed up invest for the incentive. More complex solutions (error tab in the UI) are in discussion for a later implementation.

**Comment by MightyAx** [comment]
Solved by
[ingest-ui 35e22ff](https://github.com/HumanCellAtlas/ingest-ui/commit/35e22fff6d23b5c0e82879389aa2c3349d823a5d)
