### ISSUE TITLE
[spike] How much work is required to make the spreadsheet importer continue when it encounters an error

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#509]
So we can report all errors.

**Comment by rolando-ebi** [comment]
Not a lot of change is required for parsing content cells in spreadsheets. We need to change the returns types of the various `do_import()` methods to also return a collection of errors/warnings. Parse/convert attempts should be surrounded in a try...catch, and caught exceptions should be added to the error/warning collections. At the end of import, if errors.length > 0 then write errors to ingest-core and skip writing any successfully parsed metadata.

Errors could be easily segregated by worksheet(i.e spreadsheet tab) -- failure to parse one spreadsheet shouldn't affect parsing of subsequent spreadsheets.
