### ISSUE TITLE
subEnvs -> subEnv / list -> stream refactorings

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-central#514]
~https://api.ingest.data.humancellatlas.org/submissionEnvelopes/5d51692a1a249400085ac36a/biomaterials?size=1000
reported by Parth: https://humancellatlas.slack.com/archives/C4LTU5RT8/p1566506663073300~

(Updated 6 Nov)  Originally intended to fix the slow API issue.

**Comment by rdgoite** [comment]
The solution for #576 is related to this.

**Comment by prabh-t** [comment]
This issue is resolved with lazy load dbrefs. It has also spawned refactoring that led to ingest-core PR #83 (subEnvs->subEnv / list->stream refactorings)
https://github.com/HumanCellAtlas/ingest-core/pull/83
Also see Slack thread
https://humancellatlas.slack.com/archives/GE613S72S/p1569857026006700

**Comment by MightyAx** [comment]
Comments from Sprint Planning: Please test your [branch](https://github.com/HumanCellAtlas/ingest-core/pull/83) on dev & integration to make sure the integration tests pass.

**Comment by prabh-t** [comment]
This has been done on dev, but not integration. Is there anything that integration would catch that dev wouldn't?

**Comment by aaclan-ebi** [comment]
All changes merged to master:

Passing Ingest Integration tests in DEV https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/ingest-integration-tests/pipelines/18731

Core: 78138e7
State tracker: c8f56a5
Validator: 49d863b

**Comment by aaclan-ebi** [comment]
Now in integration: https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/ingest-integration-tests/pipelines/18742
