### ISSUE TITLE
Error when attempting to use an invalid schema is not understandable

### ISSUE THREAD

**Issue by danielvaughan** [HumanCellAtlas/ingest-central#52]
**Give the bug a title**
Experienced by @samanehsan:

Error when attempting to use an invalid schema is not understandable.  

**To Reproduce**

A schema in JSON was specified as `https://schema.humancellatlas.org/type/file/6.1.1/analysis_file` but this version did not exist. Instead of producing a useful message the unhelpful error message was displayed.

`Expecting value: line 1 column 1 (char 0)`

Example:
```
{
    "file_core" : {
      "file_name" : "39f01baa-29a8-4106-9bfb-f3d9f0828608_qc.bam",
      "describedBy" : "https://schema.humancellatlas.org/core/file/6.1.1/file_core",
      "file_format" : "bam"
    },
    "describedBy" : "https://schema.humancellatlas.org/type/file/6.1.1/analysis_file",
    "schema_type" : "file"
  }
```

**Expected behaviour**

I expect a useful and helpful message.

**Actual behaviour**

```
  "validationErrors" : [ {
    "user_friendly_message" : "Expecting value: line 1 column 1 (char 0)"
  } ],
```
**Impact**
Error is difficult to debug and causes unnessary work for the green box.

**Comment by danielvaughan** [comment]
added JIRA: https://www.ebi.ac.uk/panda/jira/browse/HCA-1021

**Comment by aaclan-ebi** [comment]
Fix was deployed to production last 17th July.
