### ISSUE TITLE
[SPIKE]: Make UI fit for adding new bundles to an existing project

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#524]
This may be possible but extremely awkward for wranglers to do via the UI since this wasn't designed in. We need to check this is the case and design UI changes to improve that situation.

**Comment by aaclan-ebi** [comment]
User workflow is described under "Possible MVP" section:
https://docs.google.com/document/d/1O8QHJmMhImsx6OKAPAos3OKPxE9q9UniHHsPbCuAeuo/edit#heading=h.26lfb3396a2w
