### ISSUE TITLE
[Documentation] Link to DCP Policy Document

### ISSUE THREAD

**Issue by MightyAx** [HumanCellAtlas/ingest-central#525]
The ingest team have decided that high-priority Snyk PRs should be merged after a cursory review. This should be documented in a security policy document. Ideally this will already be documented in the DCP Security Policy document and we can simply link to it from our wiki. Otherwise a new document owned by the Ingest team should be created.

**Comment by justincc** [comment]
See these links to see if they are relevant - https://github.com/HumanCellAtlas/ingest-core/security/policy and https://github.com/HumanCellAtlas/ingest-central/security/policy

**Comment by MightyAx** [comment]
All of the security policies for the individual repos all reference the same .md:
https://github.com/HumanCellAtlas/.github/blob/master/SECURITY.md

We could add that merging Snyk vulnerabilities to the above policy for the entire HumanCellAtlas. I'll check with #dcp-security

**Comment by MightyAx** [comment]
Received approval from the Security working group to open a pull request that adds to the HCA security policy that merging Snyk pull requests should "be given best effort if unit and integration tests pass". Given their low cost and high benefit.

**Comment by MightyAx** [comment]
Had to fork the org repo to my personal to create a PR but here it is:
https://github.com/HumanCellAtlas/.github/pull/3

**Comment by MightyAx** [comment]
PR Merged
