### ISSUE TITLE
Restore ingest backups

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#537]
In the 2019-09-05 standup I learnt that backups had stopped working in July. If we lose the MongoDB then we lose the ability to do updates on ingested datasets. The only solution will be either to reingest (which will not be acceptable) or rebuild the DB out of the datastore. We have not thought about how to do the latter, whether it would be possible or how long it would take. Therefore, it is imperative that we are taking backups.

**Acceptance criteria**
Backups of our MongoDB are happening across all environments. If it will take a long time to do this for dev and integration then we may be able to drop these (though please discuss with the team first). But having production and staging is imperative.

**Comment by rdgoite** [comment]
I've updated the backup job with a new procedure for configuring the AWS credentials. The changes have been deployed to all environments. I've so far only seen it working on dev (by setting the backup to be more frequent); still needs to verify on the other environments.

**Comment by rdgoite** [comment]
I've confirmed that the fix worked for all other environments.
