### ISSUE TITLE
[SPIKE]: Design a process for automatically restoring and testing an ingest backup

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#538]
**Acceptance criteria**
We have a team-agreed design for a process to automatically restore an ingest backup and test it.

Taking backups is one thing. But if we don't test those backups it's as good as not having them at all. Witness the situation we have right now where backups stopped working in July due to DCP security changes but we weren't aware of this until early September.

See [Making the Meyer dataset available](https://docs.google.com/document/d/1O8QHJmMhImsx6OKAPAos3OKPxE9q9UniHHsPbCuAeuo/edit?ts=5d711b8c#heading=h.5wi8s3gxvadj)

**Comment by rdgoite** [comment]
I have [documented an overview of the strategies for testing and verifying the backups](https://docs.google.com/document/d/1hAku3V0H6Wva-hgKQFRN0J5H3Gf4wFo7i55GX7HVmZY/edit?usp=sharing) we generate using our backup operation.
