### ISSUE TITLE
Multiple copy edges in links.json

### ISSUE THREAD

**Issue by caaespin** [HumanCellAtlas/ingest-central#54]
**Multiple edges in links.json**

* [Validation] The are multiple copy edges in links.json

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to https://dss.integration.data.humancellatlas.org/v1/files/4c2e8482-1444-4a3a-8d4a-413c10cc273c?replica=aws&version=2018-04-12T112527.110275Z
2. Look for:
```
{
"source_id": "3575fc89-df78-4fa2-a177-d140e6b6a39e",
"source_type": "biomaterial",
"destination_id": "a18464e5-b4ac-4d66-b88c-a663321546aa",
"destination_type": "process"
}
```
3. Observe this edge repeats multiple times.

**Expected behaviour**

* I expect that links.json should only one copy for each edge.
    
**Actual behaviour**

* The links.json has multiple copies of the same edge.

**Impact**

It makes it hard to create indexes in orange box.

**Comment by danielvaughan** [comment]
Hi @caaespin,

We have some changes to the code that generates bundles already in integration. Do you experience similar problems if you use a more recently generated bundle e.g.

https://dss.integration.data.humancellatlas.org/v1/bundles/f4b1199a-5c72-4c20-ae42-54862b361a72/?replica=aws

**Comment by caaespin** [comment]
@danielvaughan , the links.json in this one seems fine. I wonder if this only happens under certain conditions or if it was something pervasive to all the old bundles.

**Comment by aaclan-ebi** [comment]
Hi @caaespin, There's a new links.json released along with the new bundle structure in integration environment. Closing this issue now as the issue was in the old links.json structure. Kindly let us know if you have further questions/concerns.
