### ISSUE TITLE
Only single bundle exported when attempting simple update

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/ingest-central#543]
**Only single bundle exported when attempting simple update**

**To Reproduce**

Steps to reproduce the behaviour:
1. Submitted a dataset in prod but realised I had forgotten to add myself as a data curator
2. Downloaded the spreadsheet from the UI
3. Added my details to the `Project - Contributors` tab
4. Created a new submission and changed it to 'Update'

**Expected behaviour**

all 5 bundles are exported to the data store

**Actual behaviour**

Only one bundle exported to the datastore

**Impact**

This will prevent all bundles being analysed. This is a high priority dataset for the CZI incentive

@aaclan-ebi is currently working on this and it is related to #535 

The project tracker ticket is https://github.com/HumanCellAtlas/hca-data-wrangling/issues/272

**Comment by aaclan-ebi** [comment]
Manually worked around the 4 bundles that needed fixing. The update submission is now complete. 5 bundles were updated.

I'm going to mark this done specific to this WongAdultRetina dataset 

Please refer to the https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/543 for the permanent fix.

**Comment by mshadbolt** [comment]
I will close this now that I reingested and this is now no longer relevant.
