### ISSUE TITLE
Implement backup checking

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#555]
This will be a choice of action from the [Ingest Backup Testing doc](https://docs.google.com/document/d/1hAku3V0H6Wva-hgKQFRN0J5H3Gf4wFo7i55GX7HVmZY/edit#heading=h.kqtg94q0pcns)

**Comment by rdgoite** [comment]
Basic implementation of backup checking is now implemented. There are some further improvements noted in the [proposal document](https://docs.google.com/document/d/1hAku3V0H6Wva-hgKQFRN0J5H3Gf4wFo7i55GX7HVmZY).
