### ISSUE TITLE
Test process of re-ingesting a dataset with project UUID preservation

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#561]
In staging.
[Reingestion via New Project Document](https://docs.google.com/document/d/1O8QHJmMhImsx6OKAPAos3OKPxE9q9UniHHsPbCuAeuo/edit#heading=h.zgdx5miry37h)
- [x] Find Project on [Prod](https://ui.ingest.data.humancellatlas.org/projects/detail?uuid=c4077b3c-5c98-4d26-a614-246d12c2e5d7) & [Staging](https://ui.ingest.staging.data.humancellatlas.org/projects/detail?uuid=8b01ff5a-2157-4c4a-96bb-2c686a7ef8b0)
- [x] Tombstone all existing bundles
- [x] Note the original Binary representation of the UUID
  - `db.project.find({_id: ObjectId("...")},{"uuid.uuid":1})`
- [x] Update the uuid of the project in the original submission and in its bundle manifests to some random UUID.
  - `db.project.updateOne({_id: ObjectId("...")}, { $set: {"uuid.uuid": BinData(3,"...") } } )`
  - `db.bundleManifest.updateMany({ "fileProjectMap": { "...": [ "..." ] } }, { $set: { "fileProjectMap": { "...": [ "...." ] } } })`
- [x] Ensure the ingestion spreadsheet does not contain any external references.
- [x] Ingest the Meyer spreadsheet and upload its files
- [x] Before submit, update the project uuid in the new submission to the original uuid.
- [x] Submit.

**Comment by MightyAx** [comment]
Using http://guid-convert.appspot.com to get from UUID Hex to Base64
```
db.project.find({"_id": ObjectId("...")})
db.project.updateOne({"_id": ObjectId("...")},{ $set: {uuid: {uuid: BinData(3,"...")}}})
```

**Comment by MightyAx** [comment]
Waiting on https://github.com/HumanCellAtlas/data-store/issues/2461

**Comment by justincc** [comment]
From convo with @MightyAx this morning, he is going to talk to @zperova soon since we're in a position to test this process with the dataset she needs to reingest due to assay structure changes.

**Comment by MightyAx** [comment]
# Staging Re-Ingestion Notes
Target UUID (string): `8b01ff5a-2157-4c4a-96bb-2c686a7ef8b0`
Target UUID (binary): `BinData(3,"SkxXIVr/AYuw+H5qaCy7lg==")`


## Convert old project and manifests:
`db.project.find({"_id" : ObjectId("5d84f4f9e397b20008e67c0b")},{"uuid.uuid": 1})`
`db.project.updateOne({_id: ObjectId("5d84f4f9e397b20008e67c0b")}, { $set: {"uuid.uuid": BinData(3,"bDSuTeno6RGBtCoq4tvM5A==") } } )`
New UUID (String): `"11e9e8e9-4dae-346c-e4cc-dbe22a2ab481"`
New UUID (Binary): `BinData(3,"bDSuTeno6RGBtCoq4tvM5A==")`

`db.bundleManifest.find({ "fileProjectMap": { "8b01ff5a-2157-4c4a-96bb-2c686a7ef8b0": [ "8b01ff5a-2157-4c4a-96bb-2c686a7ef8b0" ] } }).count()`
`db.bundleManifest.updateMany({ "fileProjectMap": { "8b01ff5a-2157-4c4a-96bb-2c686a7ef8b0": [ "8b01ff5a-2157-4c4a-96bb-2c686a7ef8b0" ] } }, { $set: { "fileProjectMap": { "11e9e8e9-4dae-346c-e4cc-dbe22a2ab481": [ "11e9e8e9-4dae-346c-e4cc-dbe22a2ab481" ] } } })`


## Convert New Project
### Find new project:
`db.project.find({"_id" : ObjectId("5d9b33d11c8f4500088c6d21")},{"uuid.uuid": 1})`

### Check that our specified project UUID is not used:
`db.project.find({"uuid.uuid" : BinData(3,"SkxXIVr/AYuw+H5qaCy7lg==")},{"uuid.uuid": 1})`

### Convert new project to specified UUID
`db.project.updateOne({_id: ObjectId("5d9b33d11c8f4500088c6d21")}, { $set: {"uuid.uuid": BinData(3,"SkxXIVr/AYuw+H5qaCy7lg==") } } )`

## Bundle Manifests
### Find Bundle manifests of our new project
`db.bundleManifest.find({ "fileProjectMap": { "51dd56d6-e2d2-4bfa-8bc6-c8bab87488d6": [ "51dd56d6-e2d2-4bfa-8bc6-c8bab87488d6" ] } }).count()`

### Find Bundle manifests for our specified project.
`db.bundleManifest.find({ "fileProjectMap": { "8b01ff5a-2157-4c4a-96bb-2c686a7ef8b0": [ "8b01ff5a-2157-4c4a-96bb-2c686a7ef8b0" ] } }).count()`

### Convert Bundle manifests to specified project UUID
`db.bundleManifest.updateMany({ "fileProjectMap": { "51dd56d6-e2d2-4bfa-8bc6-c8bab87488d6": [ "51dd56d6-e2d2-4bfa-8bc6-c8bab87488d6" ] } }, { $set: { "fileProjectMap": { "8b01ff5a-2157-4c4a-96bb-2c686a7ef8b0": [ "8b01ff5a-2157-4c4a-96bb-2c686a7ef8b0" ] } } })`
