### ISSUE TITLE
Levitin submission finished.

### ISSUE THREAD

**Issue by cjvillar** [HumanCellAtlas/ingest-central#565]
Just commenting that the Levitin submission finished all analysis and is in Production. Still waiting on an expression matrix from the matrix service. 
https://data.humancellatlas.org/explore/projects/4a95101c-9ffc-4f30-a809-f04518a23803

Not sure what other info is needed here but was told to make an issue for complete incentive datasets.

**Comment by jlzamanian** [comment]
Matrices are complete and on the portal.
