### ISSUE TITLE
Ingesting RuiChen_retina dataset in prod

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/ingest-central#569]
I plan to ingest RuiChen_retina dataset in prod on 20 September 2019. No problems occurred during ingestion in staging. 

Project UUID: 9c20a245-f2c0-43ae-82c9-2232ec6b594f

https://github.com/HumanCellAtlas/hca-data-wrangling/issues/278

**Comment by jlzamanian** [comment]
@HumanCellAtlas/data-ops

**Comment by jlzamanian** [comment]
Project tracker:  https://tracker.data.humancellatlas.org/?projectUUID=9c20a245-f2c0-43ae-82c9-2232ec6b594f
Submission uuid: 7d515499-b5b6-4083-95cd-6a393344865e
Project uuid: 9c20a245-f2c0-43ae-82c9-2232ec6b594f
Portal page: https://data.humancellatlas.org/explore/projects/9c20a245-f2c0-43ae-82c9-2232ec6b594f

This project was ingested successfully and without issues.
