### ISSUE TITLE
Upgrade MongoDB

### ISSUE THREAD

**Issue by rdgoite** [HumanCellAtlas/ingest-central#571]
Ingest currently use MongoDB 3.4.3 which [reaches its EOL on the 31 January 2020](https://www.mongodb.com/support-policy)(see "MongoDB Server" section). It is advised to use at least version 3.6 but if there are no compatibility issues moving to the latest (4.2 as of writing), that's recommended.

Of particular note, UUIDs in Ingest currently use UUID type 3, while the later ones default to type 4. This might need to be addressed in some way during migration.
# Rollout plan
- [x] Migrate to feature compatibility 3.4 [PR: ingest-core#87](https://github.com/HumanCellAtlas/ingest-core/pull/87)
- [ ] [Update Docker configuration to 3.6](https://github.com/HumanCellAtlas/ingest-core/tree/migration/mongo3.6.15)
- [ ] [Migrate to feature compatibility 3.6](https://github.com/HumanCellAtlas/ingest-core/tree/migration/mongo-feature3.6)
- [ ] [Update Docker configuration to 4.0](https://github.com/HumanCellAtlas/ingest-core/tree/migration/mongo4.0.13)
- [ ] [Migrate to feature compatibility 4.0](https://github.com/HumanCellAtlas/ingest-core/tree/migration/mongo-feature4.0)
- [ ] [Update Docker configuration to 4.2](https://github.com/HumanCellAtlas/ingest-core/tree/migration/mongo4.2)
- [ ] [Migrate to feature compatibility 4.2](https://github.com/HumanCellAtlas/ingest-core/tree/migration/mongo-feature4.2)

**Comment by MightyAx** [comment]
The migration of UUID 3 to 4 is not part of the upgrade. The string representation of UUID4 is a different format to UUID3. Our UUIDs are made visible to the user and so we need to keep the format the same (for now).

**Comment by MightyAx** [comment]
[Migrate to feature compatibility 3.4](https://github.com/HumanCellAtlas/ingest-core/pull/87) Merged, due for staging:
