### ISSUE TITLE
Ingested Filipe's dataset in Prod

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/ingest-central#572]
Dataset `Single cell profilling of human induced dendritic cells generated by direct reprogramming of embryonic fibroblasts` has been ingested in production.

Tracker ticket in data-wrangling here: [#284](https://github.com/HumanCellAtlas/hca-data-wrangling/issues/284)

Currently waiting for analysis, but it has generated the right amount of bundles and the previous staging submission had been analyzed correctly.

**Comment by jlzamanian** [comment]
@HumanCellAtlas/data-ops
