### ISSUE TITLE
[SPIKE]: Design approach for avoiding adding supplementary files in draft to a submission

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#573]
See [Issue 2 in the Meyer doc](https://docs.google.com/document/d/1O8QHJmMhImsx6OKAPAos3OKPxE9q9UniHHsPbCuAeuo/edit#heading=h.yjntpsmtrrn7)

**Comment by MightyAx** [comment]
Implementation Ticket: https://github.com/HumanCellAtlas/ingest-central/issues/583
