### ISSUE TITLE
[SPIKE]: Design approach for failing a submission if it references any documents in a draft submission

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#574]
See [Issue 3 in the Meyer Dataset doc](https://docs.google.com/document/d/1O8QHJmMhImsx6OKAPAos3OKPxE9q9UniHHsPbCuAeuo/edit#heading=h.gildpo4o5qqx)

**Comment by MightyAx** [comment]
Implementation Ticket: https://github.com/HumanCellAtlas/ingest-central/issues/583
