### ISSUE TITLE
Remediate High js-yaml vulnerability

### ISSUE THREAD

**Issue by Lilalamar** [HumanCellAtlas/ingest-central#578]
GitHub reports the following [**High** severity vulnerability](https://github.com/HumanCellAtlas/ingest-ui/network/alert/client/yarn.lock/js-yaml/open) in HumanCellAtlas/ingest-ui. Please remediate by the end of Q4 Milestone 1.

**Description**
js-yaml

**Suggested Remediation**
Upgrade js-yaml to version 3.13.1 or later.

**[Details](https://github.com/nodeca/js-yaml/pull/480)**
Js-yaml prior to 3.13.1 are vulnerable to Code Injection. The load() function may execute arbitrary code injected through a malicious YAML file.

**Comment by MightyAx** [comment]
Automated Security Fix [failed](https://github.com/HumanCellAtlas/ingest-ui/network/alert/client/yarn.lock/js-yaml/open/update-errors/1703423). This will need manual investigation/remediation, will schedule this for next sprint.
