### ISSUE TITLE
Issues with Reprogrammed_Dendritic_Cells analysis bundles after AUDR simple update

### ISSUE THREAD

**Issue by jlzamanian** [HumanCellAtlas/ingest-central#581]
AUDR simple update was used on Reprogrammed_Dendritic_Cells in prod.
A typo was fixed in the project title and the description was slightly modified. These changes are reflected in the browser

https://data.humancellatlas.org/explore/projects/116965f3-f094-4769-9d28-ae675c1b569c
https://github.com/HumanCellAtlas/ingest-central/issues/572

AUDR was used after the analysis workflows ran. After AUDR simple update, the updated bundles were not able to be indexed by either Azul or the matrix service.

https://tracker.data.humancellatlas.org/?projectUUID=116965f3-f094-4769-9d28-ae675c1b569c

The issue was investigated in these tickets.

https://github.com/DataBiosphere/azul/issues/1320
https://github.com/HumanCellAtlas/matrix-service/issues/396

and may be related to the issues with this ticket.

https://github.com/HumanCellAtlas/ingest-central/issues/576

**Comment by jlzamanian** [comment]
@HumanCellAtlas/ingest 
@HumanCellAtlas/data-ops 
@parthshahva

**Comment by ESapenaVentura** [comment]
I'll tag myself here to get updates on the subject! Thanks for the ticket @jlzamanian

**Comment by aaclan-ebi** [comment]
I had a quick look at this. It seems that the API endpoint to GET the bundle only returns a maximum of 500 files. https://dss.data.humancellatlas.org/v1/bundles/cb88115c-75ef-4e8e-bbd7-a48e18960344/?replica=aws&version=2019-09-26T034726.748575Z Only those 500 files retrieved from that GET request are being included in the update bundles.

DSS API has an endpoint for doing PATCH. We could utilise that instead of doing the current update mechanism (getting files from GET /bundle/uuid and updating all the files with newer versions)

**Comment by parthshahva** [comment]
Just discussed in person. @kislyuk may have some guidance here on interaction between Ingest and DSS

**Comment by kislyuk** [comment]
@aaclan-ebi the reason you are only seeing 500 files is that the response is paginated. You can follow the documentation in the "Pagination" sections of https://hca.readthedocs.io/en/latest/api.html to retrieve the full results, or just use the DSS API client:
```
from hca.dss import DSSClient

print(len(list(DSSClient().get_bundle.iterate(uuid="cb88115c-75ef-4e8e-bbd7-a48e18960344", version="2019-09-26T034726.748575Z", replica="aws"))))
```
```
565
```

**Comment by aaclan-ebi** [comment]
Yes, sorry, I meant max of 500 by default. We missed to consider that result is paginated :-( 

In this case, it's more efficient for us to just use the PATCH bundle endpoint in our code.

**Comment by rolando-ebi** [comment]
I've fixed the paginated results, will need to get the fix into prod. Nexts steps are to tombstone the affected bundles, and then re-ingest the updates

**Comment by rolando-ebi** [comment]
```
bundles_to_tombstone = [
    "cb97a8e3-8593-45df-bc63-caaa9200d3c4.2019-09-26T120958.021330Z",
    "1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.2019-09-26T120958.017471Z",
    "c6633095-68f9-4118-981b-16dc8b42a5a1.2019-09-26T120958.018559Z",
    "1307154a-0396-4f2c-a1bf-4a2bf593b1a0.2019-09-26T120958.019770Z",
    "cb88115c-75ef-4e8e-bbd7-a48e18960344.2019-09-26T120958.020808Z",
    "52245757-73ba-43a2-a78d-0eba01cb4ce1.2019-09-26T120958.022205Z"
]
```

**Comment by kislyuk** [comment]
@rolando-ebi for completeness, can you link to the fix here?

**Comment by rolando-ebi** [comment]
@kislyuk Sure the fix commit is here: https://github.com/HumanCellAtlas/ingest-client/commit/7dca49ec1c2799d4d84b0bb50eeaeaaca4b5e891

**Comment by rolando-ebi** [comment]
The updates have been re-ingested and the 6 bundles have been updated:

```
bundles = [
    'c6633095-68f9-4118-981b-16dc8b42a5a1.2019-10-03T105524.913003Z', 
    '1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.2019-10-03T105524.911627Z', 
    '52245757-73ba-43a2-a78d-0eba01cb4ce1.2019-10-03T105524.918205Z', 
    'cb97a8e3-8593-45df-bc63-caaa9200d3c4.2019-10-03T105524.916954Z', 
    'cb88115c-75ef-4e8e-bbd7-a48e18960344.2019-10-03T105524.915852Z', 
    '1307154a-0396-4f2c-a1bf-4a2bf593b1a0.2019-10-03T105524.914465Z'
]
```

@jlzamanian please confirm with Azul and Matrix Service

**Comment by amarjandu** [comment]
> ```
> bundles_to_tombstone = [
>     "cb97a8e3-8593-45df-bc63-caaa9200d3c4.2019-09-26T120958.021330Z",
>     "1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.2019-09-26T120958.017471Z",
>     "c6633095-68f9-4118-981b-16dc8b42a5a1.2019-09-26T120958.018559Z",
>     "1307154a-0396-4f2c-a1bf-4a2bf593b1a0.2019-09-26T120958.019770Z",
>     "cb88115c-75ef-4e8e-bbd7-a48e18960344.2019-09-26T120958.020808Z",
>     "52245757-73ba-43a2-a78d-0eba01cb4ce1.2019-09-26T120958.022205Z"
> ]
> ```

just including myself here to track tombstone requests.
https://gist.github.com/amarjandu/1b36b3c7e8f794c22cfb46302fb15c5f

**Comment by jlzamanian** [comment]
QA'd
