### ISSUE TITLE
[Exporter] Contents of Non-Complete Submissions should not be referenced by new submissions. 

### ISSUE THREAD

**Issue by MightyAx** [HumanCellAtlas/ingest-central#583]
Implementation of spikes: #573 and #574

### Case 1 Reject Submissions which depend on non-complete submissions:
![Screenshot 2019-10-02 at 11 21 43](https://user-images.githubusercontent.com/13031259/66037111-d190c100-e506-11e9-9f85-1ac966e56f0f.png)

Submission A and B are both valid but **not complete**.
User tries to submit B. However, this references Project 1 in submission A.

### Desired Outcome:
  1. Submit B: The submission is **rejected**.
  2. Submit A: The submission should complete but not contain B's metadata (Donor 2, C Sup 2, Fastq 2)
    - This scenario covered in more detail in case 2
  3. Submit B: The submission **completes**.

### Case 2 :
![Screenshot 2019-10-02 at 11 26 57](https://user-images.githubusercontent.com/13031259/66037452-8dea8700-e507-11e9-8d58-12a1de5b0144.png)

Submission A is **complete**.
Submission B and C both add some metadata or supplementary files, are valid but are **not yet complete**.

#### Desired Outcome:
  1. Submit C: The submission should **complete**, only adding `Donor 1`, with a link to `Project 1`.
  2. Submit B: The submission should **complete**, only adding `Supp 1` into `Project 1`.

## Implementation considerations:
The Exporter should only use metadata and supplementary files from **complete submissions** to build  a bundle manifest.

Initial Implementation Design:
Before exporting data to the data store, crawl the graph of `MetadataDocument` entities asserting that for every `MetadataDocument` in the graph: Either the `SubmissionEnvelope` is the submission being exported or the `ValidationState` is `Complete`, signifying it is stored in the data store.

As part of this pre-export step we should store a representation of what will be sent to the data store so that future submissions cannot affect what this submission represents, also meaning that the graph crawl is only required once per submission.

When the data store signals that a file has been submitted we should set the `ValidationState` of the `MetadataDocument` to Complete.

### Alternatives
If required using a new property on MetadataDocument to store the `SubmissionState`, rather than using `ValidationState` is acceptable.

## A Note on Deletion
A pre-requisite of all implementations we have considered thus-far has been the ability to delete submissions and the metadata they contain. This is required because there can exist situations where Submission A can block Submission B, as detailed above. These blocks can only be lifted by completing or deleting Submission A, therefore if submission A was created in error, it should be possible to delete.

Technically this should be possible due to the link to `submissionEnvelope` on `MetaDataDocument`.

# Unanswered Questions:
  - Do we check if an external reference **exists** before adding data to the data-store?
  - Can we use the presence of the `DCPVersion` property on `MetaDataDocument` to determine if the item has already been added to the data store?

**Comment by MightyAx** [comment]
# Possible MVP
It may be that a better solution for resolving this issue in the short term is to **only allow one incomplete submission per project**. This would implicitly grant us the desired outcomes listed above.

The pre-requisites of this approach would be:
  - Ability to deleting incomplete submissions
  - Project First structure (at least at an API level)

With the above pre-requisites only allowing one incomplete submission for a project is easy at an API level. At the UI level it could be simply disabling the "Create new Submission" button for a project, and highlighting the incomplete submission for the user to delete or complete.

This workflow also models how the wranglers currently work, in an isolated way with only one wrangler per project. Iterating their single submission until they are accepted into the data store. Once the wranglers need to move to a more collaborative workflow, we could work on any of the solutions mentioned above or other solutions that are more relevant at the time such as editing submissions via the ui rather than adding more submissions with more spreadsheets (as is the long term goal).

This also means that we are not trying to build logic to support how multiple submissions are related to each other into a data model that doesn't really support the idea of isolated submission data.

**Comment by aaclan-ebi** [comment]
Changes needed for the described MVP above:

* User shouldn't be allowed to create a submission if there is an incomplete submission (Checking if a project has incomplete submissions)
	- All submissions (including analysis and update submissions) must have a reference to the projects.
	- We need to establish how we model project -> submission relationship. Can be included in this change https://github.com/HumanCellAtlas/ingest-core/pull/83
	
* User should be able to link new entities to existing entities.
	- This should be possible in the spreadsheet by specifying uuids, labels
	- Limitation: if the linking for 2 entities uses a different protocol, it would be very har to indicate this in the spreadsheet

* Fix the exporter to not upload files which are already in the DSS. 
	- Already covered in ticket https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/575

**Comment by aaclan-ebi** [comment]
Other things to consider for usability:
1. Users should be able to see how things are linked.
2. Users should be able to delete a submission (all entities created by that submission will be deleted, any linking should be removed) OR
3. Users should be able to modify existing submission ( add more, edit, delete a metadata). For the delete, the state tracker should be notified.

**Comment by MightyAx** [comment]
# Project First User Story (UI)
## Project Creation
  - Project Core fields displayed:
    - Title, Description, Shortname? (viewable only by submitter)
    - Once submitted a Unique link is shown
    - Other project fields
      - Name / DataType / Validation rules detected from Project Metadata Schema
  - Project Page Structure Config
    - Pages of Project information are organized for input from the page structure config which references schema fields.
JSON that describes what schema fields are displayed where, with reference to schema.

## Project Submissions
  - Submissions can only be created from project screen.
  - New Submission button only available when no other incomplete submissions exist.

## Existing Functionality
  - Project screen shows list of all submissions created for a project.

# Project First User Story (API)
## Project 
  - Creation Endpoint
    - Title, Description
    - Returns permanent Project UUID
  - Update Endpoint
    - Schema URL
    - Project Metadata document that validates against the passed schema

## Submission Envelope
  - URI for create endpoint should include project id
  - API should deny operation if incomplete submission for project already exists

**Comment by justincc** [comment]
Let's go ahead with restricting submissions to one at a time. The next step is to lay out the work required to do this then design it to a level of detail where we can point estimate.

**Comment by justincc** [comment]
Notes from meeting with wranglers today:

1. At the moment wranglers CANNOT put in submissions that do not contain or reference a project.
  a) When this needs to change, we will either implement this ability or decide that such data entry will require a 'dummy' project.

2. Case 1 agreed with wranglers

3. Case 2: In the first instance, we will not report other valid submissions on another submission

4. Case 1/2: We will not allow a submission to link to an entity unless that entity has been submitted. This will require considerable implementation work by ingest to do these checks up front rather than at export time. This may have value for controlling permissions as to what submitters can link to.

A) Look into having a submissions alert channel so dev know what is coming down the pipe without requiring wranglers to manually raise tickets.

**Comment by justincc** [comment]
We are now waiting for confirmation from @zperova that wranglers are happy with this approach in [their 2019-10-17 catchup](https://docs.google.com/document/d/1FERHXnmdk62EzM0DLgMYKnHbzFgZEMYtbCVVAGks7MQ/edit#bookmark=id.byb5gvqj9pd6).

**Comment by tburdett** [comment]
From the discussion today and reviewing this ticket, I think there's some confusion about the underlying domain model in ingest. I don't want to change decisions that have been made, but it's very clear to me that a better understanding of the possible trade offs being made could have helped us make a decision faster. I'd like to propose a meeting with the whole team to recap our understanding of the domain model and the implications it has for possible implementation choices sometime soon. Any objections?

**Comment by MightyAx** [comment]
@tburdett No Objections. sounds very useful.

**Comment by zperova** [comment]
@justincc I confirm that all the wranglers have been informed of the approach. 
@tburdett I would appreciate having a meeting on this

**Comment by lauraclarke** [comment]
Everyone should have been invited to such a meeting on Nov 20th

If people have specific questions they would like to see addressed please let us know. Our starting point will currently be what is a project.

**Comment by MightyAx** [comment]
Closing this ticket as a design spike.
Decision made to restrict each project to just one open submission at a time. 

Tickets for implementing the Pre-Requisites:
#582
#599

Ticket for the implementing MVP Work:
#605
