### ISSUE TITLE
Upgrade to the latest Kubernetes

### ISSUE THREAD

**Issue by rdgoite** [HumanCellAtlas/ingest-central#588]
All deployment environments are running Kubernetes v1.11 at the time of writing. There was a [security bulletin on a high severity vulnerability last September](https://cloud.google.com/kubernetes-engine/docs/security-bulletins#september_16_2019), and the recommendation is to upgrade to latest patch version.

This can be done through the [EKS dashboard](https://console.aws.amazon.com/eks/home?region=us-east-1#/clusters)(check the documentation for more details).

**Comment by rdgoite** [comment]
Also look into enabling logs for EKS clusters.

**Comment by justincc** [comment]
Amazon EKS will stop supporting 1.11 on 2019-11-04. We must upgrade before then.
