### ISSUE TITLE
[Validation] Empty tab causes sheet validation to fail

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/ingest-central#59]
**To Reproduce**

Uploading a spreadsheet with organoid or cell line tabs with empty information causes validation to fail

**Expected behaviour**

If no data is added to the sheet the sheet should be ignored. I expected to see a success message and for the metadata to pass validation.

**Actual behaviour**

Validation failed.

**Impact**

Contributors/wranglers given large templates will also be responsible for knowing that they must delete empty sheets they do not use.

**Comment by malloryfreeberg** [comment]
I second this ticket as I have empty protocol tabs that are trying to be converted to JSON and they really should just be ignored.

**Comment by aaclan-ebi** [comment]
Fix is currently deployed in dev.

**Comment by malloryfreeberg** [comment]
Fix in dev looks good 👍
