### ISSUE TITLE
Jiarui submitted in Production.

### ISSUE THREAD

**Issue by cjvillar** [HumanCellAtlas/ingest-central#591]
Jiarui submitted in Production. Making a ticket here as agreed.

https://ui.ingest.data.humancellatlas.org/submissions/detail/5d9dfd3771fe4a0008e10b5b/overview

**Comment by jlzamanian** [comment]
Project tracker: https://tracker.data.humancellatlas.org/?projectUUID=88ec040b-8705-4f77-8f41-f81e57632f7d
Submission uuid: d1610c4a-76c6-4b69-af63-c74af869fa75
Project uuid: 88ec040b-8705-4f77-8f41-f81e57632f7d
Portal page: https://data.humancellatlas.org/explore/projects/88ec040b-8705-4f77-8f41-f81e57632f7d

This project was ingested successfully and without issues.
