### ISSUE TITLE
Bring staging environment back up after failures in week of Mon 7th October 2019

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#593]
This ticket tracks the operations work we're currently having to undertake to restore the staging environment. This environment started failing for unknown reasons (please add more detail as appropriate).

**Comment by justincc** [comment]
This failed again today when @mshadbolt tried to import the same dataset (which?) associated with the previous failure. The error looks like the same so we now strongly suspect this is the trigger rather than an infrastructure failure.

Next steps are:

0) Restore the staging environment again and ask @mshadbolt not to ingest that dataset again.
1) If there is another dataset waiting for ingestion do that and see if the same failure occurs.
2) If not, and/or in parallel investigate how Marion's data dataset is triggering the failure.
3) Come up with a fix/workaround.

**Comment by mshadbolt** [comment]
The dataset I was trying to ingest was the Meyer dataset (https://github.com/HumanCellAtlas/hca-data-wrangling/issues/86) 

I need to ingest this before the end of this week.

**Comment by rdgoite** [comment]
Thanks @mshadbolt. I don't feel like this should be something that could cause the problem, but we'll continue investigating.

**Comment by mshadbolt** [comment]
Is staging likely to be back tomorrow? Can we do a test with the updated spreadsheet without the error I mentioned above so I can submit this to prod?

**Comment by mshadbolt** [comment]
@rdgoite approved me trying to upload the spreadsheet to without the mixed id column in the sequence file tab into the integration environment. 

I uploaded this spreadsheet, I waited for the spreadsheet to change to draft before transferring data files, but the status did not change, I tried refreshing the page and it showed that integration environment went down.

When I browsed the metadata validation it looked like they were all valid but the overall project stayed in 'Pending' until the server died.

I did not try to transfer any files to the s3 upload bucket.

**Comment by rolando-ebi** [comment]
The spreadsheet in question had >1 million rows (most blank rows) for the Sequence File tab. Inserting a column into that tab caused the underlying excel lib (openpyxl) to load millions of cells, mostly blank, into memory causing the cluster to fall over. Related ticket: https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/597
