### ISSUE TITLE
[F2F] Provenance Update = Version

### ISSUE THREAD

**Issue by MightyAx** [HumanCellAtlas/ingest-central#598]
![IMG_6342](https://user-images.githubusercontent.com/13031259/67335079-2b2a5100-f4f1-11e9-92db-7ef1741d3b83.jpg)
@maniarathi, please find who knows the whole issue here.

**Comment by rolando-ebi** [comment]
This is where the "update_date" field in provenance.json doesn't match the dcpVersion field. Matrix service requested that the timestamps match

**Comment by maniarathi** [comment]
@rolando-ebi Do you know where this change would need to be made?

**Comment by maniarathi** [comment]
@calvinnhieu @mckinsel FYI

**Comment by rolando-ebi** [comment]
@maniarathi this would need to be made in the exporter component

**Comment by maniarathi** [comment]
So it looks as though the version is actually specified as a field in the DSS put_file API so I can't quite understand where the difference is coming from if Ingest specifies the uuid and the version. Any insight from other folks here?

**Comment by maniarathi** [comment]
@rolando-ebi @MightyAx

**Comment by aaclan-ebi** [comment]
FIx for this is included in https://github.com/HumanCellAtlas/ingest-client/pull/67

**Comment by aaclan-ebi** [comment]
Requested update to the schema to rename update_date to version https://github.com/HumanCellAtlas/metadata-schema/issues/1191
