### ISSUE TITLE
Delete unsubmitted (open) submissions from the ingest UI

### ISSUE THREAD

**Issue by morrisonnorman** [HumanCellAtlas/ingest-central#599]
## Specific use case or user story:
As a wrangler I would like to be able to delete a partial or incomplete submission from the ingest UI, so that I can identify current or open submissions. 

## Current gap, problem or bottleneck:
Often wranglers upload a spreadsheet or data then realise that it is fundamentally wrong and abandon the submission. There is currently no way for the wrangler to get rid of it and no way for ingest to know that it is no longer needed. This leads to multiple submissions that are no longer needed making it hard to keep track of and find the correct one.

## Value proposition:
Wranglers are able to carry out basic housekeeping of partial or incomplete submissions. Ingest UI shows only relevant active submissions making it easy for wranglers to track the status of active submissions.

## MVP requirements:
Ability for wranglers to hide/delete incomplete, abandoned or incorrect submissions

## Suggester:
@mshadbolt

**Comment by justincc** [comment]
This is going to be part of implementing bundle additions as discussed in the 2019-10-15 internal demo meeting.

**Comment by aaclan-ebi** [comment]
During delete submission, each metadata should be unlinked to any metadata outside that submission envelope. Or, we could apply the linking after setting the submission to Submitted. Everything before `Submitted` could be deleted.

**Comment by MightyAx** [comment]
Don't use deletion for redaction cases.

**Comment by aaclan-ebi** [comment]
changed the title to `Delete unsubmitted (open) submissions from the ingest UI` to be more clear of the scope of the delete implementation here.

**Comment by aaclan-ebi** [comment]
changed the title to Delete unsubmitted (open) submissions from the ingest UI to be more clear of the scope of the delete implementation here.
