### ISSUE TITLE
Prepare talk about the HCA DCP for the AIT retreat

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/ingest-central#622]
This ticket is to track the work that @ESapenaVentura and @prabh-t are doing to create a joint 15-minute presentation for the AIT team retreat on Dec 3rd about our work for the HCA DCP.

The goal of the presentation is to give everyone else insight into the goals of our work and what user needs we are trying to meet.

The user journey maps may be useful to you in this process.
https://drive.google.com/drive/u/1/folders/1f8x8a0cFER4L3JGDksOPGsWHQfhcMNOc

The slide deck should contain a TLDR slide at the end about these goals to help future sessions at the retreat.

Please provide a draft slide deck for review by @lauraclarke @morrisonnorman and @justincc by November 27th.

You can put your slides in
https://drive.google.com/open?id=1MQyy4Nnr5jvSp3up7JLocpUwPnm6bLVW

- [x]  Presentation send to Laura, Norman and Justin for review
- [x]  Slides completed

**Comment by ESapenaVentura** [comment]
This ticket is finished so @justincc feel free to close it when you feel appropriate!
