### ISSUE TITLE
[Ingest-UI] Hide Button for Create Submission for Projects that have an open submission.

### ISSUE THREAD

**Issue by MightyAx** [HumanCellAtlas/ingest-central#628]
Use new core property on project
`Project.HasOpenSubmission()`

To disable Create Submission button on:
- Project view
- List of Projects

**Comment by MightyAx** [comment]
Tested that the following method on Project is called when the project is serialised, therefore it is called as the api is building the response to the caller, rather than the caller having to make an additional API call for each project.
```
///Project
public Boolean getHasOpenSubmission(){
   for (SubmissionEnvelope submissionEnvelope : this.submissionEnvelopes) {
       if (submissionEnvelope.isOpen()){
            return true;
        }
    }
    return false;
}
```
JSON Snippet returned:
```
        "events": [],
        "dcpVersion": null,
        "accession": null,
        "validationState": "Valid",
        "validationErrors": [],
        "isUpdate": false,
        "hasOpenSubmission": false,
        "_links": {
```

**Comment by prabh-t** [comment]
have you tried to see if it correctly returns `true` if project has an open submission?

**Comment by MightyAx** [comment]
> have you tried to see if it correctly returns `true` if project has an open submission?
indeed, tested with backup of prod data.

**Comment by aaclan-ebi** [comment]
I temporarily reverted the changes in `dev` and `integration`. 

PR  https://github.com/HumanCellAtlas/ingest-ui/pull/40 should fix the issue.

Please feel free to merge and deploy.
