### ISSUE TITLE
[Ingest-Core] Restructure references so that removing an entity removes references to that entity.

### ISSUE THREAD

**Issue by MightyAx** [HumanCellAtlas/ingest-central#630]
Alternate implementation for #626
#### Acceptance Criteria
- References to **Biomaterials** and **Files** are stored on **Process** objects.
- References to **Processes** are stored on **Protocol** objects.
- References to **Processes** are stored on **BundleManifest** objects.
- Project contains migration of existing data to new format.
- Ingest API endpoints have not changed
  - The storage of these relationships should change, not the functionality.
- When deleting a submission the system performs better than the iterative approach proposed in #626
- Test performance of this change with Tabula Muris

Highlight any negative impacts to the data model / performance compared to #626. Final merge can only take place after a team discussion.

**Comment by aaclan-ebi** [comment]
1. References to Biomaterials and Files are stored on Process objects. 
+1 for this

2. References to Processes are stored on Protocol objects.
3. References to Processes are stored on BundleManifest objects.

2&3 seems not necessary in my opinion.

In adding bundles, mostly we add new processes. Having the dbrefs/links in processes will simplify the delete.

**Comment by rolando-ebi** [comment]
In general, we can't structure references in any way such that "removing an entity removes references to that entity". Even in neo4j, this kind of cascading delete is implemented as a special kind of node deletion operation, `DETACH DELETE`. Regardless of how we structure references in mongo there will have to be some manual link clean-ups. But we can look at the likely delete submission scenarios and choose DBRefs that are most performant in those cases.

Outside of deleting submissions, I think it makes most sense for references to direct "upwards" e.g things refer to their source. This would make the kind of graph crawls we do at the moment a bit more performant. It would also simplify our permissions model, given that the owner of a node also owns the links that the node makes(at the moment, the links a node makes can be owned by a separate entity)

> References to Biomaterials and Files are stored on Process objects.

This would make cleanup a bit simpler as we would know that all links are always stored on Process objects. I wouldn't expect the runtime of the link-cleanup operation to change however.
