### ISSUE TITLE
Make file reference API endpoint handle duplicates

### ISSUE THREAD

**Issue by samanehsan** [HumanCellAtlas/ingest-central#64]
Currently, re-adding a file reference to a submission envelope will create a duplicate file reference. 

**To Reproduce**
Make a PUT request to `http://api.ingest.{env}.data.humancellatlas.org/processes/{submission_envelope_id}/fileReference` to add the same file record twice.

**Expected behaviour**
I expect that the endpoint would check if that file already exists in the submission envelope, and either throw a conflict error or just ignore the request and return a 200 status.

**Actual behaviour**
A duplicate record is created. 

**Impact**
If greenbox retries adding file references, we may end up creating duplicate information in the submission envelope.

**Comment by samanehsan** [comment]
I believe @rdgoite added a fix for this to ingest dev, but I opened this issue here for tracking purposes!

**Comment by rdgoite** [comment]
Ingest API has already been updated to address this issue. The current version deployed in the integration environment should behave as expected.
