### ISSUE TITLE
Not easy to delete submissions except by hunting in the submissions list

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#643]
At the moment, there's only a delete icon on the whole list of submissions.

![image.png](https://images.zenhubusercontent.com/5bc87e50dcb5ee160583aee9/b8045393-f721-4fb4-81ff-2adfdc93a8fb)

This makes it hard to select the correct submission to delete. Could we have a delete button on the list of submissions for the project? (as long as those submissions are incomplete?)

![image.png](https://images.zenhubusercontent.com/5bc87e50dcb5ee160583aee9/2d91ff9f-11d3-4c2c-aba3-fab944024aed)

**Comment by aaclan-ebi** [comment]
This has been implemented in https://app.zenhub.com/workspaces/ingest-dev-5cfe1cb26482e537cf35e8d1/issues/humancellatlas/ingest-central/628.
