### ISSUE TITLE
If the user tries to delete a completed submission they receive an uninformative error.

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#644]
Trying to delete a completed submission results in the following

![image.png](https://images.zenhubusercontent.com/5bc87e50dcb5ee160583aee9/5d974433-f5a2-4c66-a0ac-c0df5db79911)

We know we want to be able to force delete submissions for situations where the DSS goes out of sync with ingest (because of tests or redactions). However, I don't believe we have a situation where the user should be able to do it directly. Therefore, could we hide deletion icons for completed submissions in the UI?

**Comment by aaclan-ebi** [comment]
User won't be able to delete any complete submissions from the UI now. This has been implemented in 
 https://app.zenhub.com/workspaces/ingest-dev-5cfe1cb26482e537cf35e8d1/issues/humancellatlas/ingest-central/628
