### ISSUE TITLE
[Importer] Staging UI fails to import supplementary file

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/ingest-central#645]
**To Reproduce**

I was doing a testing submission in staging and attempting to upload an experiment with fastq files and one pdf protocol called `Single_cell_sorting_of_T_cells.pdf`

When I transferred the files to the upload s3 bucket I got the error
![Screenshot 2019-12-02 at 11 55 32](https://user-images.githubusercontent.com/13007987/69963376-0372d380-1508-11ea-8595-4e9842365978.png)

And when I look at the file that is in draft it looks like the file was uploaded to the bucket but the supplementary files tab failed to import correctly so the UI doesn't recognise it as a file that should be uploaded
![Screenshot 2019-12-02 at 13 32 26](https://user-images.githubusercontent.com/13007987/69963484-3026eb00-1508-11ea-88fa-30d09651dc4a.png)

The staging project id is: 0dfa9f6c-8f64-4bf6-87ca-967c49ff8640

**Expected behaviour**
    
I expected that the supplementary file tab would be imported and that the system would link the pdf file that was uploaded with the file in the `Supplementary file` tab

**Actual behaviour**

Ingest doesn't recognise the pdf file as a valid part of the submission

**Impact**

Cannot test this submission fully and therefore cannot progress the submission to production

**Screenshots or Messages**

See inline above

pinging @aaclan-ebi as I briefly chatted to her about it when I encountered the error.

**Comment by aaclan-ebi** [comment]
@mshadbolt could you upload the spreadsheet here?

**Comment by mshadbolt** [comment]
This is an unsubmitted dataset so I would prefer not to, I will send in a message

**Comment by rolando-ebi** [comment]
@mshadbolt The problem is actually in the sequence file tab. The last row looks wrong.

**Comment by mshadbolt** [comment]
right thanks, is there a way of making the spreadsheet validator throw an error that can be understood by a wrangler for an error like this?

**Comment by rolando-ebi** [comment]
Yeah there should be, the problem is that we should throw an error for file metadata that doesn't contain a "file_name", since a filename is required to create Files in ingest-core. I'll create a ticket for this with the specifics

**Comment by mshadbolt** [comment]
great thanks. I think this ticket can be resolved once that ticket is created.

**Comment by rolando-ebi** [comment]
New ticket here: https://app.zenhub.com/workspaces/ingest-dev-5cfe1cb26482e537cf35e8d1/issues/humancellatlas/ingest-central/651
