### ISSUE TITLE
[Importer] Throws error when importing spreadsheet

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/ingest-central#646]
**To Reproduce**

Upload [this spreadsheet](https://github.com/HumanCellAtlas/ingest-central/files/3911509/filled_example_SS2.xlsx) to the UI. 

**Expected behaviour**

The error message tells me what's wrong with the spreadsheet
    
**Actual behaviour**

Throws error:

`Max value is 14`

**Impact**

Not being able to upload a spreadsheet because of an unknown error is high impact.

**Screenshots or Messages**

Running the importer from my command line throws the same error:

![Screenshot 2019-12-02 at 13 42 47](https://user-images.githubusercontent.com/38617863/69964142-a8da7700-1509-11ea-9520-0779ac13eba5.png)

**Comment by ESapenaVentura** [comment]
@justincc you can close this ticket. This is not a bug related to ingest, it's a problem with openpyxl only being able to load 14 worksheets and weird interactions with notes!

**Comment by justincc** [comment]
Great, thanks Enrique
