### ISSUE TITLE
Showing all errors for metadata fields in ingest

### ISSUE THREAD

**Issue by willrockout** [HumanCellAtlas/ingest-central#65]
**What problem does the suggested enhancement solve? Please describe.**

Currently can only see 1 error at a time for fields in metadata. So have to fix and re-upload to catch all errors.

**What type of enhancement is this?**

Usability

**How will this enhancement benefit wrangers and/or end-users?**

Allows wranglers to fix all error related to an entity in one go.

**How complex to implement do you estimate this enhancement will be? (High, Medium, Low)**

Medium

**How much benefit do you estimate this enhancement will provide? (High, Medium, Low)**

High

**How urgent is this and is there a specific date it needs to be done by? (High, Medium, Low)**

Medium to Low

**Describe your preferred solution**

Provide a list of all errors stacked in the drop down.

**Comment by justincc** [comment]
Showing up to 5 errors would capture >80% of the problems.

**Comment by aaclan-ebi** [comment]
Fix deployed in production yesterday.
https://github.com/HumanCellAtlas/dcp/blob/prod/RELEASE_NOTES.md#ingest-ui-v091

All metadata validation errors are now being shown when metadata row is expanded.
[Screen Shot 2019-04-17 at 17.31.07.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/3916ce30-4175-4640-95f8-29ac09df0b11)

**Comment by willrockout** [comment]
@aaclan-ebi have you noticed if you expand all the page flashes or collapses every like 20 seconds?

**Comment by aaclan-ebi** [comment]
Yes, I'm not sure how to fix that yet, it's because the rows are being polled and rows are being refreshed every 4seconds  :( Please use the expand all functionality for now. Apologies for the inconvenience.

**Comment by willrockout** [comment]
No worries I've just been using the api link but it also does it when you use the expand all.

**Comment by aaclan-ebi** [comment]
Just to add more context, it looks like that the scrolling is being reset when even when using Expand All. Fixed this by setting automatically the row height for error details. 
![Screen Shot 2019-04-30 at 09 32 05](https://user-images.githubusercontent.com/31281398/56949691-727bea00-6b2b-11e9-9c3c-0d8c524c7217.png)

**Comment by aaclan-ebi** [comment]
I just notice now that the flashing happens when using safari browser. Please just use firefox/chrome as workaround.
