### ISSUE TITLE
In the JSON schema to spreadsheet converter, enforce enum fields.

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/ingest-central#70]
@malloryfreeberg commented on [Thu Nov 02 2017](https://github.com/HumanCellAtlas/metadata-schema/issues/59)

It was suggested by a user that having enum fields in a drop-down menu would aid spreadsheet filling. @simonjupp and @daniwelter suggested that it is possible to implement autofilling of a drop-down menu from enum JSON field.

---

@lauraclarke commented on [Tue Jul 10 2018](https://github.com/HumanCellAtlas/metadata-schema/issues/59#issuecomment-403927527)

@simonjupp @aaclan-ebi @rdgoite @daniwelter Was anything ever done about this, this issue is from a long time ago

If it wasn't done I am guessing that ingest-central or JIRA might be a better place for this than here?

---

@daniwelter commented on [Fri Jul 27 2018](https://github.com/HumanCellAtlas/metadata-schema/issues/59#issuecomment-408351235)

Yes, this is not a metadata issue and should be moved.

**Comment by lauraclarke** [comment]
As I couldn't edit the title of this I have created a new issue https://github.com/HumanCellAtlas/ingest-central/issues/71 and filled out a standard enhancement form. I am going to close this one as a duplicate
