### ISSUE TITLE
[UI/Upload] Blank entries appear in data

### ISSUE THREAD

**Issue by willrockout** [HumanCellAtlas/ingest-central#72]
**To Reproduce**
1. Import spreadsheet
2. Upload files not in sequence file tab 

**Expected behaviour**
No entries should appear for files not in spreadsheet.

**Actual behaviour**

Blank rows/entries appear for each file not in spreadsheet.

**Impact**

Clutters the ui and can be confusing to understand whats going on.

**Screenshots or Messages**

<img width="1193" alt="screen shot 2018-07-30 at 3 11 27 pm" src="https://user-images.githubusercontent.com/19597324/43426559-e2ee30fc-940a-11e8-8e2c-a41c9f72f49d.png">

**Comment by aaclan-ebi** [comment]
@willrockout , could you confirm if the uploaded files are specified in the spreadsheet?

**Comment by willrockout** [comment]
@aaclan-ebi The uploaded files are not in the spreadsheet.

**Comment by aaclan-ebi** [comment]
A blank file metadata is being added in ingest if there's any file uploaded in the submission's upload area. Instead of just showing a blank entry in the UI, a nice error/warning message should be shown to the user that the uploaded file is missing/awaiting its file metadata.

**Comment by aaclan-ebi** [comment]
Fix to this issue has been pushed to production last year. See changelog: https://api.ingest.dev.data.humancellatlas.org/files/5c5d7d69b07bf200060a1d17. Please reopen if issue still persists.
