### ISSUE TITLE
Dev Ingest UI HttpErrorResponse. 

### ISSUE THREAD

**Issue by cjvillar** [HumanCellAtlas/ingest-central#73]
**Spreadsheet not recognized by Ingest upload.**
"HttpErrorResponse: Http failure response for (unknown url): 0 Unknown Error"

**To Reproduce**
Please explain as much as you can about what you were doing when the bug was observed (to help us reproduce the error for testing).

1. Go to http://ui.ingest.dev.data.humancellatlas.org/submissions/new/metadata
2. Upload TM spreadsheet ( I can provide upon request) 
3. Click on Submit

**Expected behavior**
I expect the spreadsheet to upload.
    
**Please explain what actually happened.**
I get this error: HttpErrorResponse: Http failure response for (unknown url): 0 Unknown Error

**Impact**
We won't be able to upload spreadsheets. We also need more informative error messages.

**Comment by rolando-ebi** [comment]
Hey @cjvillar, can you send a link to the spreadsheet?

**Comment by cjvillar** [comment]
Sent to you via Slack. Thanks, @rolando-ebi

**Comment by rolando-ebi** [comment]
@cjvillar 
Looks like this is an HTTP timeout during the pre-processing of the spreadsheet. Despite the HTTP timeout, the spreadsheet eventually gets uploaded and processed:

http://ui.ingest.dev.data.humancellatlas.org/submissions/detail/5b630ddfe6294900068d0d4f/overview

@rdgoite @aaclan-ebi We need to discuss a mode of background pre-processing the spreadsheets and reporting the errors to ingest. Large spreadsheets like this won't get processed in <60s

**Comment by cjvillar** [comment]
Good to know. Thanks, Rolando! Closing this ticket.
