### ISSUE TITLE
Submission approval mechanism for phase 1

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/ingest-central#81]
As an HCA DCP wrangler, I need final approval of metadata/data from contributors for phase 1 data

We need to confirm with at least 1 person with authority on each project that (A) the metadata spreadsheet is accurate, (B) happy to publish, and (C) confirm happy with T&C form. Passive approval is fine.

All wranglers should follow the same protocol for final approval.

**Acceptance criteria**
- Method to produce summary information of a submission to send to the contributor for review
- Agree on final email text outlining this protocol (reviewed by wranglers and ux)
- Email all contributors 5 working days before scheduled submission into production.

**Comment by lauraclarke** [comment]
It would be good to see what is meant by a person of authority. That carries a weight which I don't think is reasonable in this context

**Comment by justincc** [comment]
Is this really a dev item or a metadata team item?

**Comment by claymfischer** [comment]
Would be nice to have the data contributor be able to click a button as a "sign off" of approval so we can begin pushing to the data store. Not sure that was the original intent here, though.

**Comment by hewgreen** [comment]
@justincc This required dev and wrangler input. We needed a tool that Rolando made and we also had some work to do as described. 

The tool was good enough to meet minimum wrangler requirements for phase 1. In the future we would like more tooling to support this use case. Maybe better summary statistics and the ability for a user to login and check their submission. This work will be submitted as separate tickets.
