### ISSUE TITLE
Example spreadsheets available for download in submission UI

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#92]
**What problem does the suggested enhancement solve? Please describe.**

As an HCA data contributor, I would like to be able to download an example metadata spreadsheet so that I can have a model to look at while I gather my own metadata.

**What type of enhancement is this?**

Usability

**How will this enhancement benefit wrangers and/or end-users?**

Make example metadata spreadsheet available to data contributors.

**How complex to implement do you estimate this enhancement will be? (High, Medium, Low)**

Low

**How much benefit do you estimate this enhancement will provide? (High, Medium, Low)**

Medium

**How urgent is this and is there a specific date it needs to be done by? (High, Medium, Low)**

Medium, not for phase 1.

**Describe your preferred solution**

On the same page where a data contributor can download a template spreadsheet, there should be an option to download an example metadata spreadsheet. Perhaps different versions for 10x, SS2, etc.

**Describe alternatives you've considered**

N/A

**Additional context**

Replaces HCA-276

**Comment by justincc** [comment]
Related to #87

**Comment by justincc** [comment]
Doesn't look like this will happen anytime soon and cleaning up our board to avoid estimating tasks that may never happen. Please bring it up again nearer the time.
