### ISSUE TITLE
Ability to visualize relationships between samples/files in submission

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#95]
**What problem does the suggested enhancement solve? Please describe.**

As a data generator, I would like to visualize the relationships between my submitted data and samples meets expectation so my data can be recreated accurately.

**What type of enhancement is this?**

Performance, usability

**How will this enhancement benefit wrangers and/or end-users?**

Help data contributors determine whether the metadata correctly captures the hierarchy/workflow of the experiment.

**How complex to implement do you estimate this enhancement will be? (High, Medium, Low)**

Medium

**How much benefit do you estimate this enhancement will provide? (High, Medium, Low)**

High

**How urgent is this and is there a specific date it needs to be done by? (High, Medium, Low)**

Medium, not required for phase 1, on roadmap for phase 2.

**Describe your preferred solution**

A neo4j graph generated from metadata and displayed to submitter in submission UI.

**Describe alternatives you've considered**

N/A

**Additional context**

Replaces HCA-594.

**Comment by justincc** [comment]
Visualization work tracked elsewhere, not immediate dev work

**Comment by malloryfreeberg** [comment]
This work is being developed in the [ingest-graph-validator](https://github.com/HumanCellAtlas/ingest-graph-validator) repo.
