### ISSUE TITLE
Upload a dataset and have it archived in EBI Repositories

### ISSUE THREAD

**Issue by ofanobilbao** [HumanCellAtlas/ingest-central#96]
As a contributor, I want to be able to upload a dataset and select to have it archived in ENA

**Comment by ofanobilbao** [comment]
HCA-1071

**Comment by morrisonnorman** [comment]
https://docs.google.com/document/d/1DY375E-jLPapPxm0dLMo3ySiKm3jcBLYI1mtTVuJwpc/edit#heading=h.rgrl71xfiho2

**Comment by justincc** [comment]
Closing as this is now achieved apart from #286 which can come when we next need to improve the archiving process.
