### ISSUE TITLE
Submit TMM to ENA

### ISSUE THREAD

**Issue by ofanobilbao** [HumanCellAtlas/ingest-central#97]
Submit TMM to ENA. Submit TMM files and XML to ENA

**Comment by ofanobilbao** [comment]
HCA-689

**Comment by justincc** [comment]
Where can I find HCA-689 or perhaps you could elaborate? (don't know what TMM is!)

**Comment by lauraclarke** [comment]
I dont think this is relevant anymore and can be closed

see https://www.ebi.ac.uk/seqdb/confluence/display/HCA/Project+Plan%3A+Getting+%27Preview%27+HCA+%28meta%29data+into+ENA
